import type { Metadata } from "next";
import Link from "next/link";
import { Eyebrow } from "@/components/eyebrow";
import { genosSource, genosSourceCommit } from "@/components/product-evidence";

export const metadata: Metadata = { title: "Développer avec GenOS", description: "Prise en main en français du runtime GenOS, de sa démo sans token et de ses contrats REST et MCP.", alternates: { canonical: "/fr/developers", languages: { en: "/en/developers", fr: "/fr/developers" } }, openGraph: { locale: "fr_FR" } };

export default function FrenchDevelopersPage() {
  return <div className="page-shell" lang="fr">
    <section className="page-hero section-wrap api-reference-hero"><Eyebrow>DÉVELOPPEURS · OPEN SOURCE</Eyebrow><h1>Essayer. Tracer.<br /><em>Faire évoluer.</em></h1><p>GenOS associe un workspace Rust, un plan de contrôle Node.js, des interfaces CLI et MCP. La démo locale sans token valide des mécanismes d’état et d’isolation, sans promettre le replay arbitraire de commandes externes.</p><div className="hero-actions"><a className="button button-dark" href={`https://github.com/PISSARAW/GenOS/tree/${genosSourceCommit}`} target="_blank" rel="noreferrer">Source examinée <span>↗</span></a><a className="button button-quiet" href={genosSource("examples/safe-debugging-demo/README.md")} target="_blank" rel="noreferrer">Démo sans token <span>↗</span></a></div></section>
    <section className="section-wrap french-dev-start"><div><Eyebrow>PRISE EN MAIN</Eyebrow><h2>Construire le runtime<br /><em>en local.</em></h2><p>Prérequis : Rust stable 1.88+, Node.js 22.12+, Git et outils de compilation C/C++ pour SQLite. Installez les dépendances du dépôt, du backend et du serveur MCP avant le build.</p><a className="text-link" href={genosSource("README.md")} target="_blank" rel="noreferrer">Guide d’installation complet ↗</a></div><div className="terminal-card"><div className="terminal-top"><span><i /><i /><i /></span><span>DÉVELOPPEMENT LOCAL</span><span>RUST · NODE</span></div><pre><code>git clone https://github.com/PISSARAW/GenOS.git{"\n"}cd GenOS{"\n"}git checkout {genosSourceCommit}{"\n"}npm ci{"\n"}npm ci --prefix backend{"\n"}npm ci --prefix mcp{"\n"}cargo build --workspace{"\n"}node examples/safe-debugging-demo/run-demo.mjs target/debug/genos</code></pre><div className="terminal-foot"><span>RUST 1.88+ · NODE 22.12+</span><a href={genosSource("examples/safe-debugging-demo/README.md")} target="_blank" rel="noreferrer">CONTRAT DE LA DÉMO ↗</a></div></div></section>
    <section className="section-wrap dev-note"><strong>Première mission avec modèle</strong><p>Copiez <code>.env.example</code> vers <code>.env</code>, configurez un modèle et démarrez son serveur d’inférence avant le backend. La configuration d’exemple utilise Ollama mais ne télécharge aucun modèle. Le MCP stdio n’expose aucun outil sans <code>GENOS_MCP_LEASE</code> ; les appels HTTP exigent aussi des permissions et un scope tenant.</p><a href={genosSource("mcp/README.md")} target="_blank" rel="noreferrer">Configuration MCP et lease ↗</a></section>
    <section className="section-wrap french-api-callout"><div><Eyebrow>INTÉGRATION D’OUTILS</Eyebrow><h2>REST et MCP,<br /><em>avec leurs contrats.</em></h2><p>L’API de documentation de GenOSWork et l’API runtime de GenOS ont des rôles différents. Consultez les routes, permissions, scope tenant et formats d’erreur avant de brancher un client.</p></div><Link className="button button-dark" href="/fr/api-mcp">Ouvrir la référence API / MCP <span>→</span></Link></section>
  </div>;
}
