/** Scientific and formal descriptions for catalog entries that lacked both. */
export type ScienceCompletion = { scienceEn: string; mathEn: string; scienceFr: string; mathFr: string };

export const scienceCompletions: Record<string, ScienceCompletion> = {
  "consciousness-taxonomy": {
    scienceEn: "Consciousness research distinguishes behavioral access, reportability and subjective experience. A software indicator can test a functional property; it cannot establish phenomenology without an accepted bridge principle.",
    mathEn: "Let I be a vector of separately measured indicators under test conditions T. Report I and uncertainty U(I|T); do not infer subjective experience S from I without a validated implication I⇒S.",
    scienceFr: "Les recherches sur la conscience séparent accès fonctionnel, rapport verbal et expérience subjective. Un indicateur logiciel teste une fonction, sans établir une phénoménologie.",
    mathFr: "Mesurer séparément les indicateurs I sous conditions T et leur incertitude U(I|T). L'implication I⇒expérience subjective n'est pas établie.",
  },
  "procedural-memory": {
    scienceEn: "Procedural memory in cognitive science concerns learned skills and action sequences. Here a procedure is a versioned software instruction with preconditions and outcome checks; storing it does not prove skill acquisition.",
    mathEn: "Represent procedure P=(preconditions, steps, postconditions, version). Permit invocation only if preconditions hold; accept success only if postconditions are independently checked.",
    scienceFr: "La mémoire procédurale humaine concerne les habiletés apprises. Ici, une procédure est une instruction logicielle versionnée dont les préconditions et résultats doivent être contrôlés.",
    mathFr: "Procédure P=(préconditions, étapes, postconditions, version). Exécuter si les préconditions tiennent ; accepter seulement après vérification des postconditions.",
  },
  "memory-fossilization": {
    scienceEn: "Fossils preserve traces of past organisms, not active behavior. The software analogy archives a closed lineage with provenance so later analysis can inspect it without reviving the process.",
    mathEn: "Archive A=(lineage, terminal state, evidence, digest). An archived branch is immutable; retrieval can inspect A but may not treat it as a live agent.",
    scienceFr: "Un fossile conserve une trace d'un organisme passé. L'analogie logicielle archive une lignée close et sa provenance, sans réactiver son processus.",
    mathFr: "Archive A=(lignée, état terminal, preuves, empreinte). La consultation de A ne rend pas la lignée active.",
  },
  morphogenesis: {
    scienceEn: "Biological morphogenesis produces form through local interactions and constraints. GenOS borrows graph composition and growth vocabulary for explicit topology operators; it does not model tissue mechanics or development.",
    mathEn: "Let G=(V,E) be a typed execution graph. Apply operator o only when its preconditions P_o(G) hold, then validate invariants I(o(G)) before admitting the new graph.",
    scienceFr: "La morphogenèse biologique produit des formes par interactions locales et contraintes. GenOS transpose ce principe à la composition explicite de graphes d'exécution.",
    mathFr: "Pour un graphe typé G=(V,E), appliquer l'opérateur o si P_o(G) est vrai, puis contrôler les invariants I(o(G)).",
  },
  "epistemic-meristem": {
    scienceEn: "A plant meristem is a region of active growth. The analogy denotes a controlled expansion of verified knowledge coverage: a gap must be demonstrated before growth is proposed.",
    mathEn: "For requirement set R and verified coverage C, gap set U=R\\C. A growth proposal targets u∈U only after its absence and verifier are recorded.",
    scienceFr: "Le méristème végétal est une zone de croissance. L'analogie désigne l'extension contrôlée d'une couverture de connaissances dont la lacune a été vérifiée.",
    mathFr: "Pour besoins R et couverture vérifiée C, lacunes U=R\\C. Proposer une extension pour u∈U après vérification de son absence.",
  },
  "unblocking-spiral": {
    scienceEn: "Adaptive search can escape repeated failure by changing representation or method. The spiral is an engineering escalation policy, not a biological law or a guarantee of progress.",
    mathEn: "If a blockage signature repeats k≥k_max times without verified progress ΔQ>0, choose a different admissible method m′ and stop when the budget B is exhausted.",
    scienceFr: "Une recherche adaptative peut changer de représentation ou de méthode après des échecs répétés. La spirale est une politique d'escalade, sans garantie de progrès.",
    mathFr: "Si un blocage revient k≥k_max fois sans progrès vérifié ΔQ>0, choisir une autre méthode admissible m′ sous budget B.",
  },
  "counterexample-cambium": {
    scienceEn: "A counterexample falsifies a universal claim under its stated assumptions. The cambium metaphor denotes a growing store of such examples, with conditions retained for valid reuse.",
    mathEn: "For claim ∀x∈D:P(x), a witnessed x*∈D with ¬P(x*) is a counterexample. Reuse requires matching domain and assumptions, not surface similarity.",
    scienceFr: "Un contre-exemple réfute une proposition universelle sous ses hypothèses. Le cambium évoque un registre qui s'accroît tout en conservant les conditions de validité.",
    mathFr: "Pour ∀x∈D:P(x), un témoin x*∈D tel que ¬P(x*) réfute la proposition. Sa réutilisation exige le même domaine et les mêmes hypothèses.",
  },
  chronotaxis: {
    scienceEn: "Time-dependent observation can miss short-lived events when sampling is periodic or delayed. Aperiodic schedules and receipts expose which windows were actually observed.",
    mathEn: "For event window W=[t_start,t_end] and observation times {t_i}, coverage holds only if some t_i∈W. Record expected and actual t_i to expose misses.",
    scienceFr: "Un échantillonnage temporel peut manquer un événement bref. Les échéances apériodiques et les reçus montrent les fenêtres réellement observées.",
    mathFr: "Pour fenêtre W=[t_début,t_fin] et observations {t_i}, la couverture exige au moins un t_i∈W. Conserver horaires prévus et réels.",
  },
  "risk-ledger": {
    scienceEn: "Statistical decision procedures spend a declared error budget across repeated tests. A ledger can bound promotion risk only if assumptions, dependence and actual decision rules are explicit.",
    mathEn: "For total risk allowance α, allocate α_i≥0 with Σ_i α_i≤α. A promotion consumes its declared allocation only after its test and evidence conditions pass.",
    scienceFr: "Les décisions statistiques répétées consomment un budget d'erreur déclaré. Un registre ne borne le risque que si hypothèses, dépendances et règles sont explicites.",
    mathFr: "Pour risque total α, allouer α_i≥0 avec Σ_i α_i≤α. Une promotion dépense sa part après contrôle du test et des preuves.",
  },
  "dynamic-organizations": {
    scienceEn: "Organization science and distributed algorithms study how coordination rules shape decisions. These nineteen software patterns declare roles and transitions; their existence does not demonstrate group effectiveness.",
    mathEn: "Model organization O=(members, roles, edges, decision rule). At each step, transition T_O(state,input) must preserve authority and resource invariants.",
    scienceFr: "Les sciences des organisations et les algorithmes distribués étudient l'effet des règles de coordination. Les dix-neuf schémas GenOS déclarent rôles et transitions.",
    mathFr: "Organisation O=(membres, rôles, liens, règle de décision). Chaque transition T_O doit préserver autorité et ressources.",
  },
  "worker-kinds": {
    scienceEn: "Typed role systems match task requirements to declared capabilities. Capability metadata is an admission condition, not evidence that a worker will complete the task correctly.",
    mathEn: "Worker w is eligible for task t when required(t)⊆capabilities(w) and permissions(w,t)=allow, subject to budget(w,t).",
    scienceFr: "Un système de rôles typés associe les besoins d'une tâche aux capacités déclarées. Cette compatibilité ne prouve pas la réussite du worker.",
    mathFr: "Worker w admissible pour t si besoins(t)⊆capacités(w), permissions(w,t)=autoriser et budget suffisant.",
  },
  "relational-physiology": {
    scienceEn: "Social and causal dependence affect how independent evidence can be counted. The software kernel records typed relations to constrain routing and quorum claims; a relation never grants authority.",
    mathEn: "For sources S, group known dependent origins into equivalence classes C(S). Effective vote count is |C(S)|, not |S|; unknown dependence must not be asserted independent.",
    scienceFr: "Les dépendances sociales et causales modifient le nombre de preuves réellement indépendantes. Le noyau encode les relations pour contraindre routage et quorum.",
    mathFr: "Regrouper les sources dépendantes S en classes C(S). Le nombre de voix effectives est |C(S)|, non |S| ; une indépendance inconnue reste inconnue.",
  },
  "communication-ecology": {
    scienceEn: "Communication systems depend on channel capacity, timing and noise. GenOS uses typed signals and bounded channels; the ecology metaphor does not imply biological communication.",
    mathEn: "A message m=(type, source, target, payload, time) is deliverable only if channel policy P(m)=allow. Measure delivery rate as acknowledged/eligible messages over a stated window.",
    scienceFr: "Une communication dépend du canal, du temps et du bruit. GenOS emploie des signaux typés et des canaux bornés ; l'écologie est une analogie.",
    mathFr: "Message m=(type, source, cible, contenu, temps) livrable si P(m)=autoriser. Taux de livraison = accusés/éligibles sur une fenêtre donnée.",
  },
  "signal-plane": {
    scienceEn: "Reliable messaging separates durable enqueueing from processing and acknowledgment. At-least-once delivery permits duplicates, so handlers need idempotent effects.",
    mathEn: "State machine pending→leased→acknowledged or retry. After k failures, backoff d_k=min(d_max,d_0·2^k); terminal quarantine follows the configured retry bound.",
    scienceFr: "Une messagerie fiable distingue persistance, traitement et accusé de réception. Une livraison au moins une fois peut produire des doublons.",
    mathFr: "Automate attente→bail→ACK ou reprise. Après k échecs, délai d_k=min(d_max,d_0·2^k), puis quarantaine à la borne fixée.",
  },
  "g-cir": {
    scienceEn: "A contract can make residual obligations explicit before a model invocation. The software mechanism combines typed admission, dependency tracking and visibility receipts; it does not prove the model understood its prompt.",
    mathEn: "Let O be versioned obligations and D their dependency DAG. Invoke only when admission A(input)=true; record hash H(prompt), recipient and model for each call, and retire o∈O only with a valid receipt.",
    scienceFr: "Un contrat rend explicites les obligations restantes avant un appel au modèle. L'admission typée et les reçus de visibilité ne prouvent pas la compréhension du prompt.",
    mathFr: "Obligations versionnées O et dépendances D. Invoquer si A(entrée)=vrai ; tracer H(prompt), destinataire et modèle, puis clore o∈O sur reçu valide.",
  },
  "mission-continuity": {
    scienceEn: "Distributed ownership and durable state permit continuation after process loss, but recovery must arbitrate competing owners and avoid duplicate effects.",
    mathEn: "For mission m, at most one valid lease owner may launch successor s at time t. Resume requires lease(m,t)=valid, completion contract unsatisfied and wake condition true.",
    scienceFr: "La persistance permet de reprendre après la perte d'un processus, à condition d'arbitrer les propriétaires et d'éviter les effets dupliqués.",
    mathFr: "Pour mission m, au plus un propriétaire doté d'un bail valide lance un successeur. Reprise si bail valide, contrat inachevé et condition de réveil vraie.",
  },
  "agent-git": {
    scienceEn: "Version control represents changes as immutable history and branches. Applying the idea to agent state supports comparison and replay only for state included in the recorded boundary.",
    mathEn: "A commit c=(parent, state digest, metadata). Branches identify commits; merge M(c1,c2) must resolve conflicting state and retain provenance.",
    scienceFr: "Le contrôle de version conserve un historique et des branches immuables. Appliqué à un agent, il ne permet de rejouer que l'état inclus dans la frontière enregistrée.",
    mathFr: "Commit c=(parent, empreinte d'état, métadonnées). La fusion M(c1,c2) résout les conflits et conserve la provenance.",
  },
  biome: {
    scienceEn: "Ecological biomes combine niches, resources and interacting populations. GenOS models a bounded resource and niche allocation; its caller-invoked operations are not an autonomous ecosystem.",
    mathEn: "For niches i with demand d_i and allocation a_i, require a_i≥0 and Σ_i a_i≤B. Report unmet demand max(0,d_i−a_i) before changing placement.",
    scienceFr: "Un biome écologique combine niches, ressources et populations. GenOS modélise une allocation bornée, sans écosystème autonome complet.",
    mathFr: "Pour chaque niche i, demande d_i et allocation a_i≥0 avec Σ_i a_i≤B. Besoin non servi = max(0,d_i−a_i).",
  },
  plasmids: {
    scienceEn: "Bacterial plasmids are mobile genetic elements that can carry traits between cells. A GenOS plasmid is a transferable capability package; transfer requires compatibility and authority checks.",
    mathEn: "Transfer package p from donor d to recipient r only if schema(p), compatible(p,r), authorized(d,r,p) and budget constraints all hold.",
    scienceFr: "Les plasmides bactériens sont des éléments génétiques mobiles qui transportent des traits. GenOS transpose l'idée à un paquet de capacité soumis à compatibilité et autorisation.",
    mathFr: "Transférer p de d vers r si schéma(p), compatible(p,r), autorisé(d,r,p) et budget sont tous satisfaits.",
  },
  "horizontal-transfer": {
    scienceEn: "Horizontal gene transfer moves genetic material outside parent-to-offspring inheritance. Here it is a governed movement of a software capability or artifact between lineages.",
    mathEn: "Lineage update L_r′=admit(L_r,p) only if provenance(p)=L_d and compatibility, validation and authority gates pass.",
    scienceFr: "Le transfert horizontal de gènes passe entre lignées sans filiation parent-enfant. GenOS en retient la structure pour déplacer une capacité logicielle gouvernée.",
    mathFr: "Lignée receveuse L_r′=admettre(L_r,p) si provenance(p)=L_d et si compatibilité, validation et autorité sont vérifiées.",
  },
  niches: {
    scienceEn: "An ecological niche describes a species' environmental conditions and role. The software analogy partitions work contexts by resource availability and suitable capabilities.",
    mathEn: "For task t and niche n, fit F(t,n)=compatible(capability_n,requirements_t) subject to resource_n≥cost_t; compare measured outcomes separately.",
    scienceFr: "Une niche écologique associe conditions et rôle d'une espèce. L'analogie partitionne les contextes de travail selon ressources et capacités pertinentes.",
    mathFr: "Adéquation F(t,n)=compatible(capacités_n,besoins_t) sous contrainte ressources_n≥coût_t ; mesurer ensuite le résultat.",
  },
  cryptobiosis: {
    scienceEn: "Cryptobiosis is a biological state with greatly reduced detectable metabolism during stress. The software analogy is explicit dormancy with preserved state and a guarded wake condition, not suspended life.",
    mathEn: "State transition active→dormant requires stress≥τ and a durable checkpoint. dormant→active requires wake predicate W(state,event)=true and valid ownership.",
    scienceFr: "La cryptobiose réduit fortement l'activité métabolique dans certaines conditions. GenOS transpose l'idée à une dormance explicite avec état préservé et réveil contrôlé.",
    mathFr: "Transition actif→dormant si stress≥τ et checkpoint durable ; dormant→actif si W(état,événement)=vrai et propriété valide.",
  },
  "natural-creative-ecology": {
    scienceEn: "Evolutionary search combines variation, inheritance and selection under environmental constraints. Novelty search adds a declared diversity objective; neither guarantees useful innovation.",
    mathEn: "For candidate x, score J(x)=quality(x)+λ·novelty(x) subject to safety and budget constraints. Selection uses measured outcomes, not novelty alone.",
    scienceFr: "La recherche évolutionnaire combine variation, héritage et sélection sous contraintes. Une mesure de nouveauté favorise l'exploration sans garantir une innovation utile.",
    mathFr: "Score candidat J(x)=qualité(x)+λ·nouveauté(x) sous contraintes de sécurité et budget ; sélectionner sur résultats mesurés.",
  },
  sensorium: {
    scienceEn: "Animal perception integrates multiple sensory streams under attention and uncertainty. GenOS sensorium is a typed observation interface; simulated and measured inputs must stay distinguishable.",
    mathEn: "Observation o=(modality,value,time,source,uncertainty). Fusion F({o_i}) may occur only for compatible scope and time windows, with provenance retained.",
    scienceFr: "La perception animale combine plusieurs modalités avec incertitude. Le sensorium GenOS est une interface d'observations typées où simulation et mesure restent distinctes.",
    mathFr: "Observation o=(modalité,valeur,temps,source,incertitude). Fusion F({o_i}) seulement pour portée et temps compatibles, avec provenance.",
  },
  resilience: {
    scienceEn: "Resilience research studies recovery after disturbance. In software it requires measured service restoration under a declared fault and recovery budget; mere retrying is not proof of resilience.",
    mathEn: "For quality Q(t), baseline Q0 and disturbance at t0, recovery time T_r=inf{t≥t0:Q(t)≥q_min}. Report fault conditions and incomplete recovery.",
    scienceFr: "La résilience concerne le rétablissement après perturbation. En logiciel, elle exige une mesure de service restauré sous faute et budget déclarés.",
    mathFr: "Pour qualité Q(t) et perturbation à t0, temps de reprise T_r=inf{t≥t0:Q(t)≥q_min}. Déclarer faute et reprise incomplète.",
  },
  development: {
    scienceEn: "Biological development changes form and function across stages through regulated processes. A software lineage can use staged transitions, but this is an authored state machine rather than organismal ontogeny.",
    mathEn: "For stages s_i, permit transition s_i→s_j only when guard g_ij(state,evidence)=true; preserve lineage and invariants across the transition.",
    scienceFr: "Le développement biologique transforme forme et fonction par étapes régulées. Une lignée logicielle reprend l'idée comme automate explicite, sans ontogenèse vivante.",
    mathFr: "Transition s_i→s_j si garde g_ij(état,preuves)=vrai, avec préservation de la lignée et des invariants.",
  },
  symbionts: {
    scienceEn: "Symbiosis describes sustained interactions between different organisms that may benefit or harm participants. Software specialists are admitted services, not living symbionts; their contribution must be measured.",
    mathEn: "Host H admits service S only if capability(S)⊇required(H), cost(S)≤remaining budget and lifecycle policy permits attachment.",
    scienceFr: "La symbiose désigne une interaction durable entre organismes, bénéfique ou non. Les symbiotes GenOS sont des services spécialisés admis sous contrat.",
    mathFr: "L'hôte H admet S si capacité(S)⊇besoin(H), coût(S)≤budget restant et cycle de vie autorisé.",
  },
  foveation: {
    scienceEn: "Visual systems concentrate high-resolution sampling near the fovea while surveying a wider field at lower detail. The software analogy selects a region for deeper inspection under cost limits.",
    mathEn: "Choose region r*=argmax_r value(r)/cost(r) subject to inspection budget B; record what remained outside the high-resolution window.",
    scienceFr: "La vision concentre une haute résolution près de la fovéa et observe le reste avec moins de détail. GenOS sélectionne une région à inspecter sous budget.",
    mathFr: "Choisir région r*=argmax_r valeur(r)/coût(r) sous budget B ; tracer les zones non inspectées en haute résolution.",
  },
  "animal-senses": {
    scienceEn: "Animal senses transduce physical stimuli through modality-specific receptors. GenOS uses sensing metaphors for software inputs; it does not possess biological receptors or subjective perception.",
    mathEn: "For modality m, measurement y_m=h_m(x)+ε_m. State sensor range, resolution and noise ε_m before combining observations.",
    scienceFr: "Les sens animaux transforment des stimuli physiques au moyen de récepteurs propres à chaque modalité. GenOS n'a que des entrées logicielles déclarées.",
    mathFr: "Pour modalité m, mesure y_m=h_m(x)+ε_m. Déclarer plage, résolution et bruit ε_m avant la fusion.",
  },
  "animal-control-primitives": {
    scienceEn: "Simple animal behaviors can emerge from local stimulus-response loops. Software primitives borrow this control structure; their correctness depends on specified triggers, authority and measured outcomes.",
    mathEn: "Controller a_t=π(o_t) applies only if guard(o_t,authority,budget)=true. Evaluate stability and unintended effects across repeated steps.",
    scienceFr: "Certains comportements animaux reposent sur des boucles locales stimulus-réponse. Les primitives logicielles reprennent cette structure sous gardes et mesures.",
    mathFr: "Contrôleur a_t=π(o_t) si garde(observation,autorité,budget)=vrai. Mesurer stabilité et effets indésirables.",
  },
  nosology: {
    scienceEn: "Medical nosology organizes diseases by observable patterns and causes. A software failure taxonomy borrows classification discipline but is not a medical diagnostic system.",
    mathEn: "Define classes C with explicit inclusion predicates P_c(x). Multi-label classification returns {c∈C:P_c(x)} and uncertainty, followed by independent response verification.",
    scienceFr: "La nosologie médicale classe les maladies selon observations et causes. Une taxonomie logicielle emprunte cette discipline sans devenir un diagnostic médical.",
    mathFr: "Classes C avec prédicats P_c(x). Classer par {c∈C:P_c(x)} et incertitude, puis vérifier séparément la réponse.",
  },
  autoimmune: {
    scienceEn: "Autoimmune disease involves immune responses against self components. The software metaphor describes safeguards that flag authorized behavior; measure false positives before intervention.",
    mathEn: "False-positive rate FPR=FP/(FP+TN) on a declared authorized-behavior set. A response gate should account for both harm from intervention and missed threats.",
    scienceFr: "L'auto-immunité biologique vise des composants du soi. L'analogie décrit une protection logicielle qui bloque une activité légitime.",
    mathFr: "Taux de faux positifs FPR=FP/(FP+TN) sur un jeu d'activités légitimes déclaré ; comparer les coûts d'intervention et d'omission.",
  },
  degenerative: {
    scienceEn: "Degeneration is progressive loss of structure or function. The runtime category tracks declining capability or state quality over time; causal diagnosis requires more than a trend.",
    mathEn: "For quality Q_t, flag sustained decline only when slope(Q_{t−k:t})<−τ across a declared window and measurement uncertainty is controlled.",
    scienceFr: "La dégénérescence est une perte progressive de structure ou de fonction. La catégorie logicielle suit une baisse de qualité sans en déduire automatiquement la cause.",
    mathFr: "Signaler un déclin si pente(Q_{t−k:t})<−τ sur une fenêtre déclarée, après contrôle de l'incertitude de mesure.",
  },
  infectious: {
    scienceEn: "Infection spreads through contact and transmission paths. The software analogy tracks unwanted propagation of a bad artifact or state across workspaces, without implying a pathogen.",
    mathEn: "On graph G=(V,E), exposure set R_{t+1}=R_t∪neighbors(R_t) subject to actual transfer events; containment removes or blocks implicated edges.",
    scienceFr: "Une infection se propage par des voies de transmission. L'analogie suit un artefact ou état fautif entre workspaces, sans agent pathogène.",
    mathFr: "Sur graphe G=(V,E), exposition R_{t+1}=R_t∪voisins(R_t) selon transferts observés ; contenir en bloquant les liens en cause.",
  },
  "genetic-pathology": {
    scienceEn: "Inherited genetic variants can affect biological function. Here the category concerns harmful traits encoded in a versioned agent model; genotype-to-effect claims need controlled comparison.",
    mathEn: "Compare outcome Y(G′,E)−Y(G,E) under matched environment E before attributing a failure to changed inherited configuration G′.",
    scienceFr: "Des variantes génétiques héritées peuvent modifier une fonction biologique. Ici, la catégorie vise des traits nuisibles dans un modèle agent versionné.",
    mathFr: "Comparer Y(G′,E)−Y(G,E) sous le même environnement E avant d'attribuer l'échec au trait modifié G′.",
  },
  cancerous: {
    scienceEn: "Cancer involves dysregulated cell proliferation and selection. The software analogy concerns uncontrolled process or artifact growth; it does not model tumors or cancer biology.",
    mathEn: "Let N_t be active descendants; flag expansion when N_{t+1}>N_max or growth rate (N_{t+1}−N_t)/max(1,N_t)>g_max under declared policy.",
    scienceFr: "Le cancer implique une prolifération cellulaire dérégulée. L'analogie logicielle vise une croissance de processus ou d'artefacts non autorisée.",
    mathFr: "Pour descendants actifs N_t, alerter si N_{t+1}>N_max ou si (N_{t+1}−N_t)/max(1,N_t)>g_max.",
  },
  "metabolic-pathology": {
    scienceEn: "Metabolic disease disrupts energy or material processing in organisms. Software resource pathology concerns unsustainable budget use; units and allocation rules must be stated.",
    mathEn: "For available budget B_t and consumption c_t, deficit D_t=max(0,c_t−B_t). Persistent D_t>0 requires throttling or replanning, not biological treatment.",
    scienceFr: "Une maladie métabolique perturbe des transformations biologiques. En logiciel, la catégorie décrit une consommation de ressources non soutenable.",
    mathFr: "Pour budget B_t et consommation c_t, déficit D_t=max(0,c_t−B_t). Un déficit durable impose limitation ou replanification.",
  },
  cardiovascular: {
    scienceEn: "Cardiovascular circulation moves blood through a bounded network. The software analogy concerns blocked information or control flow; it does not represent blood pressure or physiology.",
    mathEn: "For channel e, throughput q_e=delivered_e/window and backlog b_e=arrivals_e−delivered_e. A bottleneck appears when sustained arrivals exceed service capacity.",
    scienceFr: "La circulation cardiovasculaire déplace le sang dans un réseau. L'analogie logicielle vise un goulot de flux d'information, sans physiologie sanguine.",
    mathFr: "Pour canal e, débit q_e=livrés/fenêtre et arriéré b_e=arrivées−livrés ; le goulot persiste si les arrivées dépassent la capacité.",
  },
  psychiatric: {
    scienceEn: "Psychiatric conditions concern people and require clinical assessment. The GenOS label is only a metaphor for unstable software decisions; no mental-health inference is made.",
    mathEn: "Measure decision variance Var(a_t|matched inputs) and constraint violations over a declared test set. A high value prompts software investigation, not diagnosis.",
    scienceFr: "Les troubles psychiatriques concernent des personnes et exigent une évaluation clinique. Le terme GenOS ne décrit que des décisions logicielles instables.",
    mathFr: "Mesurer variance des décisions Var(a_t|entrées comparables) et violations de contraintes sur un jeu déclaré ; cela n'est pas un diagnostic.",
  },
  "environmental-pathology": {
    scienceEn: "Environmental exposures can alter biological health. Software failures may likewise depend on configuration, network, load or external services; isolate conditions before claiming causation.",
    mathEn: "Estimate effect Δ=Y(environment E1)−Y(environment E0) under matched workload and version. Record confounders and repeated measurements.",
    scienceFr: "Des expositions environnementales influencent la santé biologique. Les défaillances logicielles peuvent dépendre de charge, réseau ou configuration.",
    mathFr: "Estimer Δ=Y(environnement E1)−Y(environnement E0) à charge et version comparables, avec répétitions et facteurs confondants.",
  },
  vfs: {
    scienceEn: "A virtual filesystem separates logical paths and operations from backing storage. Access control must be enforced during path resolution and operation, including traversal and aliasing cases.",
    mathEn: "Resolve normalized path p to resource r only if r lies within allowed root R and policy(actor,operation,r)=allow; reject traversal outside R.",
    scienceFr: "Un système de fichiers virtuel sépare chemins logiques et stockage réel. La résolution doit appliquer les droits, y compris face aux traversées de chemin.",
    mathFr: "Résoudre p vers ressource r si r appartient à racine autorisée R et politique(acteur,opération,r)=autoriser ; refuser toute sortie de R.",
  },
};
