/** Concept-specific teaching sequences. These describe a model, not a runtime trace. */
export type TeachingFlow = { en: [string, string, string]; fr: [string, string, string] };

export const teachingFlows: Record<string, TeachingFlow> = {
  maladies: { en: ["Observe failure signals", "Classify a software pathology", "Contain and reassess"], fr: ["Observer les signaux de défaillance", "Classer la pathologie logicielle", "Contenir puis réévaluer"] },
  "adaptive-epistemic-immunity": { en: ["Receive a questionable claim", "Check source and anomaly", "Quarantine or release"], fr: ["Recevoir une affirmation douteuse", "Contrôler source et anomalie", "Isoler ou libérer"] },
  "immune-system": { en: ["Sense a threat signal", "Test detection and authority", "Apply bounded response"], fr: ["Détecter un signal de menace", "Vérifier détection et autorité", "Appliquer une réponse bornée"] },
  nosology: { en: ["Collect observed failures", "Separate failure classes", "Revise the taxonomy"], fr: ["Recueillir les défaillances", "Séparer les classes", "Réviser la taxonomie"] },
  pathologies: { en: ["Record telemetry", "Match failure patterns", "Verify a remedy"], fr: ["Enregistrer la télémétrie", "Reconnaître les motifs", "Vérifier le remède"] },
  autoimmune: { en: ["Detect self-directed alert", "Estimate false positive", "Reduce harmful response"], fr: ["Détecter une alerte contre soi", "Estimer le faux positif", "Réduire la réponse nuisible"] },
  degenerative: { en: ["Measure capability over time", "Identify persistent decline", "Test restoration"], fr: ["Mesurer la capacité dans le temps", "Repérer le déclin durable", "Tester la restauration"] },
  infectious: { en: ["Trace a faulty artifact", "Map its propagation", "Isolate affected scope"], fr: ["Tracer un artefact fautif", "Cartographier sa propagation", "Isoler la portée touchée"] },
  "genetic-pathology": { en: ["Inspect inherited configuration", "Locate faulty trait", "Validate a corrected lineage"], fr: ["Examiner la configuration héritée", "Localiser le trait fautif", "Valider une lignée corrigée"] },
  cancerous: { en: ["Observe uncontrolled expansion", "Check growth limits", "Stop unauthorized replication"], fr: ["Observer la croissance incontrôlée", "Vérifier les limites", "Arrêter la réplication non autorisée"] },
  "metabolic-pathology": { en: ["Read resource demand", "Find allocation imbalance", "Restore budget bounds"], fr: ["Lire la demande de ressources", "Repérer le déséquilibre", "Rétablir les bornes du budget"] },
  cardiovascular: { en: ["Observe information flow", "Locate blocked channel", "Restore bounded circulation"], fr: ["Observer le flux d'information", "Localiser le canal bloqué", "Rétablir une circulation bornée"] },
  psychiatric: { en: ["Observe unstable decisions", "Check feedback and context", "Require independent review"], fr: ["Observer les décisions instables", "Contrôler retour et contexte", "Exiger une revue indépendante"] },
  "environmental-pathology": { en: ["Record external conditions", "Link condition to failure", "Mitigate the exposure"], fr: ["Relever les conditions externes", "Relier condition et défaillance", "Réduire l'exposition"] },

  memoire: { en: ["Encode an episode", "Rank stored candidates", "Retrieve with provenance"], fr: ["Encoder un épisode", "Classer les candidats stockés", "Récupérer avec provenance"] },
  "episodic-memory": { en: ["Record context and action", "Attach observation and outcome", "Retrieve an episode"], fr: ["Enregistrer contexte et action", "Joindre observation et résultat", "Retrouver un épisode"] },
  "semantic-memory": { en: ["Extract a proposition", "Index relations and sources", "Retrieve scoped knowledge"], fr: ["Extraire une proposition", "Indexer relations et sources", "Retrouver un savoir borné"] },
  "vector-memory": { en: ["Embed a query and records", "Compute vector similarity", "Check retrieved candidates"], fr: ["Projeter requête et éléments", "Calculer la similarité", "Vérifier les candidats retrouvés"] },
  "procedural-memory": { en: ["Capture a verified procedure", "Match its preconditions", "Execute under policy"], fr: ["Conserver une procédure vérifiée", "Comparer ses préconditions", "Exécuter sous politique"] },
  "synaptic-plasticity": { en: ["Observe an update signal", "Adjust bounded association", "Evaluate later retrieval"], fr: ["Observer un signal d'apprentissage", "Ajuster l'association bornée", "Évaluer la récupération future"] },
  stdp: { en: ["Measure spike order", "Apply timing window", "Bound the weight change"], fr: ["Mesurer l'ordre des impulsions", "Appliquer la fenêtre temporelle", "Borner le changement de poids"] },
  "memory-fossilization": { en: ["Close a lineage", "Preserve its evidence", "Retrieve historical lessons"], fr: ["Clore une lignée", "Conserver ses preuves", "Retrouver les leçons passées"] },
  "memory-retrieval": { en: ["Form a scoped query", "Rank eligible records", "Return evidence-linked context"], fr: ["Former une requête bornée", "Classer les éléments admissibles", "Rendre un contexte sourcé"] },

  cortex: { en: ["Receive a request", "Search distributed indexes", "Check the assembled answer"], fr: ["Recevoir une demande", "Chercher dans les index répartis", "Vérifier la réponse assemblée"] },
  agow: { en: ["Admit candidate frames", "Compete for attention", "Broadcast selected content"], fr: ["Admettre des cadres candidats", "Mettre en concurrence l'attention", "Diffuser le contenu retenu"] },
  gvx: { en: ["Isolate a candidate change", "Evaluate its evidence", "Gate maturity or promotion"], fr: ["Isoler un changement candidat", "Évaluer ses preuves", "Conditionner maturité ou promotion"] },
  "self-model": { en: ["Read versioned identity", "Update bounded self-description", "Check continuity claims"], fr: ["Lire l'identité versionnée", "Actualiser l'auto-description", "Vérifier la continuité"] },
  "theory-of-self": { en: ["Define identity criteria", "Compare consecutive states", "Report bounded continuity"], fr: ["Définir les critères d'identité", "Comparer deux états successifs", "Décrire la continuité bornée"] },
  "predictive-system": { en: ["Issue a forecast", "Observe resolved outcome", "Score prediction error"], fr: ["Émettre une prévision", "Observer le résultat résolu", "Mesurer l'erreur de prévision"] },
  "natural-search-control-plane": { en: ["Measure search pressure", "Choose a bounded action", "Stop or update hypothesis"], fr: ["Mesurer la pression de recherche", "Choisir une action bornée", "Arrêter ou réviser l'hypothèse"] },
  attention: { en: ["Collect candidate signals", "Rank by salience and cost", "Allocate limited focus"], fr: ["Recueillir les signaux candidats", "Classer saillance et coût", "Allouer l'attention limitée"] },
  "consciousness-taxonomy": { en: ["Name a claimed property", "Separate observable indicators", "Limit the inference"], fr: ["Nommer la propriété alléguée", "Séparer les indices observables", "Borner l'inférence"] },
  "functional-indicators": { en: ["Define an observable test", "Measure behavior and uncertainty", "Report only the tested property"], fr: ["Définir un test observable", "Mesurer comportement et incertitude", "Rapporter la seule propriété testée"] },

  ontogenese: { en: ["Select eligible mission", "Execute and verify", "Integrate or resume"], fr: ["Choisir une mission admissible", "Exécuter et vérifier", "Intégrer ou reprendre"] },
  genome: { en: ["Read inherited configuration", "Apply permitted transformation", "Validate derived profile"], fr: ["Lire la configuration héritée", "Appliquer une transformation permise", "Valider le profil dérivé"] },
  epigenetics: { en: ["Read inherited traits", "Apply contextual expression rule", "Observe effective trait"], fr: ["Lire les traits hérités", "Appliquer la règle contextuelle", "Observer le trait effectif"] },
  "agent-dna": { en: ["Parse versioned artifact", "Validate schema and identity", "Hand off to separate runtime"], fr: ["Lire l'artefact versionné", "Valider schéma et identité", "Transmettre au runtime distinct"] },
  phenotype: { en: ["Combine traits and context", "Resolve override precedence", "Observe runtime profile"], fr: ["Combiner traits et contexte", "Résoudre la priorité des règles", "Observer le profil runtime"] },
  instinct: { en: ["Detect an authored trigger", "Evaluate guard and authority", "Choose bounded response"], fr: ["Détecter le déclencheur défini", "Vérifier garde et autorité", "Choisir la réponse bornée"] },
  reproduction: { en: ["Select parent models", "Transform inherited data", "Validate child artifact"], fr: ["Choisir les modèles parents", "Transformer les données héritées", "Valider l'artefact enfant"] },
  "speciation-graft": { en: ["Propose a new lineage", "Test compatibility", "Review evidence before adoption"], fr: ["Proposer une nouvelle lignée", "Tester la compatibilité", "Examiner les preuves avant adoption"] },

  ontologie: { en: ["Define entities", "Relate possible worlds", "Qualify conclusions"], fr: ["Définir les entités", "Relier les mondes possibles", "Qualifier les conclusions"] },
  epistemics: { en: ["State a scoped claim", "Attach evidence and uncertainty", "Revise the judgment"], fr: ["Formuler une affirmation bornée", "Joindre preuves et incertitude", "Réviser le jugement"] },
  beliefs: { en: ["Record proposition and confidence", "Receive new evidence", "Revise versioned belief"], fr: ["Noter proposition et confiance", "Recevoir une nouvelle preuve", "Réviser la croyance versionnée"] },
  claims: { en: ["State assessable proposition", "Collect support and challenge", "Assign qualified status"], fr: ["Formuler une proposition vérifiable", "Réunir appuis et objections", "Attribuer un statut qualifié"] },
  evidence: { en: ["Collect an observation", "Check method and provenance", "Relate it to a claim"], fr: ["Recueillir une observation", "Contrôler méthode et provenance", "La relier à une affirmation"] },
  contradictions: { en: ["Retain opposing claims", "Compare scope and provenance", "Resolve or preserve conflict"], fr: ["Conserver les affirmations opposées", "Comparer portée et provenance", "Résoudre ou maintenir le conflit"] },
  provenance: { en: ["Identify a source", "Trace transformations", "Audit a derived claim"], fr: ["Identifier une source", "Tracer les transformations", "Auditer l'affirmation dérivée"] },
  "brier-calibration": { en: ["Record forecast probability", "Wait for resolved outcome", "Calculate squared error"], fr: ["Noter la probabilité prévue", "Attendre le résultat résolu", "Calculer l'erreur quadratique"] },
  gettier: { en: ["State belief and reasons", "Test truth and causal link", "Expose lucky correctness"], fr: ["Énoncer croyance et raisons", "Tester vérité et lien causal", "Révéler la vérité accidentelle"] },
  knowledge: { en: ["Collect scoped claims", "Link support and conflict", "Report justified conclusion"], fr: ["Réunir des affirmations bornées", "Relier appui et conflit", "Rapporter la conclusion justifiée"] },

  morphogenesis: { en: ["Read topology and operators", "Compose bounded graph", "Validate executable transition"], fr: ["Lire topologie et opérateurs", "Composer un graphe borné", "Valider la transition exécutable"] },
  "epistemic-meristem": { en: ["Detect coverage gap", "Revalidate evidence", "Propose bounded growth"], fr: ["Détecter une lacune de couverture", "Revérifier la preuve", "Proposer une croissance bornée"] },
  "unblocking-spiral": { en: ["Detect repeated blockage", "Change method or scope", "Verify renewed progress"], fr: ["Détecter le blocage répété", "Changer méthode ou portée", "Vérifier la reprise"] },
  "counterexample-cambium": { en: ["Capture counterexample", "Preserve its conditions", "Gate later reuse"], fr: ["Capturer le contre-exemple", "Conserver ses conditions", "Conditionner sa réutilisation"] },
  chronotaxis: { en: ["Schedule observation", "Record temporal receipt", "Expose missed window"], fr: ["Planifier l'observation", "Enregistrer un reçu temporel", "Révéler la fenêtre manquée"] },
  "risk-ledger": { en: ["Allocate risk budget", "Account for a proposal", "Permit or refuse promotion"], fr: ["Allouer le budget de risque", "Comptabiliser la proposition", "Autoriser ou refuser la promotion"] },
  "dynamic-organizations": { en: ["Choose organization rule", "Assign members and edges", "Apply decision procedure"], fr: ["Choisir la règle d'organisation", "Affecter membres et liens", "Appliquer la procédure de décision"] },
  "worker-kinds": { en: ["Declare task needs", "Match worker capability", "Enforce role constraints"], fr: ["Déclarer les besoins de la tâche", "Associer les capacités du worker", "Appliquer les contraintes du rôle"] },
  "resident-daemons": { en: ["Observe durable state", "Apply daemon policy", "Record bounded action"], fr: ["Observer l'état durable", "Appliquer la politique du daemon", "Enregistrer l'action bornée"] },
  "agent-relationships": { en: ["Declare relation edge", "Measure active interaction", "Constrain routing"], fr: ["Déclarer un lien relationnel", "Mesurer l'interaction active", "Contraindre le routage"] },
  "relational-physiology": { en: ["Load scoped relations", "Check independence and authority", "Dispatch reduced content"], fr: ["Charger les relations bornées", "Vérifier indépendance et autorité", "Transmettre un contenu réduit"] },
  "communication-ecology": { en: ["Emit typed signal", "Select permitted channel", "Observe receipt and response"], fr: ["Émettre un signal typé", "Choisir le canal permis", "Observer réception et réponse"] },
  "signal-plane": { en: ["Persist addressed signal", "Deliver or escalate", "ACK or retry with lease"], fr: ["Persister le signal adressé", "Livrer ou escalader", "Accuser réception ou réessayer"] },
  "g-cir": { en: ["Admit typed input", "Resolve remaining obligations", "Attest invocation visibility"], fr: ["Admettre l'entrée typée", "Résoudre les obligations restantes", "Attester la visibilité de l'invocation"] },
  "mission-continuity": { en: ["Check completion contract", "Reserve durable owner", "Resume or regenerate"], fr: ["Vérifier le contrat d'achèvement", "Réserver le propriétaire durable", "Reprendre ou régénérer"] },
  "agent-git": { en: ["Version agent state", "Branch and compare", "Replay or merge with evidence"], fr: ["Versionner l'état agent", "Brancher et comparer", "Rejouer ou fusionner avec preuves"] },
  "counterfactual-workspaces": { en: ["Fork isolated candidates", "Run matched probes", "Compare controlled outcomes"], fr: ["Créer des candidats isolés", "Exécuter des sondes comparables", "Comparer les résultats contrôlés"] },

  trinity: { en: ["Fork three candidate worlds", "Collect terminal evidence", "Compare and retain"], fr: ["Créer trois mondes candidats", "Recueillir les preuves terminales", "Comparer et retenir"] },
  "a-team": { en: ["Decompose dependent tasks", "Assign specialists", "Integrate verified outputs"], fr: ["Décomposer les tâches dépendantes", "Affecter les spécialistes", "Intégrer les résultats vérifiés"] },
  biocenose: { en: ["Collect independent ballots", "Check quorum and evidence", "Aggregate qualified decision"], fr: ["Recueillir des votes indépendants", "Vérifier quorum et preuves", "Agréger la décision qualifiée"] },
  holobionte: { en: ["Identify host needs", "Admit bounded symbionts", "Review collective outcome"], fr: ["Identifier les besoins de l'hôte", "Admettre les symbiotes bornés", "Examiner le résultat collectif"] },
  syncytium: { en: ["Read shared version", "Propose concurrent updates", "Merge under invariants"], fr: ["Lire la version partagée", "Proposer des mises à jour concurrentes", "Fusionner sous invariants"] },
  rhizome: { en: ["Map capability graph", "Route through eligible edges", "Verify local trace"], fr: ["Cartographier le graphe de capacités", "Router par les liens admissibles", "Vérifier la trace locale"] },
  metapopulation: { en: ["Observe local demes", "Move typed propagules", "Test recolonization"], fr: ["Observer les populations locales", "Déplacer les propagules typés", "Tester la recolonisation"] },
  biome: { en: ["Measure niche demand", "Allocate limited resources", "Reassess ecological pressure"], fr: ["Mesurer la demande des niches", "Allouer les ressources limitées", "Réévaluer la pression écologique"] },

  mutation: { en: ["Propose variation", "Validate constraints", "Retain or reject candidate"], fr: ["Proposer une variation", "Valider les contraintes", "Conserver ou rejeter le candidat"] },
  "evolution-selection": { en: ["Create candidate variants", "Measure declared fitness", "Select under policy"], fr: ["Créer des variantes candidates", "Mesurer l'adaptation déclarée", "Sélectionner sous politique"] },
  plasmids: { en: ["Package transferable trait", "Check receiver compatibility", "Record horizontal transfer"], fr: ["Emballer un trait transférable", "Vérifier la compatibilité", "Tracer le transfert horizontal"] },
  "horizontal-transfer": { en: ["Identify donor and recipient", "Transfer bounded capability", "Verify recipient state"], fr: ["Identifier donneur et receveur", "Transférer la capacité bornée", "Vérifier l'état du receveur"] },
  "swarm-intelligence": { en: ["Apply local interaction rules", "Propagate neighbor signals", "Measure group behavior"], fr: ["Appliquer les règles locales", "Propager les signaux voisins", "Mesurer le comportement collectif"] },
  stigmergy: { en: ["Deposit environmental trace", "Read and decay traces", "Adapt local route"], fr: ["Déposer une trace environnementale", "Lire et dissiper les traces", "Adapter la route locale"] },
  niches: { en: ["Define task environment", "Match capability to niche", "Measure occupancy and fit"], fr: ["Définir l'environnement de tâche", "Associer capacité et niche", "Mesurer occupation et adéquation"] },
  populations: { en: ["Count group members", "Apply transition policy", "Observe population change"], fr: ["Compter les membres du groupe", "Appliquer la transition", "Observer le changement de population"] },
  cryptobiosis: { en: ["Detect hostile conditions", "Enter dormant state", "Resume after validated wake"], fr: ["Détecter les conditions hostiles", "Entrer en dormance", "Reprendre après réveil validé"] },
  "natural-creative-ecology": { en: ["Generate diverse variants", "Expose them to constraints", "Retain evidenced novelty"], fr: ["Générer des variantes diverses", "Les soumettre aux contraintes", "Retenir la nouveauté étayée"] },

  sensorium: { en: ["Collect permitted signals", "Normalize observations", "Route actionable perception"], fr: ["Recueillir les signaux permis", "Normaliser les observations", "Router la perception utile"] },
  metabolism: { en: ["Read available budget", "Allocate to active work", "Account for consumption"], fr: ["Lire le budget disponible", "Allouer au travail actif", "Comptabiliser la consommation"] },
  homeostasis: { en: ["Measure deviation", "Apply bounded correction", "Check restored range"], fr: ["Mesurer l'écart", "Appliquer la correction bornée", "Vérifier la plage restaurée"] },
  resilience: { en: ["Detect disturbance", "Reconfigure within limits", "Measure recovery"], fr: ["Détecter la perturbation", "Reconfigurer sous contraintes", "Mesurer le rétablissement"] },
  development: { en: ["Read lineage state", "Apply stage transition", "Validate new capability"], fr: ["Lire l'état de la lignée", "Appliquer la transition d'étape", "Valider la nouvelle capacité"] },
  symbionts: { en: ["Identify host need", "Attach specialist", "Measure mutual contribution"], fr: ["Identifier le besoin de l'hôte", "Associer le spécialiste", "Mesurer l'apport mutuel"] },
  "web-foraging": { en: ["Estimate source yield", "Search under cost budget", "Leave diminishing source"], fr: ["Estimer le rendement de la source", "Chercher sous budget de coût", "Quitter une source épuisée"] },
  foveation: { en: ["Sample broad scene", "Select high-value region", "Inspect focused detail"], fr: ["Échantillonner la scène globale", "Choisir la région utile", "Examiner le détail ciblé"] },
  "animal-senses": { en: ["Receive sensor modality", "Filter signal and noise", "Interpret for action"], fr: ["Recevoir la modalité sensorielle", "Filtrer signal et bruit", "Interpréter pour agir"] },
  "animal-control-primitives": { en: ["Observe local cue", "Apply simple response rule", "Check global consequence"], fr: ["Observer l'indice local", "Appliquer la règle de réponse", "Vérifier la conséquence globale"] },

  "lean-verification": { en: ["State proposition", "Submit proof term", "Check with Lean kernel"], fr: ["Énoncer la proposition", "Soumettre le terme de preuve", "Contrôler avec le noyau Lean"] },
  "proof-artifact": { en: ["Package proposition", "Attach proof and assumptions", "Verify checker result"], fr: ["Emballer la proposition", "Joindre preuve et hypothèses", "Vérifier le résultat du contrôleur"] },
  "deterministic-verification": { en: ["Freeze input and checker", "Run reproducible test", "Report bounded result"], fr: ["Figer entrée et contrôleur", "Exécuter le test reproductible", "Rapporter le résultat borné"] },
  "mathematical-organism": { en: ["Define state and controls", "Apply transition function", "Compare observables"], fr: ["Définir état et contrôles", "Appliquer la transition", "Comparer les observations"] },
  "verification-registry": { en: ["Register versioned contract", "Select matching verifier", "Preserve result artifact"], fr: ["Enregistrer le contrat versionné", "Choisir le vérificateur", "Conserver l'artefact résultat"] },
  "smt-solver": { en: ["Encode constraints", "Solve SAT or UNSAT", "Check model or certificate"], fr: ["Encoder les contraintes", "Résoudre SAT ou UNSAT", "Contrôler modèle ou certificat"] },
  "deterministic-procedures": { en: ["Fix input and version", "Execute procedure", "Compare repeat outputs"], fr: ["Figer entrée et version", "Exécuter la procédure", "Comparer les sorties répétées"] },

  snapshots: { en: ["Capture selected state", "Check dependency integrity", "Restore declared scope"], fr: ["Capturer l'état sélectionné", "Contrôler les dépendances", "Restaurer la portée déclarée"] },
  vfs: { en: ["Resolve virtual path", "Apply access boundary", "Read or write backing store"], fr: ["Résoudre le chemin virtuel", "Appliquer la frontière d'accès", "Lire ou écrire le stockage"] },
  sqlite: { en: ["Parse SQL operation", "Execute transaction", "Commit durable result"], fr: ["Analyser l'opération SQL", "Exécuter la transaction", "Valider le résultat durable"] },
  persistence: { en: ["Serialize state", "Commit durable version", "Reload and migrate"], fr: ["Sérialiser l'état", "Valider la version durable", "Recharger et migrer"] },
  "shared-state": { en: ["Read versioned value", "Propose concurrent change", "Merge or reject conflict"], fr: ["Lire la valeur versionnée", "Proposer un changement concurrent", "Fusionner ou refuser le conflit"] },
  "model-routing": { en: ["Read task requirements", "Filter eligible providers", "Select within budget"], fr: ["Lire les besoins de la tâche", "Filtrer les fournisseurs admissibles", "Choisir sous budget"] },
  mcp: { en: ["Describe typed tool", "Validate client request", "Return bounded response"], fr: ["Décrire l'outil typé", "Valider la requête cliente", "Renvoyer la réponse bornée"] },
  sandbox: { en: ["Declare allowed effects", "Intercept requested action", "Permit or deny execution"], fr: ["Déclarer les effets permis", "Intercepter l'action demandée", "Autoriser ou refuser l'exécution"] },
  observability: { en: ["Emit attributed event", "Correlate trace and metric", "Investigate missing evidence"], fr: ["Émettre l'événement attribué", "Corréler trace et mesure", "Examiner la preuve manquante"] },
  "identity-authority": { en: ["Identify actor", "Evaluate scope and policy", "Record authorization decision"], fr: ["Identifier l'acteur", "Évaluer portée et politique", "Tracer la décision d'autorisation"] },
  governance: { en: ["Define decision rule", "Collect required approvals", "Audit execution receipt"], fr: ["Définir la règle de décision", "Réunir les approbations", "Auditer le reçu d'exécution"] },
  workflows: { en: ["Declare task graph", "Fire guarded transitions", "Recover or complete"], fr: ["Déclarer le graphe de tâches", "Déclencher les transitions gardées", "Récupérer ou terminer"] },
};
