/** French display names for every concept route. Product identifiers stay unchanged. */
export const frenchConceptTitles: Record<string, string> = {
  "genos-philosophy": "Philosophie GenOS",
  maladies: "Maladies logicielles",
  memoire: "Mémoire",
  ontogenese: "Ontogenèse",
  ontologie: "Ontologie",
  genome: "Génome",
  epigenetics: "Épigénétique",
  "agent-dna": "AgentDNA",
  phenotype: "Phénotype",
  instinct: "Instinct",
  reproduction: "Reproduction",
  "speciation-graft": "Spéciation et greffe",
  agow: "AGOW",
  gvx: "GVX",
  "self-model": "Auto-modèle",
  "theory-of-self": "Théorie du soi",
  "predictive-system": "Système prédictif",
  "natural-search-control-plane": "Plan de contrôle de la recherche naturelle",
  attention: "Attention et saillance",
  "consciousness-taxonomy": "Taxonomie de l'esprit et de la conscience",
  "functional-indicators": "Indicateurs fonctionnels",
  epistemics: "Épistémologie",
  beliefs: "Croyances",
  claims: "Affirmations",
  evidence: "Preuves",
  contradictions: "Contradictions",
  provenance: "Provenance",
  "brier-calibration": "Calibration de Brier",
  gettier: "Problèmes de Gettier",
  knowledge: "Connaissances",
  "episodic-memory": "Mémoire épisodique",
  "semantic-memory": "Mémoire sémantique",
  "vector-memory": "Mémoire vectorielle",
  "procedural-memory": "Mémoire procédurale",
  "synaptic-plasticity": "Plasticité synaptique",
  stdp: "STDP",
  "memory-fossilization": "Fossilisation de la mémoire",
  "memory-retrieval": "Récupération de la mémoire",
  cortex: "Cortex",
  morphogenesis: "Morphogenèse",
  "epistemic-meristem": "Méristème épistémique",
  "unblocking-spiral": "Spirale de déblocage",
  "counterexample-cambium": "Cambium des contre-exemples",
  chronotaxis: "Chronotaxie apériodique",
  "risk-ledger": "Risque statistique sous contrat",
  "dynamic-organizations": "Organisations dynamiques",
  "worker-kinds": "Types de workers",
  "resident-daemons": "Daemons résidents",
  "agent-relationships": "Relations entre agents",
  "relational-physiology": "Physiologie relationnelle",
  "communication-ecology": "Écologie de la communication",
  "signal-plane": "Plan de signalisation sans texte",
  "g-cir": "G-CIR",
  "mission-continuity": "Continuité de mission",
  "agent-git": "AgentGit",
  "counterfactual-workspaces": "Espaces de travail contrefactuels",
  trinity: "Trinity",
  "a-team": "A-Team",
  biocenose: "Biocénose",
  holobionte: "Holobionte",
  syncytium: "Syncytium",
  rhizome: "Rhizome",
  metapopulation: "Métapopulation",
  biome: "Biome",
  mutation: "Mutation",
  "evolution-selection": "Sélection",
  plasmids: "Plasmides",
  "horizontal-transfer": "Transfert horizontal",
  "swarm-intelligence": "Intelligence en essaim",
  stigmergy: "Stigmergie",
  niches: "Niches",
  populations: "Populations",
  cryptobiosis: "Cryptobiose et dormance",
  "natural-creative-ecology": "Écologie créative naturelle",
  sensorium: "Sensorium",
  metabolism: "Métabolisme",
  homeostasis: "Homéostasie et allostasie",
  resilience: "Résilience et reprise",
  development: "Développement",
  symbionts: "Symbiontes",
  "web-foraging": "Exploration web par recherche de ressources",
  foveation: "Fovéation",
  "animal-senses": "Sens animaux",
  "animal-control-primitives": "Primitives de contrôle animal",
  "adaptive-epistemic-immunity": "Immunité épistémique adaptative",
  "immune-system": "Système immunitaire",
  nosology: "Nosologie",
  pathologies: "Pathologies computationnelles",
  autoimmune: "Défaillance auto-immune",
  degenerative: "Défaillance dégénérative",
  infectious: "Défaillance infectieuse",
  "genetic-pathology": "Défaillance génétique",
  cancerous: "Défaillance de type cancéreux",
  "metabolic-pathology": "Défaillance métabolique",
  cardiovascular: "Défaillance cardiovasculaire",
  psychiatric: "Défaillance psychiatrique",
  "environmental-pathology": "Défaillance environnementale",
  "lean-verification": "Vérification Lean",
  "proof-artifact": "Artefact de preuve",
  "deterministic-verification": "Vérification déterministe",
  "mathematical-organism": "Organisme mathématique",
  "verification-registry": "Registre de vérification",
  "smt-solver": "Couche de solveur SMT",
  "deterministic-procedures": "Procédures déterministes",
  snapshots: "Instantanés",
  vfs: "Système de fichiers virtuel",
  sqlite: "Persistance SQLite",
  persistence: "Persistance",
  "shared-state": "État partagé",
  "model-routing": "Routage des modèles",
  mcp: "Interfaces MCP",
  sandbox: "Bac à sable",
  observability: "Observabilité",
  "identity-authority": "Identité et autorité",
  governance: "Gouvernance",
  workflows: "Workflows et tâches",
};

export const frenchConceptFamilyNames: Record<string, string> = {
  "identity-development": "Identité et développement",
  "cognition-control": "Cognition et contrôle",
  "knowledge-evidence": "Connaissances et preuves",
  "memory-learning": "Mémoire et apprentissage",
  "collective-intelligence": "Intelligence collective",
  orchestration: "Orchestration",
  "evolution-ecology": "Évolution et écologie",
  "physiology-perception": "Physiologie et perception",
  "immunity-medicine": "Immunité et médecine",
  "formal-verification": "Vérification formelle",
  "runtime-infrastructure": "Runtime et infrastructure",
};
