import Link from "next/link";
import { Eyebrow } from "./eyebrow";
import { OrganizationExplorer } from "./organization-explorer";
import styles from "./organization-explorer.module.css";

export function OrganizationsView({ language = "en" }: { language?: "en" | "fr" }) {
  const fr = language === "fr", t = (en: string, french: string) => fr ? french : en;
  return <div className={`page-shell organizations-page ${styles.view}`} lang={language}>
    <section className="page-hero section-wrap organization-hero"><Eyebrow>{t("ORCHESTRATION · 19 DYNAMIC ORGANIZATIONS", "ORCHESTRATION · 19 ORGANISATIONS DYNAMIQUES")}</Eyebrow><h1>{t("Algorithms shape", "Les algorithmes guident")}<br />{t("how a team ", "l’adaptation ")}<em>{t("adapts.", "du collectif.")}</em></h1><p>{t("A dynamic organization guides one step of collective work: how agents compare evidence, explore, find a route, allocate resources or prepare recovery. Explore all 19 algorithms, change their inputs and inspect their calculated results.", "Une organisation dynamique guide un pas de travail collectif : comparer des preuves, explorer, trouver une route, répartir des ressources ou préparer une reprise. Explorez les 19 algorithmes, modifiez leurs entrées et inspectez leurs résultats calculés.")}</p><div className="organization-statline"><span><strong>19</strong> {t("executable guidance steps", "pas de guidage exécutables")}</span><i /><span><strong>4</strong> {t("swarm algorithms", "algorithmes d’essaim")}</span><i /><span><strong>8</strong> {t("separate topologies", "topologies distinctes")}</span></div></section>
    <div className="section-wrap"><section className={styles.intro} aria-label={t("Topologies and organizations", "Topologies et organisations")}><article><small>{t("STRUCTURE · TOPOLOGY", "STRUCTURE · TOPOLOGIE")}</small><h2>{t("How the team is arranged.", "Comment le collectif est structuré.")}</h2><p>{t("Trinity, A-Team, Biocénose, Holobionte, Syncytium, Rhizome, Métapopulation and Biome define broader coordination patterns and service contracts.", "Trinity, A-Team, Biocénose, Holobionte, Syncytium, Rhizome, Métapopulation et Biome définissent des structures de coordination et des contrats de services.")}</p><Link href={fr ? "/fr/topologies" : "/en/topologies"}>{t("Explore the eight topologies", "Explorer les huit topologies")} →</Link></article><article><small>{t("DECISION RULE · ORGANIZATION", "RÈGLE DE DÉCISION · ORGANISATION")}</small><h2>{t("What one algorithm returns.", "Ce que retourne un algorithme.")}</h2><p>{t("The organization consumes a supplied state and options to return guidance: votes, steering vectors, ranks, routes, allocations or facts. This laboratory executes those deterministic calculations in your browser, with no model calls.", "L’organisation consomme un état et des options pour retourner un guidage : votes, vecteurs, rangs, routes, allocations ou faits. Ce laboratoire exécute ces calculs déterministes dans votre navigateur, sans appel de modèle.")}</p></article></section><OrganizationExplorer language={language} /></div>
  </div>;
}
