export type Organization = {
  id: string;
  name: string;
  family: string;
  summary: string;
  algorithm: string;
  mechanism: string;
  status: "PARTIAL" | "EXPERIMENTAL";
  visual: "hub" | "blind" | "redblue" | "brier" | "quorum" | "trails" | "boids" | "fish" | "slime" | "wolves" | "mycelium" | "roles" | "energy" | "silence" | "arena" | "hierarchy" | "recovery" | "memory";
};

export const organizations: Organization[] = [
  { id: "specialist_expert_committee", name: "Specialist expert committee", family: "Collective judgment", summary: "A coordinating hub gathers independent reports from specialist spokes and synthesizes them.", algorithm: "Role-based fan-out → independent reports → synthesis", mechanism: "Hub-and-spoke routing; each specialist contributes a distinct view.", status: "PARTIAL", visual: "hub" },
  { id: "blind_adversarial_review", name: "Blind adversarial review", family: "Collective judgment", summary: "Anonymous critics examine work in isolated pairs to reduce attribution bias.", algorithm: "Pair critics → hide identities → compare challenges", mechanism: "Critics are paired and their review is marked anonymous.", status: "PARTIAL", visual: "blind" },
  { id: "red_blue_coevolution", name: "Red / Blue coevolution", family: "Collective judgment", summary: "Attackers probe assumptions while defenders identify protections; an observer can assess both sides.", algorithm: "Red probes ↔ Blue defends → neutral observation", mechanism: "Agents are assigned to adversarial red and blue groups.", status: "EXPERIMENTAL", visual: "redblue" },
  { id: "brier_weighted_consensus", name: "Brier-weighted consensus", family: "Collective judgment", summary: "Historical calibration weights confidence against resolved outcomes before aggregating support.", algorithm: "Resolved outcome → Brier score → weighted support", mechanism: "Brier loss is computed only when an external resolved outcome exists.", status: "PARTIAL", visual: "brier" },
  { id: "quorum_with_abstention", name: "Quorum with abstention", family: "Collective judgment", summary: "A decision passes only when active, non-abstaining votes meet the configured support threshold.", algorithm: "Count active votes → calculate support → test quorum", mechanism: "Abstentions are counted separately and excluded from the active support denominator.", status: "PARTIAL", visual: "quorum" },
  { id: "stigmergy", name: "Stigmergy", family: "Collective coordination", summary: "Agents coordinate indirectly by leaving traces in a shared environment.", algorithm: "Deposit trace → select strongest trail → decay", mechanism: "The dominant route comes from shared trail intensity or the strongest supplied trace.", status: "PARTIAL", visual: "trails" },
  { id: "flocking_boids", name: "Flocking / Boids", family: "Swarm search", summary: "Local movement balances cohesion toward the group, alignment with neighbors and separation at close range.", algorithm: "Cohesion + alignment + separation → steering vectors", mechanism: "Each agent receives a heading adjustment and a movement vector.", status: "EXPERIMENTAL", visual: "boids" },
  { id: "fish_school_search", name: "Fish School Search", family: "Swarm search", summary: "Agents shift toward a fitness-weighted barycenter, combining individual exploration with collective movement.", algorithm: "Fitness-weighted barycenter → volitive movement", mechanism: "The center is weighted by fitness; each individual gets a vector toward it.", status: "EXPERIMENTAL", visual: "fish" },
  { id: "slime_mould_network", name: "Slime-mould network", family: "Swarm search", summary: "Flow reinforces useful paths while decay weakens them; low-conductivity edges can be pruned.", algorithm: "Flow reinforcement + decay → conductivity pruning", mechanism: "Conductivity determines which edges remain available for preferred routing.", status: "EXPERIMENTAL", visual: "slime" },
  { id: "grey_wolf_optimizer", name: "Grey Wolf Optimizer", family: "Swarm search", summary: "The strongest candidates become alpha, beta and delta leaders; other candidates update toward the pack.", algorithm: "Rank fitness → assign leaders → update positions", mechanism: "Top three candidates guide bounded movement of the remaining pack.", status: "EXPERIMENTAL", visual: "wolves" },
  { id: "mycelial_routing", name: "Mycelial routing", family: "Adaptive routing", summary: "A mission need is routed to a member whose declared capabilities match it.", algorithm: "Read capability need → find matching member → route", mechanism: "The first matching capability is selected; an absent need or match yields no route.", status: "PARTIAL", visual: "mycelium" },
  { id: "dynamic_polyethism", name: "Dynamic polyethism", family: "Adaptive routing", summary: "Members are ordered by fitness to expose a changing gradient of roles and likely assignments.", algorithm: "Rank member fitness → produce role gradient", mechanism: "A deterministic fitness sort ranks agents for the current step.", status: "PARTIAL", visual: "roles" },
  { id: "energy_huddle", name: "Energy huddle", family: "Adaptive routing", summary: "A shared budget is divided across groups according to their relative weights.", algorithm: "Normalize weights → allocate proportional budget", mechanism: "Non-negative weights share the available budget; equal weights are used by default.", status: "PARTIAL", visual: "energy" },
  { id: "network_silence", name: "Network silence", family: "Resilience & memory", summary: "Agents hold non-critical communication in a local buffer and keep the group silent for the step.", algorithm: "Buffer messages → flush on critical event or success", mechanism: "The organization step marks the network silent and reports the buffered member count.", status: "PARTIAL", visual: "silence" },
  { id: "strategy_arena", name: "Strategy arena", family: "Resilience & memory", summary: "Candidate strategies compete in an isolated tournament before one can be selected.", algorithm: "Isolate competitors → evaluate → compare", mechanism: "The step returns the competitors and an isolated-tournament mode.", status: "PARTIAL", visual: "arena" },
  { id: "hierarchical_merge", name: "Hierarchical merge", family: "Resilience & memory", summary: "A root gathers child contributions into a hierarchy for a later synthesis step.", algorithm: "Choose root → group children → merge", mechanism: "The first member is root; remaining members become children.", status: "PARTIAL", visual: "hierarchy" },
  { id: "competitive_arena", name: "Competitive arena", family: "Resilience & memory", summary: "Candidates work in isolation so their outputs can be compared without shared-state influence.", algorithm: "Seal candidate runs → compare independent outcomes", mechanism: "Uses the isolated tournament guidance step shared with strategy arena.", status: "PARTIAL", visual: "arena" },
  { id: "isolated_recovery", name: "Isolated recovery", family: "Resilience & memory", summary: "Affected members are isolated while lost roles are listed for a controlled recovery plan.", algorithm: "Isolate affected agents → identify lost roles → plan", mechanism: "The step returns the isolated members and supplied lost-role plan.", status: "PARTIAL", visual: "recovery" },
  { id: "memory_compilation", name: "Memory compilation", family: "Resilience & memory", summary: "Relevant facts are gathered into a compact memory with source references for later work.", algorithm: "Collect facts → compile memory → retain source refs", mechanism: "The organization step carries forward the supplied facts for compilation.", status: "PARTIAL", visual: "memory" },
];

export const organizationFamilies = [...new Set(organizations.map((item) => item.family))];
