/** Published source revision used to verify the organization guidance algorithms. */
export const genosSourceCommit = "7ed77a88ab5183ee355bf65f9106bc6d1e1c078c";
export const genosReviewedAt = "2026-10-06";
export const genosSource = (path: string) =>
  `https://github.com/PISSARAW/GenOS/blob/${genosSourceCommit}/${path}`;

export type ProductStatus = "implemented" | "partial" | "experimental" | "planned";
export type EvidenceLevel = "unit" | "integration" | "end-to-end" | "benchmark" | "reported-run";
export type ProductClaim = {
  id: string;
  name: string;
  status: ProductStatus;
  label: string;
  implementedSlice: string;
  missingWork: string;
  evidenceLevel: EvidenceLevel;
  sourcePath: string;
};

/** A registered capability is not automatically invoked by an orchestrated mission. */
export const productClaims: ProductClaim[] = [
  { id: "agent-git", name: "Versioned workspace state", status: "partial", label: "BOUNDED WORKFLOWS", implementedSlice: "Snapshot, fork, diff and replay operations are available for supported state.", missingWork: "Coverage and recovery vary by path; external effects and processes are not automatically restored.", evidenceLevel: "integration", sourcePath: "docs/03-reference/contrat-produit-et-completude.md" },
  { id: "topologies", name: "Eight topology modes", status: "partial", label: "MIXED MATURITY", implementedSlice: "Eight modes have composition and coordination services.", missingWork: "Each mode has distinct integration and end-to-end gaps; registration does not establish feature parity.", evidenceLevel: "integration", sourcePath: "docs/03-reference/contrat-produit-et-completude.md" },
  { id: "trinity", name: "Trinity variants", status: "partial", label: "12 RUNNERS WIRED", implementedSlice: "Twelve runners are connected with variant-specific completion gates.", missingWork: "The pre-correction R3 campaign ended 12/12 ESCALATE and 0 merge; no corrected-path E2E qualification is published.", evidenceLevel: "reported-run", sourcePath: "docs/02-orchestration/topologies/trinity.md" },
  { id: "a-team", name: "A-Team specialist assignment", status: "partial", label: "STRUCTURED INPUTS", implementedSlice: "Validated WorkGraphs and explicit requirements can drive specialist assignment and handoffs.", missingWork: "Text-only analysis remains lexical; semantic decomposition and a complete mission E2E are open.", evidenceLevel: "unit", sourcePath: "docs/03-reference/contrat-produit-et-completude.md" },
  { id: "biocenose", name: "Biocenosis live missions", status: "partial", label: "0 VERIFIED PROMOTIONS", implementedSlice: "A 12-mission SQLite campaign retained 766 telemetry and 549 community events with no reported persistence loss.", missingWork: "Nine cycles blocked; three cycles completed but no mission fulfilled all criteria or received verified promotion. Independent provider domains were not measured.", evidenceLevel: "reported-run", sourcePath: "docs/06-qualite-preuves/missions-live-biocenose-sqlite-2026-10-04.md" },
  { id: "syncytium", name: "Syncytium shared state", status: "partial", label: "LOCAL OPERATIONS", implementedSlice: "Persisted shared sessions and supported CRDT operations are callable.", missingWork: "Concurrent multi-writer convergence and full mission integration remain unqualified.", evidenceLevel: "unit", sourcePath: "docs/03-reference/contrat-produit-et-completude.md" },
  { id: "rhizome", name: "Rhizome graph routing", status: "experimental", label: "BOUNDED ROUTING", implementedSlice: "A topology session plans bounded routes over a persisted capability graph.", missingWork: "Provider execution, autonomous mission routing and E2E growth are not demonstrated.", evidenceLevel: "unit", sourcePath: "docs/03-reference/contrat-produit-et-completude.md" },
  { id: "holobionte", name: "Holobiont lifecycle", status: "experimental", label: "BOUNDED RUNTIME", implementedSlice: "Host and symbiont lifecycle primitives exist.", missingWork: "Host veto and full mission behavior require product validation.", evidenceLevel: "unit", sourcePath: "docs/03-reference/contrat-produit-et-completude.md" },
  { id: "biome", name: "Biome resource cycles", status: "experimental", label: "BOUNDED OPERATIONS", implementedSlice: "Resource allocation and observation services can run controlled cycles.", missingWork: "Autonomous ecology, provider calls and outcome E2E remain open.", evidenceLevel: "unit", sourcePath: "docs/03-reference/contrat-produit-et-completude.md" },
  { id: "metapopulation", name: "Metapopulation recovery", status: "experimental", label: "ADAPTER DEPENDENT", implementedSlice: "Regional and migration controls have bounded operations.", missingWork: "Regeneration and recovery require integration evidence and supplied adapters.", evidenceLevel: "unit", sourcePath: "docs/03-reference/contrat-produit-et-completude.md" },
  { id: "organizations", name: "Nineteen dynamic organizations", status: "partial", label: "REGISTRY AND RUNSTEP", implementedSlice: "The registry and deterministic runStep policies exist.", missingWork: "Selection, dispatch and improved mission outcomes are not established by registry presence.", evidenceLevel: "unit", sourcePath: "docs/03-reference/contrat-produit-et-completude.md" },
  { id: "morphogenesis", name: "Morphogenesis topology plugins", status: "partial", label: "EXPLICIT GATES", implementedSlice: "Registered plugins can execute a validated graph on the explicit opt-in path.", missingWork: "Execution receipts are unverified traces; graph completion does not prove a mission outcome or apply a transition.", evidenceLevel: "integration", sourcePath: "docs/03-reference/plugins-topologies-morphogenese.md" },
  { id: "workers", name: "Measured worker methods", status: "partial", label: "NARROW SUITE", implementedSlice: "The 20-case local suite passes ten cases without Lean and one additional case with Lean.", missingWork: "Nine cases remain unmeasured; broad external benchmark parity is unproven.", evidenceLevel: "benchmark", sourcePath: "benchmarks/workers/README.md" },
  { id: "mcp", name: "MCP interfaces", status: "partial", label: "TOOL BY TOOL", implementedSlice: "JS stdio and backend dispatch enforce leases and direct calls.", missingWork: "Rust parity and individual tool nominal/refusal coverage vary by tool.", evidenceLevel: "integration", sourcePath: "docs/03-reference/contrat-produit-et-completude.md" },
  { id: "web-perception", name: "Continuous web perception", status: "experimental", label: "PRIMITIVES", implementedSlice: "Web observation and foveation handlers exist.", missingWork: "A complete observation–action–verification mission loop is not published.", evidenceLevel: "unit", sourcePath: "docs/03-reference/contrat-produit-et-completude.md" },
  { id: "g-cir", name: "G-CIR obligation compilation", status: "partial", label: "TWO ADAPTERS", implementedSlice: "Two adapters and a versioned local obligation registry are documented.", missingWork: "General compilation of arbitrary free-form missions is not established.", evidenceLevel: "integration", sourcePath: "docs/02-orchestration/g-cir.md" },
  { id: "relational-physiology", name: "Relational physiology", status: "partial", label: "TARGETED ROUTING", implementedSlice: "A kernel and targeted routing are integrated.", missingWork: "General mission integration is pending; relation constraints cannot grant new authority.", evidenceLevel: "integration", sourcePath: "docs/02-orchestration/physiologie-relationnelle.md" },
  { id: "signal-plane", name: "Signal Plane delivery", status: "partial", label: "DURABLE PULL", implementedSlice: "Persisted deliveries, an inbox and ACK states, cognitive escalation and leased handler retries are connected.", missingWork: "Receiver registration is not wired at server startup; delivery is at least once and external actions require idempotency.", evidenceLevel: "integration", sourcePath: "docs/01-concepts/signal-plane-zero-text.md" },
  { id: "mission-continuity", name: "Mission continuity", status: "partial", label: "PERSISTED STATE", implementedSlice: "Completion, feedback, dormancy and regeneration have connected paths, including a two-process SQLite WAL authority test.", missingWork: "A multi-instance deployment has not been qualified.", evidenceLevel: "integration", sourcePath: "docs/02-orchestration/continuite-mission-organisme.md" },
  { id: "epistemic-meristem", name: "Epistemic meristem", status: "partial", label: "REVALIDATION", implementedSlice: "Read revalidation and Rhizome planning are connected.", missingWork: "Autonomous recruitment, Trinity adaptation and empirical calibration are open.", evidenceLevel: "integration", sourcePath: "docs/02-orchestration/meristeme-epistemique.md" },
  { id: "unblock-spiral", name: "Unblocking spiral", status: "partial", label: "PERSISTED PROGRESSION", implementedSlice: "Signed attempts, duplicate refusal and bounded persistent morphology search are connected.", missingWork: "Automatic control of a full mission and comparative outcome evidence are open.", evidenceLevel: "integration", sourcePath: "docs/02-orchestration/spirale-de-deblocage.md" },
  { id: "cambium", name: "Counterexample cambium", status: "partial", label: "REGISTRY AND GATE", implementedSlice: "A registry, gate and conditional Holobiont recall exist.", missingWork: "General automated replay into memory is pending.", evidenceLevel: "integration", sourcePath: "docs/02-orchestration/cambium-contre-exemples.md" },
  { id: "chronotaxis", name: "Aperiodic chronotaxis", status: "partial", label: "PERSISTED SCHEDULES", implementedSlice: "Schedules, observation receipts and missed windows can be persisted.", missingWork: "Resident probes and field qualification are pending.", evidenceLevel: "integration", sourcePath: "docs/02-orchestration/chronotaxie-aperiodique.md" },
  { id: "contracted-infinity", name: "Contracted infinity", status: "partial", label: "OPT-IN GATES", implementedSlice: "A transactional risk ledger and opt-in Trinity/Biocenosis gates exist.", missingWork: "Data provenance and empirical campaign evidence are pending.", evidenceLevel: "integration", sourcePath: "docs/02-orchestration/infini-sous-contrat.md" },
  { id: "creative-ecology", name: "Natural creative ecology", status: "partial", label: "CONTROLLED INTEGRATION", implementedSlice: "The curiosity bridge, persisted phenotype and topology filtering run in controlled tests.", missingWork: "POET agent startup remains simulated in its test; autonomous user-task campaigns, statistical comparisons and generalization are not established.", evidenceLevel: "integration", sourcePath: "docs/01-concepts/natural-creative-ecology.md" },
];

export const topologyClaim = (slug: string) => productClaims.find((claim) => claim.id === slug);
