/** Published origin/v3 revision; previously reported local probes are scoped separately. */
export const genosSourceCommit = "a6b273aaf5ea6a570a9a7b850fef53e84e408ca5";
export const genosReviewedAt = "2026-10-06";
export const genosSource = (path: string) =>
  `https://github.com/PISSARAW/GenOS/blob/${genosSourceCommit}/${path}`;

export type ProductStatus = "implemented" | "partial" | "experimental" | "planned";
export type EvidenceLevel = "unit" | "integration" | "end-to-end" | "benchmark" | "reported-run";
export type ProductClaim = {
  id: string;
  name: string;
  status: ProductStatus;
  label: string;
  implementedSlice: string;
  missingWork: string;
  evidenceLevel: EvidenceLevel;
  sourcePath: string;
};

/** A registered capability is not automatically invoked by an orchestrated mission. */
export const productClaims: ProductClaim[] = [
  { id: "agent-git", name: "Versioned workspace state", status: "partial", label: "BOUNDED WORKFLOWS", implementedSlice: "Snapshot, fork, diff and replay operations are available for supported state.", missingWork: "Coverage and recovery vary by path; external effects and processes are not automatically restored.", evidenceLevel: "integration", sourcePath: "docs/03-reference/contrat-produit-et-completude.md" },
  { id: "topologies", name: "Eight topology modes", status: "partial", label: "MIXED MATURITY", implementedSlice: "Eight modes have composition and coordination services.", missingWork: "Each mode has distinct integration and end-to-end gaps; registration does not establish feature parity.", evidenceLevel: "integration", sourcePath: "docs/03-reference/contrat-produit-et-completude.md" },
  { id: "trinity", name: "Trinity variants", status: "partial", label: "12 RUNNERS WIRED", implementedSlice: "Twelve runners share comparison, isolated execution, bounded research and persisted resume guards with targeted runtime tests.", missingWork: "The pre-correction R3 campaign ended 12/12 ESCALATE and 0 merge; no corrected-path real-mission campaign is published.", evidenceLevel: "integration", sourcePath: "docs/02-orchestration/topologies/trinity.md" },
  { id: "a-team", name: "A-Team specialist assignment", status: "partial", label: "PROOF-GATED EXECUTION", implementedSlice: "Structured work graphs, independent scheduling and versioned handoffs connect to proof-gated completion with SQLite/subprocess E2E tests.", missingWork: "Text-only formation remains lexical; general expertise and generic multi-team sub-runs remain partial.", evidenceLevel: "integration", sourcePath: "docs/02-orchestration/topologies/a-team.md" },
  { id: "biocenose", name: "Biocenosis live missions", status: "partial", label: "PERSISTENT PROOF GATES", implementedSlice: "Twelve executable variants share persistent deliberation, transactional round receipts, resume and proof-gated finalization.", missingWork: "Models, independent oracles and action adapters remain explicit dependencies. Runtime tests do not establish causal superiority; the dated October 4 campaign reported no verified promotion.", evidenceLevel: "integration", sourcePath: "docs/02-orchestration/topologies/biocenose.md" },
  { id: "syncytium", name: "Syncytium shared state", status: "partial", label: "CAUSAL STATE GATES", implementedSlice: "Causal replay, retry fingerprints, persistence rollback and committed-state validation are connected.", missingWork: "Local tests do not establish universal convergence, distributed consensus or general worker correctness.", evidenceLevel: "integration", sourcePath: "docs/adr/0331-syncytium-rejeu-causal-et-preuve-de-completion.md" },
  { id: "rhizome", name: "Rhizome graph routing", status: "experimental", label: "BOUNDED ROUTING", implementedSlice: "A topology session plans bounded routes over a persisted capability graph.", missingWork: "Provider execution, autonomous mission routing and E2E growth are not demonstrated.", evidenceLevel: "unit", sourcePath: "docs/03-reference/contrat-produit-et-completude.md" },
  { id: "holobionte", name: "Holobiont lifecycle", status: "experimental", label: "BOUNDED RUNTIME", implementedSlice: "Host and symbiont lifecycle primitives exist.", missingWork: "Host veto and full mission behavior require product validation.", evidenceLevel: "unit", sourcePath: "docs/03-reference/contrat-produit-et-completude.md" },
  { id: "biome", name: "Biome resource cycles", status: "partial", label: "PERSISTED CYCLES", implementedSlice: "Eleven variants share bounded transactional cycles, authorized adapters, measured consumption and independent verification, with SQLite restart tests.", missingWork: "A global goal requires its own verifier; comparative ecological benefit and real provider quality remain unqualified.", evidenceLevel: "integration", sourcePath: "docs/03-reference/runtime-biome.md" },
  { id: "metapopulation", name: "Metapopulation recovery", status: "experimental", label: "ADAPTER DEPENDENT", implementedSlice: "Regional and migration controls have bounded operations.", missingWork: "Regeneration and recovery require integration evidence and supplied adapters.", evidenceLevel: "unit", sourcePath: "docs/03-reference/contrat-produit-et-completude.md" },
  { id: "organizations", name: "Nineteen dynamic organizations", status: "partial", label: "REGISTRY AND RUNSTEP", implementedSlice: "The registry and deterministic runStep policies exist.", missingWork: "Selection, dispatch and improved mission outcomes are not established by registry presence.", evidenceLevel: "unit", sourcePath: "docs/03-reference/contrat-produit-et-completude.md" },
  { id: "morphogenesis", name: "Morphogenesis topology plugins", status: "partial", label: "EXPLICIT GATES", implementedSlice: "Registered plugins can execute a validated graph on the explicit opt-in path.", missingWork: "Execution receipts are unverified traces; graph completion does not prove a mission outcome or apply a transition.", evidenceLevel: "integration", sourcePath: "docs/03-reference/plugins-topologies-morphogenese.md" },
  { id: "workers", name: "Measured worker methods", status: "partial", label: "NARROW SUITE", implementedSlice: "The 20-case local suite passes ten cases without Lean and one additional case with Lean.", missingWork: "Nine cases remain unmeasured; broad external benchmark parity is unproven.", evidenceLevel: "benchmark", sourcePath: "benchmarks/workers/README.md" },
  { id: "mcp", name: "MCP interfaces", status: "partial", label: "TOOL BY TOOL", implementedSlice: "JS stdio and backend dispatch enforce leases and direct calls.", missingWork: "Rust parity and individual tool nominal/refusal coverage vary by tool.", evidenceLevel: "integration", sourcePath: "docs/03-reference/contrat-produit-et-completude.md" },
  { id: "web-perception", name: "Continuous web perception", status: "experimental", label: "PRIMITIVES", implementedSlice: "Web observation and foveation handlers exist.", missingWork: "A complete observation–action–verification mission loop is not published.", evidenceLevel: "unit", sourcePath: "docs/03-reference/contrat-produit-et-completude.md" },
  { id: "g-cir", name: "G-CIR obligation compilation", status: "partial", label: "OMEGA GATEWAY", implementedSlice: "The Node Omega gateway executes six guarded operations with persisted session visibility, MMU resolution and verification receipts.", missingWork: "General free-form mission compilation, complete Rust production bindings and empirical PGO qualification remain open.", evidenceLevel: "integration", sourcePath: "docs/02-orchestration/g-cir.md" },
  { id: "relational-physiology", name: "Relational physiology", status: "partial", label: "TARGETED ROUTING", implementedSlice: "A kernel and targeted routing are integrated.", missingWork: "General mission integration is pending; relation constraints cannot grant new authority.", evidenceLevel: "integration", sourcePath: "docs/02-orchestration/physiologie-relationnelle.md" },
  { id: "signal-plane", name: "Signal Plane delivery", status: "partial", label: "DURABLE PULL", implementedSlice: "Persisted deliveries, an inbox and ACK states, cognitive escalation and leased handler retries are connected.", missingWork: "Receiver registration is not wired at server startup; delivery is at least once and external actions require idempotency.", evidenceLevel: "integration", sourcePath: "docs/01-concepts/signal-plane-zero-text.md" },
  { id: "mission-continuity", name: "Mission continuity", status: "partial", label: "PERSISTED STATE", implementedSlice: "Completion, feedback, dormancy and regeneration have connected paths, including a two-process SQLite WAL authority test.", missingWork: "A multi-instance deployment has not been qualified.", evidenceLevel: "integration", sourcePath: "docs/02-orchestration/continuite-mission-organisme.md" },
  { id: "epistemic-meristem", name: "Epistemic meristem", status: "partial", label: "VERIFIED WAVES", implementedSlice: "Transactional experiment waves connect verified coverage, Trinity hypotheses and Biome niches under explicit contracts.", missingWork: "Host adapters must ensure real isolation and verification; empirical advantage is not qualified.", evidenceLevel: "integration", sourcePath: "docs/02-orchestration/meristeme-epistemique.md" },
  { id: "unblock-spiral", name: "Unblocking spiral", status: "partial", label: "VERIFIED INTERVENTIONS", implementedSlice: "Bounded counterfactual search connects authorized interventions, verified history and snapshot restoration.", missingWork: "Host restoration and general mission outcomes remain domain-specific and need comparative evidence.", evidenceLevel: "integration", sourcePath: "docs/02-orchestration/spirale-de-deblocage.md" },
  { id: "cambium", name: "Counterexample cambium", status: "partial", label: "ISOLATED REPLAY", implementedSlice: "Declarative procedures support isolated compression replay, transactional consolidation, scoped recall and transitive invalidation.", missingWork: "Known-case preservation does not establish general agent-memory safety or coverage of future failures.", evidenceLevel: "integration", sourcePath: "docs/02-orchestration/cambium-contre-exemples.md" },
  { id: "chronotaxis", name: "Aperiodic chronotaxis", status: "partial", label: "RESIDENT PROBES", implementedSlice: "Resident ticks dispatch read-only probes and persist observed coverage, failures and missed windows.", missingWork: "Creating a schedule does not start a daemon; field detection and coverage remain unqualified.", evidenceLevel: "integration", sourcePath: "docs/02-orchestration/chronotaxie-aperiodique.md" },
  { id: "contracted-infinity", name: "Contracted infinity", status: "partial", label: "RISK LINEAGE", implementedSlice: "Preregistered evaluation units, inherited risk grants, provenance checks and signed receipts guard protected topology promotions.", missingWork: "Valid individual statistical tests and field evidence remain required; these gates do not replace deterministic safety checks.", evidenceLevel: "integration", sourcePath: "docs/02-orchestration/infini-sous-contrat.md" },
  { id: "creative-ecology", name: "Natural creative ecology", status: "partial", label: "NATIVE CAUSAL CYCLE", implementedSlice: "Native numerical procedures, POET snapshots, cultural reuse and persisted phenotype run with SQLite reopen and six executed ablation arms.", missingWork: "Open-ended creativity, arbitrary user tasks and all 25 conceptual mechanisms are not demonstrated; search costs are not equalized across arms.", evidenceLevel: "integration", sourcePath: "docs/01-concepts/natural-creative-ecology.md" },
];

export const topologyClaim = (slug: string) => productClaims.find((claim) => claim.id === slug);
