import type { EvidenceState, ImplementationState, IntegrationState } from "@/components/concept-catalog";

export type Topology = {
  slug: string;
  name: string;
  index: string;
  summary: string;
  principle: string;
  runtime: string;
  limit: string;
  status: string;
  color: string;
  implementation: ImplementationState;
  integration: IntegrationState;
  evidence: EvidenceState;
  statusNote: string;
};

export const topologies: Topology[] = [
  { slug: "trinity", name: "Trinity", index: "01", summary: "Parallel candidates with comparative evidence.", principle: "Three candidate worlds work on one mission while keeping their histories apart. A comparative barrier evaluates their evidence before a result is promoted.", runtime: "Dedicated orchestration path, comparative evidence dossiers and a promotion barrier.", limit: "The declared capability profile does not mean every listed capability is an active lease in every run.", status: "WIRED · COMPARATIVE GATE", color: "purple", implementation: "partial", integration: "wired", evidence: "unit-tested", statusNote: "The runtime comparison path is wired. The canonical completion contract still lists the compose-to-merge integration acceptance as open; no end-to-end promotion claim is made." },
  { slug: "a-team", name: "A-Team", index: "02", summary: "Specialists, handoffs and integration.", principle: "A mission is divided across domain specialists. Explicit handoffs move work between them, then an integration step assembles the result.", runtime: "Dedicated dispatch and coordination paths for domain work, handoffs and integration.", limit: "Pareto arbitration only applies where the A-Team evaluator invokes it.", status: "WIRED · SPECIALIZED WORKERS", color: "orange", implementation: "partial", integration: "wired", evidence: "unit-tested", statusNote: "Graph and specialist-assignment tests are documented. Semantic decomposition and a complete mission E2E remain open." },
  { slug: "biocenose", name: "Biocenosis", index: "03", summary: "Community evaluation and explicit ballots.", principle: "A community of roles contributes evidence and evaluations. Consensus can account for confidence and quorum, while the evidence barrier remains in the decision path.", runtime: "Community preparation, evaluation and explicit jury ballots; consensus services are available.", limit: "A juror must provide an explicit ballot. Profile capabilities are not all activated automatically.", status: "WIRED · EVALUATION PATH", color: "green", implementation: "partial", integration: "wired", evidence: "unit-tested", statusNote: "Community preparation and evaluation services are wired. Integration of consensus with the full decision path remains an explicit acceptance item." },
  { slug: "holobionte", name: "Holobiont", index: "04", summary: "A host, symbionts and lifecycle contracts.", principle: "An orchestrating host composes specialist symbionts around mission capabilities, governs their lifecycle, and constrains execution through resource and capability contracts.", runtime: "The topology runtime provisions host and symbiont state, plans bounded cycles, executes supplied capabilities, and records lifecycle and health state.", limit: "Automatic immune behavior is proposed; host veto and drift evaluation are primitives without a guaranteed call in every path.", status: "WIRED · IMMUNITY PARTIAL", color: "orange", implementation: "experimental", integration: "wired", evidence: "unit-tested", statusNote: "A bounded lifecycle runtime is present. The canonical product contract still treats the topology as experimental and leaves veto acceptance open." },
  { slug: "syncytium", name: "Syncytium", index: "05", summary: "A conceptual model for shared state and invariant-aware reconciliation.", principle: "The target architecture separates mergeable operations from changes that need coordination, then checks application invariants. The repository does not implement its distributed protocol.", runtime: "Conceptual target design; no complete multi-writer replication or convergence path is implemented.", limit: "Replication, causal ordering, CRDT convergence and invariant preservation are conditional design goals, not runtime guarantees.", status: "CONCEPTUAL · TARGET DESIGN", color: "blue", implementation: "conceptual", integration: "unassessed", evidence: "unassessed", statusNote: "Canonical documentation classifies Syncytium as a target architecture. Current code does not realize the distributed shared-state protocol." },
  { slug: "rhizome", name: "Rhizome", index: "06", summary: "Versioned capability routing, traces and gated graph growth.", principle: "A revisioned capability graph retains local traces, ranks bounded routes and can admit graph changes through explicit evidence gates.", runtime: "Bounded BFS with deterministic route scoring, versioned trace and session operations, and receipt-bearing growth admission are implemented.", limit: "Host-supplied adapters still determine whether an external provider runs. A route or admission receipt does not prove worker startup or promote a mission result.", status: "WIRED · BOUNDED ROUTING", color: "green", implementation: "partial", integration: "wired", evidence: "unit-tested", statusNote: "Bounded routing, trace operations and gated graph admission are present. External execution depends on host adapters; end-to-end provider startup and mission promotion require separate evidence." },
  { slug: "metapopulation", name: "Metapopulation", index: "07", summary: "Regional populations, verified migration and recovery.", principle: "Semi-independent demes keep local state and exchange typed propagules through directed corridors; each receiver validates transfers locally.", runtime: "Bounded regional cycles observe demes, evaluate migration utility and corridor policy, verify receiver outcomes, and can start classic_patch recolonization trials.", limit: "Migration requires configured enablement and an adaptive signal. Rescue needs a fitness/rollback adapter; a recolonized deme is active only after local viability proof.", status: "WIRED · VERIFIED MIGRATION", color: "purple", implementation: "experimental", integration: "wired", evidence: "unit-tested", statusNote: "Regional controls and receiver-verified migration are wired. The runtime bounds cycles and gates actions; evolutionary execution remains adapter-dependent." },
  { slug: "biome", name: "Biome", index: "08", summary: "Persisted niches, resource allocation and bounded variant cycles.", principle: "A persisted environment tracks niches, specialized populations, resources, and evidence; selected variant operations apply bounded changes to that session.", runtime: "Eleven variant controllers are connected to sessions for resource allocation, foraging, quality-diversity, succession, recovery, persistence, knowledge, compute recommendations, and multi-scale summaries.", limit: "A caller or scheduler must invoke each cycle. The complete autonomous ecology loop, worker placement, provider calls, and external fitness remain outside the topology.", status: "PARTIAL · VARIANT CONTROLLERS", color: "orange", implementation: "partial", integration: "wired", evidence: "unit-tested", statusNote: "The persisted variant operations are wired, but they do not start another cycle by themselves. External worker/provider execution and several measures still depend on callers or adapters." },
];

export function getTopology(slug: string) {
  return topologies.find((topology) => topology.slug === slug);
}
