export type TopologyVariantGuide = { id: string; useCase: string };
export type TopologyGuide = { explanation: string; formula: string; formulaNote: string; variants: TopologyVariantGuide[] };

// Variants are the identifiers in the canonical GenOS catalog. Use cases below
// describe when a policy is useful; they are not claims that it is auto-selected.
export const topologyGuides: Record<string, TopologyGuide> = {
  trinity: {
    explanation: "Trois mondes indépendants traitent la même mission depuis un état initial comparable. Ils gardent leurs dossiers scellés jusqu’à la comparaison; une barrière examine les preuves avant de retenir ou promouvoir un artefact candidat.",
    formula: "D = (x₁, x₂, x₃) ;  scoreᵢ = f(preuvesᵢ, contraintes) ;  admissibleᵢ ⇔ preuvesᵢ ≥ seuil",
    formulaNote: "f représente une règle de comparaison déclarée, pas une probabilité apprise. La sélection peut garder plusieurs solutions non dominées; la promotion d’un candidat n’est pas un déploiement en production.",
    variants: [
      { id: "controlled", useCase: "Baseline reproductible : comparer trois stratégies fixes sur une migration ou une revue de code." },
      { id: "heterogeneous", useCase: "Réduire les erreurs corrélées lors d’une analyse où une seule famille de modèles risquerait de partager le même angle mort." },
      { id: "adversarial", useCase: "Audit de sécurité : produire des contre-exemples et faire examiner les affirmations après le travail indépendant." },
      { id: "counterfactual", useCase: "Décision sensible aux hypothèses : comparer scénario de référence, favorable et défavorable." },
      { id: "factorial", useCase: "Expérience planifiée qui doit comparer systématiquement des combinaisons de stratégies, modèles ou outils; adaptateur requis." },
      { id: "pareto", useCase: "Choix avec compromis explicites entre qualité, coût, latence et risque, sans réduire tout à un seul score." },
      { id: "jury", useCase: "Avis consultatif aveugle quand plusieurs dossiers doivent être départagés; le jury ne remplace pas les gates de preuve." },
      { id: "recursive", useCase: "Mission difficile à décomposer où un sous-problème isolé mérite lui-même une comparaison Trinity, sous budget et profondeur bornés." },
      { id: "adaptive", useCase: "Budget limité avec incertitude restante : redistribuer les ressources entre trois mondes en gardant leur nombre fixe." },
      { id: "temporal", useCase: "Décision dont les résultats immédiats, la maintenance et la réversibilité à long terme diffèrent." },
      { id: "oracular", useCase: "Évaluer la capacité d’un processus à prédire quel candidat réussira, puis comparer la prédiction au résultat vérifié." },
      { id: "exploratory", useCase: "Conception ouverte où préserver des solutions diverses et nouvelles est plus utile que converger tôt." },
    ],
  },
  "a-team": {
    explanation: "A-Team répartit le travail entre spécialistes selon des domaines ou des étapes. Les contrats de transfert cadrent les entrées et sorties; une intégration assemble les livrables. Les dépendances peuvent être séquentielles ou parallèles.",
    formula: "G = (V, E) ;  début(v) ≥ max(fin(u) : (u,v) ∈ E) ;  résultat = intégrer({sortieᵥ})",
    formulaNote: "G est le graphe de travail; E contient les dépendances. La durée idéale est bornée par le chemin critique, tandis que les handoffs et la coordination ajoutent un coût réel.",
    variants: [
      { id: "expert_committee", useCase: "Revue d’architecture ou audit transversal nécessitant plusieurs expertises et une décision collective." },
      { id: "pipeline", useCase: "Traitement à étapes strictement ordonnées, par exemple extraire, vérifier puis synthétiser un dossier." },
      { id: "project_dag", useCase: "Projet aux dépendances ramifiées : documentation et tests peuvent avancer en parallèle avant une fusion." },
      { id: "cross_functional_pod", useCase: "Petit produit ou fonctionnalité à livrer de bout en bout par une équipe réunissant les compétences nécessaires." },
      { id: "boundary_spanner", useCase: "Travail à l’interface de domaines ou de services, où les contrats et traductions entre équipes sont le point de risque." },
      { id: "matrix_team", useCase: "Programme mobilisant plusieurs fonctions tout en gardant des responsabilités fonctionnelles distinctes." },
      { id: "tiger_team", useCase: "Enquête courte et ciblée sur un risque critique, une vulnérabilité ou un incident complexe." },
      { id: "incident_command", useCase: "Incident actif demandant un responsable de coordination, des rôles explicites et des mises à jour contrôlées." },
      { id: "multiteam", useCase: "Initiative large composée de plusieurs équipes autonomes qui doivent synchroniser leurs livrables." },
      { id: "adaptive", useCase: "Mission qui change de forme en cours de route et exige de réaffecter les spécialistes selon les besoins observés." },
      { id: "relay_team", useCase: "Flux avec relais explicites entre spécialistes, utile quand chaque étape exige une compétence différente." },
    ],
  },
  biocenose: {
    explanation: "Une communauté de rôles examine les mêmes propositions à travers des évaluations, des preuves et des désaccords conservés. Selon la politique, l’agrégation privilégie la preuve, un quorum ou une distribution de jugements.",
    formula: "S(c) = Σᵢ wᵢ sᵢ(c) / Σᵢ wᵢ ;  quorum(c) ⇔ Σᵢ wᵢ·voteᵢ(c) ≥ q·Σᵢ wᵢ",
    formulaNote: "sᵢ est l’évaluation d’un membre, wᵢ son poids déclaré et q le seuil de quorum. Une agrégation numérique ne prouve pas la vérité; les preuves et les abstentions doivent rester visibles.",
    variants: [
      { id: "epistemic_jury", useCase: "Évaluer des affirmations factuelles à partir d’experts et de preuves explicites." },
      { id: "delphi_community", useCase: "Estimation incertaine où des tours anonymes peuvent réduire l’ancrage et révéler la dispersion des avis." },
      { id: "adversarial_assembly", useCase: "Audit ou menace où une revue dédiée recherche activement les réfutations." },
      { id: "forecasting_crowd", useCase: "Prévisions probabilistes à comparer ensuite à des résultats observés, avec poids de calibration déclarés." },
      { id: "argumentation_community", useCase: "Débat structuré où l’on doit relier arguments, contre-arguments et sources; maturité partielle." },
      { id: "polycentric_council", useCase: "Décisions couvrant plusieurs domaines ou juridictions avec des avis locaux à préserver; maturité partielle." },
      { id: "byzantine_resilient_community", useCase: "Collectif exposé à des contributions défaillantes ou adverses, lorsque provenance et quarantaine sont centrales; maturité partielle." },
      { id: "minority_preserving_jury", useCase: "Décision à fort enjeu où le dissensus minoritaire doit rester consultable après l’agrégation." },
      { id: "representative_community", useCase: "Consultation à grande échelle résumée par un panel représentatif; maturité partielle." },
      { id: "persistent_community", useCase: "Évaluations répétées où l’historique des jugements et leur évolution comptent; maturité partielle." },
      { id: "human_ai_deliberation", useCase: "Question normative exigeant un jugement humain explicite et la conservation des avis divergents." },
      { id: "hybrid_oracle_community", useCase: "Question vérifiable disposant d’un contrôle déterministe, complété par une revue communautaire." },
    ],
  },
  holobionte: {
    explanation: "Un hôte coordonne des symbiotes spécialisés sous un contrat de capacités et de ressources. L’hôte fixe les frontières et compose les compétences; les mécanismes de veto ou d’immunité ne sont pas garantis dans chaque chemin d’exécution.",
    formula: "Cₘ ⊆ ⋃ᵢ Cᵢ ;  allocationᵢ ≥ 0 ;  Σᵢ allocationᵢ ≤ budgetₘ",
    formulaNote: "Les capacités requises Cₘ doivent être couvertes par les capacités Cᵢ des symbiotes. Le respect du budget dépend du contrat d’allocation; cette formule ne modélise pas la sécurité complète.",
    variants: [
      { id: "organelle", useCase: "Décomposer un système en symbiotes très spécialisés autour d’un hôte qui garde la coordination." },
      { id: "adaptive-microbiome", useCase: "Composition qui doit s’adapter aux compétences disponibles et au profil de mission; mécanismes encore partiels." },
      { id: "immune-critical", useCase: "Mission sensible où menaces déclarées, contrôles indépendants et quarantaine doivent être prioritaires; partiel." },
      { id: "local-first", useCase: "Données ou capacités devant rester au plus près de l’environnement local; le placement réel dépend des exécuteurs disponibles." },
      { id: "regenerative", useCase: "Service devant préparer une reprise après perte de symbiote avec conditions de preuve et de restauration; partiel." },
      { id: "cloud-core/edge-symbionts", useCase: "Coordination centrale cloud avec fonctions spécialisées placées près des données ou appareils edge; partiel." },
      { id: "edge-core/cloud-symbionts", useCase: "Coordination principale en edge avec capacités cloud appelées en soutien; partiel." },
      { id: "memory-rich", useCase: "Travail longitudinal où les souvenirs persistants, leur provenance et la gestion des conflits sont nécessaires; partiel." },
      { id: "competitive-partner", useCase: "Comparer des symbiotes concurrents sous budget commun avant d’allouer durablement une responsabilité; partiel." },
      { id: "procedural", useCase: "Mission encadrée par des procédures et séquences d’étapes explicites; partiel." },
      { id: "tool", useCase: "Composition qui dépend de capacités d’outillage soumises à un manifeste et à des baux; partiel." },
      { id: "cloud-core/edge-sync", useCase: "Hôte cloud et symbiotes edge qui doivent réconcilier les événements et synchroniser leur état; partiel." },
    ],
  },
  syncytium: {
    explanation: "Les membres coordonnent leurs actions autour d’un état partagé, versionné et soumis à des invariants. Les opérations CRDT peuvent fusionner certaines écritures concurrentes; l’évaluation de cohérence vérifie ensuite les contraintes métier.",
    formula: "Sₜ₊₁ = merge(Sₜ, Δ₁, …, Δₙ) ;  invariantⱼ(Sₜ₊₁) = vrai  ∀j",
    formulaNote: "La fusion converge seulement pour les types d’opérations et hypothèses de réplication prévus. Une transaction ou un invariant sémantique peut nécessiter un contrôle supplémentaire.",
    variants: [
      { id: "hard", useCase: "État où les invariants stricts priment et où une écriture invalide doit être refusée." },
      { id: "soft", useCase: "Collaboration où certaines divergences temporaires sont acceptables avant réconciliation." },
      { id: "code", useCase: "Éditions concurrentes de code, d’artefacts ou de plans techniques avec validation après fusion." },
      { id: "document", useCase: "Rédaction collaborative où les mises à jour de contenu doivent converger." },
      { id: "graph", useCase: "État composé de nœuds et liens, comme un graphe de dépendances modifié par plusieurs rôles." },
      { id: "transactional", useCase: "Opérations métier qui doivent être appliquées comme une transaction plutôt que fusionnées librement." },
      { id: "epistemic", useCase: "Base de faits où les sources, contradictions et niveaux de confiance doivent rester attachés aux valeurs." },
      { id: "blackboard", useCase: "Agents qui contribuent à un tableau commun sans se transmettre directement chaque message." },
      { id: "localFirst", useCase: "Usage intermittent ou hors ligne où l’écriture locale précède la synchronisation." },
      { id: "speculative", useCase: "Exploration de changements provisoires, avec besoin d’isoler les hypothèses avant validation." },
      { id: "hierarchical", useCase: "État avec niveaux parent-enfant, par exemple synthèses régionales et détails locaux." },
      { id: "realtimeControl", useCase: "Boucle de contrôle sensible aux mises à jour rapides; les bornes de latence doivent être validées pour le système cible." },
      { id: "humanAi", useCase: "Opérations mêlant agents et humains, avec décisions ou changements traçables dans un état partagé." },
    ],
  },
  rhizome: {
    explanation: "Le Rhizome relie des membres par capacités, traces et relations locales. La session peut sélectionner un membre composé pour un besoin et enregistrer des dépôts stigmergiques; le routage multi-sauts automatique et la croissance autonome restent proposés.",
    formula: "Gₜ = (Nₜ,Eₜ) ;  route₁(c) = arg maxᵢ score(cᵢ, besoin) ;  ρₜ₊₁(e)= (1−λ)ρₜ(e)+Δ(e)",
    formulaNote: "G est le graphe, ρ une trace avec décroissance λ. La formule illustre une intuition de routage et stigmergie; le runtime expose une sélection directe parmi les membres et un calcul sur arêtes fournies.",
    variants: [
      { id: "exploratory", useCase: "Mission dont les besoins sont inconnus au départ et se révèlent pendant l’exploration." },
      { id: "routing", useCase: "Choisir directement un membre compatible avec une capacité demandée." },
      { id: "growth", useCase: "Étudier l’ajout contrôlé d’une capacité lorsque le graphe montre une lacune; création automatique proposée." },
      { id: "resilient", useCase: "Enquête ou service où des routes alternatives sont utiles en cas de membre indisponible." },
      { id: "sparse", useCase: "Graphe large où l’on veut limiter le nombre de branches et conserver des connexions clairsemées." },
      { id: "persistent", useCase: "Travail répété nécessitant une session et des traces conservées entre les étapes." },
      { id: "ephemeral", useCase: "Mission temporaire dont le graphe et ses ressources ne doivent pas persister au-delà de la session." },
      { id: "small_world", useCase: "Réseau modulaire avec quelques hubs observés pour faciliter les échanges locaux." },
      { id: "private", useCase: "Routage au sein d’un périmètre de confiance avec admission et quarantaine explicites." },
      { id: "cross_representation", useCase: "Relier des capacités qui manipulent des représentations différentes, par exemple texte, code et graphe." },
      { id: "procedural", useCase: "Chemin de travail composé d’étapes procédurales typées et de transformations locales." },
      { id: "self_healing", useCase: "Préparer la reconfiguration après défaillance; les mécanismes disponibles restent bornés et dépendent des adaptateurs." },
    ],
  },
  metapopulation: {
    explanation: "Des groupes régionaux semi-indépendants explorent ou traitent des sous-espaces. Des corridors contrôlent les échanges et la migration; quorum et plans de récupération existent comme appels explicites, pas comme boucle autonome permanente.",
    formula: "P = {P₁,…,Pₖ} ;  quorum ⇔ votes pondérés ≥ q·Σwᵢ ;  migration(Pᵢ→Pⱼ) seulement si corridor autorisé",
    formulaNote: "q est le seuil déclaré, wᵢ le poids d’une région. La topologie des corridors, les règles de migration et la souveraineté des données dépendent du variant.",
    variants: [
      { id: "balanced", useCase: "Point de départ général lorsque diversité, exploration et secours doivent rester équilibrés." },
      { id: "resilient", useCase: "Groupes exposés à des pertes où la priorité est le secours et la continuité." },
      { id: "exploratory", useCase: "Recherche de solutions variées dans un espace peu connu." },
      { id: "conservative", useCase: "Contexte à risque où quorum élevé et recherche de contre-exemples sont préférés." },
      { id: "classic_patch", useCase: "Simulation ou plan de récupération par régions et recolonisation après extinction locale." },
      { id: "island_search", useCase: "Optimisation difficile où plusieurs îlots cherchent séparément puis échangent périodiquement des candidats." },
      { id: "heterogeneous_islands", useCase: "Espace inconnu où chaque région utilise une stratégie ou une lignée différente." },
      { id: "source_sink", useCase: "Ressources ou populations inégalement réparties entre régions source et régions consommatrices." },
      { id: "rescue_network", useCase: "Service critique ayant besoin d’un plan de secours et d’un objectif de reprise régional." },
      { id: "stepping_stone", useCase: "Propagation graduelle entre régions voisines pour préserver la diversité et limiter les transferts." },
      { id: "anti_synchrony", useCase: "Défaillances corrélées où coupe-feux et réarrangement des corridors réduisent la contagion." },
      { id: "federated", useCase: "Organisation souveraine où les données doivent rester locales et seuls des résultats attestés circulent." },
      { id: "ephemeral_patch", useCase: "Populations temporaires ou ressources intermittentes nécessitant un rattachement rapide." },
      { id: "persistent", useCase: "Groupes résidents dont la mémoire régionale doit soutenir plusieurs missions." },
      { id: "evolutionary", useCase: "Exploration de stratégies évolutives avec reproduction locale; mécanismes encore partiels." },
      { id: "cultural", useCase: "Transmission de pratiques ou d’artefacts entre groupes sans déplacer les agents eux-mêmes." },
    ],
  },
  biome: {
    explanation: "Biome traite la mission comme un environnement avec ressources, niches et populations spécialisées. Sa boucle bornée observe, propose, contraint, agit puis vérifie; les effets réels demandent une autorisation explicite.",
    formula: "Aᵢ ≥ 0 ;  ΣᵢAᵢ ≤ B ;  xₜ₊₁ = verify(act(constrain(propose(observe(xₜ)))))",
    formulaNote: "Aᵢ est l’allocation à une activité, B le budget. La boucle est une abstraction séquentielle; le mode simulé ne produit pas d’effet réel et la navigation n’est pas autonome.",
    variants: [
      { id: "resource", useCase: "Tâche avec ressources rares où les demandes et une allocation explicite dominent." },
      { id: "exploration", useCase: "Environnement peu connu où l’exploration doit rapporter incertitude, information et preuves." },
      { id: "quality_diversity", useCase: "Conception où l’on veut maintenir plusieurs solutions de qualité dans des niches différentes." },
      { id: "successional", useCase: "Travail par phases : découverte, spécialisation puis stabilisation sous conditions de preuve." },
      { id: "resilience", useCase: "Mission ayant besoin d’une réserve de reprise et de chemins de récupération." },
      { id: "persistent", useCase: "Environnement de travail récurrent où les changements et connaissances réutilisables doivent durer." },
      { id: "open_ended", useCase: "Exploration ouverte de niches utiles, en marquant les pistes non vérifiées comme hypothèses." },
      { id: "adversarial", useCase: "Analyse de population ou de ressources qui doit être challengée par des contre-exemples." },
      { id: "knowledge", useCase: "Recherche où l’environnement est organisé autour de collections de sources ou domaines de connaissance." },
      { id: "compute", useCase: "Calcul soumis à des contraintes d’allocation, de capacité ou de budget." },
      { id: "multi_scale", useCase: "Problème imbriquant des échelles locales et globales qui doivent être observées et résumées ensemble." },
    ],
  },
};
