export type TopologyVariantGuide = { id: string; useCase: string };
export type TopologyGuide = { explanation: string; formula: string; formulaNote: string; variants: TopologyVariantGuide[] };

// Variants are the identifiers in the canonical GenOS catalog. Use cases below
// describe when a policy is useful; they are not claims that it is auto-selected.
export const topologyGuides: Record<string, TopologyGuide> = {
  trinity: {
    explanation: "Three independent worlds handle the same mission from a comparable initial state. They keep their records sealed until comparison; an evidence gate evaluates them before retaining or promoting a candidate artifact.",
    formula: "D = (x₁, x₂, x₃) ;  scoreᵢ = f(evidenceᵢ, constraints) ;  eligibleᵢ ⇔ evidenceᵢ ≥ threshold",
    formulaNote: "f represents a stated comparison rule, not a learned probability. Selection can retain several non-dominated solutions; promoting a candidate is not a production deployment.",
    variants: [
      { id: "controlled", useCase: "Reproducible baseline: compare three fixed strategies on a migration or code review." },
      { id: "heterogeneous", useCase: "Reduce correlated errors when one model family could share the same blind spot." },
      { id: "adversarial", useCase: "Security audit: generate counterexamples and review claims after independent work." },
      { id: "counterfactual", useCase: "Assumption-sensitive decision: compare baseline, favorable, and unfavorable scenarios." },
      { id: "factorial", useCase: "Planned experiment comparing combinations of strategies, models, or tools; an adapter is required." },
      { id: "pareto", useCase: "Choose among explicit quality, cost, latency, and risk trade-offs without collapsing them into one score." },
      { id: "jury", useCase: "Blind advisory review when several reports need a decision; the jury does not replace evidence gates." },
      { id: "recursive", useCase: "A difficult mission where an isolated subproblem needs its own Trinity comparison under bounded budget and depth." },
      { id: "adaptive", useCase: "With a limited budget and remaining uncertainty, redistribute resources across three worlds while keeping their number fixed." },
      { id: "temporal", useCase: "A decision where immediate outcomes, maintenance, and long-term reversibility differ." },
      { id: "oracular", useCase: "Evaluate whether a process can predict which candidate will succeed, then compare its prediction with the verified result." },
      { id: "exploratory", useCase: "Open-ended design where retaining diverse, novel solutions is more useful than converging early." },
    ],
  },
  "a-team": {
    explanation: "A-Team distributes work among specialists by domain or step. Handoff contracts define inputs and outputs; integration assembles the deliverables. Dependencies can be sequential or parallel.",
    formula: "G = (V, E) ;  start(v) ≥ max(end(u) : (u,v) ∈ E) ;  result = integrate({outputᵥ})",
    formulaNote: "G is the work graph; E contains dependencies. Ideal duration is bounded by the critical path, while handoffs and coordination add real cost.",
    variants: [
      { id: "expert_committee", useCase: "Architecture review or cross-functional audit that needs several specialties and a collective decision." },
      { id: "pipeline", useCase: "Strictly ordered processing, such as extracting, verifying, then synthesizing a report." },
      { id: "project_dag", useCase: "A project with branching dependencies where documentation and tests can advance in parallel before merging." },
      { id: "cross_functional_pod", useCase: "A small product or feature delivered end to end by a team with the required skills." },
      { id: "boundary_spanner", useCase: "Work at the boundary between domains or services, where contracts and translation between teams are the main risk." },
      { id: "matrix_team", useCase: "A program using several functions while retaining distinct functional responsibilities." },
      { id: "tiger_team", useCase: "A short, focused investigation into a critical risk, vulnerability, or complex incident." },
      { id: "incident_command", useCase: "An active incident needing a coordination lead, explicit roles, and controlled updates." },
      { id: "multiteam", useCase: "A large initiative made up of autonomous teams that must synchronize deliverables." },
      { id: "adaptive", useCase: "A mission that changes shape and requires specialists to be reassigned as needs emerge." },
      { id: "relay_team", useCase: "A workflow with explicit handoffs between specialists when each step needs a different skill." },
    ],
  },
  biocenose: {
    explanation: "A community of roles examines the same proposals through evaluations, evidence, and preserved disagreements. Depending on policy, aggregation may prioritize evidence, a quorum, or a distribution of judgments.",
    formula: "S(c) = Σᵢ wᵢ sᵢ(c) / Σᵢ wᵢ ;  quorum(c) ⇔ Σᵢ wᵢ·voteᵢ(c) ≥ q·Σᵢ wᵢ",
    formulaNote: "sᵢ is a member's evaluation, wᵢ its declared weight, and q the quorum threshold. Numeric aggregation does not prove truth; evidence and abstentions must remain visible.",
    variants: [
      { id: "epistemic_jury", useCase: "Evaluate factual claims using experts and explicit evidence." },
      { id: "delphi_community", useCase: "Uncertain estimates where anonymous rounds can reduce anchoring and reveal the spread of opinion." },
      { id: "adversarial_assembly", useCase: "An audit or threat review where a dedicated group actively looks for refutations." },
      { id: "forecasting_crowd", useCase: "Probabilistic forecasts compared with observed outcomes using declared calibration weights." },
      { id: "argumentation_community", useCase: "Structured debate that links arguments, counterarguments, and sources; partial maturity." },
      { id: "polycentric_council", useCase: "Decisions across domains or jurisdictions where local views should be preserved; partial maturity." },
      { id: "byzantine_resilient_community", useCase: "A group exposed to faulty or adversarial contributions where provenance and quarantine are central; partial maturity." },
      { id: "minority_preserving_jury", useCase: "A high-stakes decision where minority dissent must remain available after aggregation." },
      { id: "representative_community", useCase: "A large-scale consultation summarized by a representative panel; partial maturity." },
      { id: "persistent_community", useCase: "Repeated evaluations where the history and evolution of judgments matter; partial maturity." },
      { id: "human_ai_deliberation", useCase: "A normative question that needs explicit human judgment and preservation of differing views." },
      { id: "hybrid_oracle_community", useCase: "A verifiable question with deterministic checks supplemented by community review." },
    ],
  },
  holobionte: {
    explanation: "A host coordinates specialist symbionts under capability and resource contracts. The host sets boundaries and composes skills; veto or immune mechanisms are not guaranteed in every execution path.",
    formula: "Cₘ ⊆ ⋃ᵢ Cᵢ ;  allocationᵢ ≥ 0 ;  Σᵢ allocationᵢ ≤ budgetₘ",
    formulaNote: "Required capabilities Cₘ must be covered by symbiont capabilities Cᵢ. Budget compliance depends on the allocation contract; this formula does not model full safety.",
    variants: [
      { id: "organelle", useCase: "Decompose a system into highly specialized symbionts around a coordinating host." },
      { id: "adaptive-microbiome", useCase: "A composition that adapts to available skills and the mission profile; mechanisms remain partial." },
      { id: "immune-critical", useCase: "A sensitive mission prioritizing declared threats, independent checks, and quarantine; partial." },
      { id: "local-first", useCase: "Data or capabilities that should stay close to the local environment; placement depends on available executors." },
      { id: "regenerative", useCase: "A service preparing recovery after symbiont loss with evidence and restoration conditions; partial." },
      { id: "cloud-core/edge-symbionts", useCase: "Central cloud coordination with specialist functions placed near edge data or devices; partial." },
      { id: "edge-core/cloud-symbionts", useCase: "Primary edge coordination that calls on cloud capabilities for support; partial." },
      { id: "memory-rich", useCase: "Long-running work that needs persistent memories, provenance, and conflict handling; partial." },
      { id: "competitive-partner", useCase: "Compare competing symbionts under a shared budget before assigning lasting responsibility; partial." },
      { id: "procedural", useCase: "A mission governed by explicit procedures and ordered steps; partial." },
      { id: "tool", useCase: "A composition that depends on tool capabilities governed by a manifest and leases; partial." },
      { id: "cloud-core/edge-sync", useCase: "A cloud host and edge symbionts reconciling events and synchronizing state; partial." },
    ],
  },
  syncytium: {
    explanation: "Members coordinate around shared, versioned state subject to invariants. CRDT operations can merge some concurrent writes; a consistency check then verifies business constraints.",
    formula: "Sₜ₊₁ = merge(Sₜ, Δ₁, …, Δₙ) ;  invariantⱼ(Sₜ₊₁) = true  ∀j",
    formulaNote: "Merging converges only for the supported operation types and replication assumptions. A transaction or semantic invariant may need additional checks.",
    variants: [
      { id: "hard", useCase: "State where strict invariants take priority and invalid writes must be rejected." },
      { id: "soft", useCase: "Collaboration where some temporary divergence is acceptable before reconciliation." },
      { id: "code", useCase: "Concurrent edits to code, artifacts, or technical plans with validation after merging." },
      { id: "document", useCase: "Collaborative writing where content updates need to converge." },
      { id: "graph", useCase: "State made of nodes and links, such as a dependency graph edited by multiple roles." },
      { id: "transactional", useCase: "Business operations that must be applied as a transaction rather than freely merged." },
      { id: "epistemic", useCase: "A fact base where sources, contradictions, and confidence levels stay attached to values." },
      { id: "blackboard", useCase: "Agents contributing to a shared board without sending every message directly." },
      { id: "localFirst", useCase: "Intermittent or offline use where local writes happen before synchronization." },
      { id: "speculative", useCase: "Exploration of provisional changes that need isolated assumptions before validation." },
      { id: "hierarchical", useCase: "State with parent-child levels, such as regional summaries and local details." },
      { id: "realtimeControl", useCase: "A control loop sensitive to rapid updates where latency bounds must be validated for the target system." },
      { id: "humanAi", useCase: "Operations combining agents and people, with traceable decisions and changes in shared state." },
    ],
  },
  rhizome: {
    explanation: "Rhizome connects members through capabilities, traces, and local relationships. A session can select a composed member for a need and record stigmergic deposits; automatic multi-hop routing and autonomous growth remain proposals.",
    formula: "Gₜ = (Nₜ,Eₜ) ;  route₁(c) = arg maxᵢ score(cᵢ, need) ;  ρₜ₊₁(e)= (1−λ)ρₜ(e)+Δ(e)",
    formulaNote: "G is the graph and ρ a trace with decay λ. The formula illustrates routing and stigmergy; the runtime exposes direct member selection and calculations over supplied edges.",
    variants: [
      { id: "exploratory", useCase: "A mission whose needs are unknown at first and emerge during exploration." },
      { id: "routing", useCase: "Directly select a member compatible with a requested capability." },
      { id: "growth", useCase: "Study controlled addition of a capability when the graph reveals a gap; automatic creation is only proposed." },
      { id: "resilient", useCase: "An investigation or service that benefits from alternate routes when a member is unavailable." },
      { id: "sparse", useCase: "A large graph where branches should be limited and connections kept sparse." },
      { id: "persistent", useCase: "Repeated work that needs a session and traces preserved across steps." },
      { id: "ephemeral", useCase: "A temporary mission whose graph and resources should not persist after the session." },
      { id: "small_world", useCase: "A modular network with a few observed hubs to support local exchange." },
      { id: "private", useCase: "Routing within a trusted boundary with explicit admission and quarantine." },
      { id: "cross_representation", useCase: "Connect capabilities handling different representations, such as text, code, and graphs." },
      { id: "procedural", useCase: "A workflow made of typed procedural steps and local transformations." },
      { id: "self_healing", useCase: "Prepare reconfiguration after failure; available mechanisms remain bounded and adapter-dependent." },
    ],
  },
  metapopulation: {
    explanation: "Semi-independent regional groups explore or process subspaces. Corridors control exchange and migration; quorum and recovery plans are explicit calls, not a permanent autonomous loop.",
    formula: "P = {P₁,…,Pₖ} ;  quorum ⇔ weighted votes ≥ q·Σwᵢ ;  migration(Pᵢ→Pⱼ) only if corridor is authorized",
    formulaNote: "q is the declared threshold and wᵢ a region's weight. Corridor topology, migration rules, and data sovereignty depend on the variant.",
    variants: [
      { id: "balanced", useCase: "A general starting point when diversity, exploration, and recovery should stay balanced." },
      { id: "resilient", useCase: "Groups exposed to losses where recovery and continuity take priority." },
      { id: "exploratory", useCase: "Search for varied solutions in a poorly understood space." },
      { id: "conservative", useCase: "A risky context favoring high quorum and the search for counterexamples." },
      { id: "classic_patch", useCase: "Regional recovery simulation or plan with recolonization after local extinction." },
      { id: "island_search", useCase: "A hard optimization problem where islands search separately and periodically exchange candidates." },
      { id: "heterogeneous_islands", useCase: "An unknown space where each region uses a different strategy or lineage." },
      { id: "source_sink", useCase: "Resources or populations unevenly distributed between source and consuming regions." },
      { id: "rescue_network", useCase: "A critical service needing a fallback plan and regional recovery objective." },
      { id: "stepping_stone", useCase: "Gradual spread between neighboring regions to preserve diversity and limit transfers." },
      { id: "anti_synchrony", useCase: "Correlated failures where circuit breakers and corridor changes reduce contagion." },
      { id: "federated", useCase: "A sovereign organization where data stays local and only attested results move." },
      { id: "ephemeral_patch", useCase: "Temporary populations or intermittent resources that need fast reattachment." },
      { id: "persistent", useCase: "Resident groups whose regional memory needs to support multiple missions." },
      { id: "evolutionary", useCase: "Exploration of evolutionary strategies with local reproduction; mechanisms remain partial." },
      { id: "cultural", useCase: "Transfer practices or artifacts between groups without moving the agents themselves." },
    ],
  },
  biome: {
    explanation: "Biome treats a mission as an environment with resources, niches, and specialized populations. Its bounded loop observes, proposes, constrains, acts, and verifies; real effects require explicit authorization.",
    formula: "Aᵢ ≥ 0 ;  ΣᵢAᵢ ≤ B ;  xₜ₊₁ = verify(act(constrain(propose(observe(xₜ)))))",
    formulaNote: "Aᵢ is the allocation to an activity and B the budget. The loop is a sequential abstraction; simulated mode has no real effect and navigation is not autonomous.",
    variants: [
      { id: "resource", useCase: "A task with scarce resources where demand and explicit allocation dominate." },
      { id: "exploration", useCase: "A poorly understood environment where exploration should return uncertainty, information, and evidence." },
      { id: "quality_diversity", useCase: "Design work that should maintain several high-quality solutions in different niches." },
      { id: "successional", useCase: "Phased work: discovery, specialization, then stabilization under evidence conditions." },
      { id: "resilience", useCase: "A mission that needs recovery reserves and fallback paths." },
      { id: "persistent", useCase: "Recurring work where changes and reusable knowledge should persist." },
      { id: "open_ended", useCase: "Open-ended exploration of useful niches, marking unverified leads as hypotheses." },
      { id: "adversarial", useCase: "Population or resource analysis that should be challenged with counterexamples." },
      { id: "knowledge", useCase: "Research where the environment is organized around source collections or knowledge domains." },
      { id: "compute", useCase: "Compute work subject to allocation, capacity, or budget constraints." },
      { id: "multi_scale", useCase: "A problem combining local and global scales that must be observed and summarized together." },
    ],
  },
};
