export type TopologyVariantGuide = { id: string; useCase: string };
export type TopologyGuide = {
  explanation: string;
  formula: string;
  formulaNote: string;
  purpose: string;
  selection: string;
  scientificBasis: string;
  failureModes: string[];
  relatedConcepts: string[];
  benchmarkPath?: string;
  variants: TopologyVariantGuide[];
};

// Variants are the identifiers in the canonical GenOS catalog. Use cases below
// describe when a policy is useful; they are not claims that it is auto-selected.
export const topologyGuides: Record<string, TopologyGuide> = {
  trinity: {
    explanation: "Three independent worlds handle the same mission from a comparable initial state. They keep their records sealed until comparison; an evidence gate evaluates them before retaining or promoting a candidate artifact.",
    formula: "D = (x₁, x₂, x₃) ;  scoreᵢ = f(evidenceᵢ, constraints) ;  eligibleᵢ ⇔ evidenceᵢ ≥ threshold",
    formulaNote: "f represents a stated comparison rule, not a learned probability. Selection can retain several non-dominated solutions; promoting a candidate is not a production deployment.",
    purpose: "Compare independent approaches to one mission while keeping their intermediate histories separate until evaluation.",
    selection: "Choose Trinity when parallel candidate work fits the budget and the result can be assessed against shared constraints and comparable evidence.",
    scientificBasis: "Its useful foundations are controlled comparison, independent replication, and multi-objective selection. The three-world name is a runtime design, not a claim of a specific biological mechanism.",
    failureModes: ["Correlated strategies can share the same blind spot.", "Incomparable or empty evidence can make the gate inconclusive.", "A passing promotion gate does not deploy or certify a production system."],
    relatedConcepts: ["counterfactual-workspaces", "evidence", "gvx", "a-team"],
    variants: [
      { id: "controlled", useCase: "Reproducible baseline: compare three fixed strategies on a migration or code review." },
      { id: "heterogeneous", useCase: "Reduce correlated errors when one model family could share the same blind spot." },
      { id: "adversarial", useCase: "Security audit: generate counterexamples and review claims after independent work." },
      { id: "counterfactual", useCase: "Assumption-sensitive decision: compare baseline, favorable, and unfavorable scenarios." },
      { id: "factorial", useCase: "Planned experiment comparing combinations of strategies, models, or tools; an adapter is required." },
      { id: "pareto", useCase: "Choose among explicit quality, cost, latency, and risk trade-offs without collapsing them into one score." },
      { id: "jury", useCase: "Blind advisory review when several reports need a decision; the jury does not replace evidence gates." },
      { id: "recursive", useCase: "A difficult mission where an isolated subproblem needs its own Trinity comparison under bounded budget and depth." },
      { id: "adaptive", useCase: "With a limited budget and remaining uncertainty, redistribute resources across three worlds while keeping their number fixed." },
      { id: "temporal", useCase: "A decision where immediate outcomes, maintenance, and long-term reversibility differ." },
      { id: "oracular", useCase: "Evaluate whether a process can predict which candidate will succeed, then compare its prediction with the verified result." },
      { id: "exploratory", useCase: "Open-ended design where retaining diverse, novel solutions is more useful than converging early." },
    ],
  },
  "a-team": {
    explanation: "A-Team distributes work among specialists by domain or step. Handoff contracts define inputs and outputs; integration assembles the deliverables. Dependencies can be sequential or parallel.",
    formula: "G = (V, E) ;  start(v) ≥ max(end(u) : (u,v) ∈ E) ;  result = integrate({outputᵥ})",
    formulaNote: "G is the work graph; E contains dependencies. Ideal duration is bounded by the critical path, while handoffs and coordination add real cost.",
    purpose: "Split work across specialists when the mission has distinct domains, dependencies, or handoff boundaries.",
    selection: "Choose A-Team when requirements can be represented as roles and work dependencies. Text-only mission descriptions may not produce a fully validated work graph.",
    scientificBasis: "The technical model comes from task graphs, specialization, and dependency scheduling. Team metaphors do not guarantee that every role is staffed by an independent expert.",
    failureModes: ["A missing specialist or invalid dependency can block downstream work.", "A handoff can lose context or provenance.", "Integration can hide disagreement or combine incompatible outputs."],
    relatedConcepts: ["worker-kinds", "workflows", "morphogenesis", "evidence"],
    benchmarkPath: "06-benchmarks/benchmark-ateam.md",
    variants: [
      { id: "expert_committee", useCase: "Architecture review or cross-functional audit that needs several specialties and a collective decision." },
      { id: "pipeline", useCase: "Strictly ordered processing, such as extracting, verifying, then synthesizing a report." },
      { id: "project_dag", useCase: "A project with branching dependencies where documentation and tests can advance in parallel before merging." },
      { id: "cross_functional_pod", useCase: "A small product or feature delivered end to end by a team with the required skills." },
      { id: "boundary_spanner", useCase: "Work at the boundary between domains or services, where contracts and translation between teams are the main risk." },
      { id: "matrix_team", useCase: "A program using several functions while retaining distinct functional responsibilities." },
      { id: "tiger_team", useCase: "A short, focused investigation into a critical risk, vulnerability, or complex incident." },
      { id: "incident_command", useCase: "An active incident needing a coordination lead, explicit roles, and controlled updates." },
      { id: "multiteam", useCase: "A large initiative made up of autonomous teams that must synchronize deliverables." },
      { id: "adaptive", useCase: "A mission that changes shape and requires specialists to be reassigned as needs emerge." },
      { id: "relay_team", useCase: "A workflow with explicit handoffs between specialists when each step needs a different skill." },
    ],
  },
  biocenose: {
    explanation: "A community of roles examines the same proposals through evaluations, evidence, and preserved disagreements. Depending on policy, aggregation may prioritize evidence, a quorum, or a distribution of judgments.",
    formula: "S(c) = Σᵢ wᵢ sᵢ(c) / Σᵢ wᵢ ;  quorum(c) ⇔ Σᵢ wᵢ·voteᵢ(c) ≥ q·Σᵢ wᵢ",
    formulaNote: "sᵢ is a member's evaluation, wᵢ its declared weight, and q the quorum threshold. Numeric aggregation does not prove truth; evidence and abstentions must remain visible.",
    purpose: "Make collective review and judgment explicit while retaining the evidence, abstentions, and dissent that inform an aggregate result.",
    selection: "Choose Biocenosis when a decision benefits from several roles evaluating common proposals under a declared ballot and aggregation policy.",
    scientificBasis: "The model draws on deliberation, epistemic aggregation, quorum, and probabilistic calibration. A majority or weighted score is not a truth oracle.",
    failureModes: ["A quorum may not be reached or may conceal minority disagreement.", "Correlated judgments can amplify shared errors.", "Missing evidence or unresolved outcomes makes calibration scores incomplete."],
    relatedConcepts: ["beliefs", "brier-calibration", "evidence", "adaptive-epistemic-immunity"],
    variants: [
      { id: "epistemic_jury", useCase: "Evaluate factual claims using experts and explicit evidence." },
      { id: "delphi_community", useCase: "Uncertain estimates where anonymous rounds can reduce anchoring and reveal the spread of opinion." },
      { id: "adversarial_assembly", useCase: "An audit or threat review where a dedicated group actively looks for refutations." },
      { id: "forecasting_crowd", useCase: "Probabilistic forecasts compared with observed outcomes using declared calibration weights." },
      { id: "argumentation_community", useCase: "Structured debate that links arguments, counterarguments, and sources; partial maturity." },
      { id: "polycentric_council", useCase: "Decisions across domains or jurisdictions where local views should be preserved; partial maturity." },
      { id: "byzantine_resilient_community", useCase: "A group exposed to faulty or adversarial contributions where provenance and quarantine are central; partial maturity." },
      { id: "minority_preserving_jury", useCase: "A high-stakes decision where minority dissent must remain available after aggregation." },
      { id: "representative_community", useCase: "A large-scale consultation summarized by a representative panel; partial maturity." },
      { id: "persistent_community", useCase: "Repeated evaluations where the history and evolution of judgments matter; partial maturity." },
      { id: "human_ai_deliberation", useCase: "A normative question that needs explicit human judgment and preservation of differing views." },
      { id: "hybrid_oracle_community", useCase: "A verifiable question with deterministic checks supplemented by community review." },
    ],
  },
  holobionte: {
    explanation: "A host coordinates specialist symbionts under capability and resource contracts. The host sets boundaries and composes skills; veto or immune mechanisms are not guaranteed in every execution path.",
    formula: "Cₘ ⊆ ⋃ᵢ Cᵢ ;  allocationᵢ ≥ 0 ;  Σᵢ allocationᵢ ≤ budgetₘ",
    formulaNote: "Required capabilities Cₘ must be covered by symbiont capabilities Cᵢ. Budget compliance depends on the allocation contract; this formula does not model full safety.",
    purpose: "Compose specialist capabilities around a host that keeps authority, resource allocation, and lifecycle state visible.",
    selection: "Choose Holobiont when a mission needs a set of bounded specialist services coordinated by a host. Every capability and executor must be supplied under the run contract.",
    scientificBasis: "The host–symbiont relationship is an ecological analogy translated into contracts, provisioning, execution, and health records. It does not imply automatic immunity or biological equivalence.",
    failureModes: ["A required capability may have no admissible executor.", "Resource allocation can constrain or prevent a planned cycle.", "Host veto and immune checks are not guaranteed on every path."],
    relatedConcepts: ["symbionts", "immune-system", "metabolism", "plasmids"],
    benchmarkPath: "06-benchmarks/benchmark-longitudinal-holobionte.md",
    variants: [
      { id: "organelle", useCase: "Decompose a system into highly specialized symbionts around a coordinating host." },
      { id: "adaptive-microbiome", useCase: "A composition that adapts to available skills and the mission profile; mechanisms remain partial." },
      { id: "immune-critical", useCase: "A sensitive mission prioritizing declared threats, independent checks, and quarantine; partial." },
      { id: "local-first", useCase: "Data or capabilities that should stay close to the local environment; placement depends on available executors." },
      { id: "regenerative", useCase: "A service preparing recovery after symbiont loss with evidence and restoration conditions; partial." },
      { id: "cloud-core/edge-symbionts", useCase: "Central cloud coordination with specialist functions placed near edge data or devices; partial." },
      { id: "edge-core/cloud-symbionts", useCase: "Primary edge coordination that calls on cloud capabilities for support; partial." },
      { id: "memory-rich", useCase: "Long-running work that needs persistent memories, provenance, and conflict handling; partial." },
      { id: "competitive-partner", useCase: "Compare competing symbionts under a shared budget before assigning lasting responsibility; partial." },
      { id: "procedural", useCase: "A mission governed by explicit procedures and ordered steps; partial." },
      { id: "tool", useCase: "A composition that depends on tool capabilities governed by a manifest and leases; partial." },
      { id: "cloud-core/edge-sync", useCase: "A cloud host and edge symbionts reconciling events and synchronizing state; partial." },
    ],
  },
  syncytium: {
    explanation: "Syncytium is a target design for participants working around shared state. It separates mergeable operations from changes that need coordination, then checks application invariants.",
    formula: "Sₜ₊₁ = merge(Sₜ, Δ₁, …, Δₙ) ;  invariantⱼ(Sₜ₊₁) = true  ∀j",
    formulaNote: "This notation describes a design goal, not an implemented merge. CRDT convergence depends on the selected data type, delivery, and merge assumptions; application invariants need their own verification.",
    purpose: "Describe a shared-state architecture that distinguishes conditional convergence from application validity and coordination needs.",
    selection: "Consider the Syncytium model when a system needs shared state and can define operation semantics, causal assumptions, and invariants. The distributed protocol is not implemented in this runtime.",
    scientificBasis: "The target design draws on distributed-state and CRDT research. The biological analogy does not establish convergence or semantic consistency in software.",
    failureModes: ["Unsupported operations may diverge under concurrent writes.", "A convergent merge can still violate a business invariant.", "CRDT guarantees depend on data type and delivery assumptions; this repository does not implement the distributed protocol."],
    relatedConcepts: ["persistence", "evidence", "agent-relationships", "morphogenesis"],
    benchmarkPath: "06-benchmarks/benchmark-syncytium.md",
    variants: [
      { id: "hard", useCase: "State where strict invariants take priority and invalid writes must be rejected." },
      { id: "soft", useCase: "Collaboration where some temporary divergence is acceptable before reconciliation." },
      { id: "code", useCase: "Concurrent edits to code, artifacts, or technical plans with validation after merging." },
      { id: "document", useCase: "Collaborative writing where content updates need to converge." },
      { id: "graph", useCase: "State made of nodes and links, such as a dependency graph edited by multiple roles." },
      { id: "transactional", useCase: "Business operations that must be applied as a transaction rather than freely merged." },
      { id: "epistemic", useCase: "A fact base where sources, contradictions, and confidence levels stay attached to values." },
      { id: "blackboard", useCase: "Agents contributing to a shared board without sending every message directly." },
      { id: "localFirst", useCase: "Intermittent or offline use where local writes happen before synchronization." },
      { id: "speculative", useCase: "Exploration of provisional changes that need isolated assumptions before validation." },
      { id: "hierarchical", useCase: "State with parent-child levels, such as regional summaries and local details." },
      { id: "realtimeControl", useCase: "A control loop sensitive to rapid updates where latency bounds must be validated for the target system." },
      { id: "humanAi", useCase: "Operations combining agents and people, with traceable decisions and changes in shared state." },
    ],
  },
  rhizome: {
    explanation: "Rhizome maintains a versioned capability graph with local traces. It can diagnose gaps, rank bounded routes, and admit a capability change after budget, provider, and evidence checks.",
    formula: "Gₜ = (Nₜ,Eₜ) ;  route₁(c) = arg maxᵢ score(cᵢ, need) ;  ρₜ₊₁(e)= (1−λ)ρₜ(e)+Δ(e)",
    formulaNote: "G is the revisioned capability graph and ρ a trace. The runtime uses bounded BFS and deterministic route scoring; the equation is illustrative, not a learned probability or a guarantee that a provider started.",
    purpose: "Find bounded routes between declared capabilities, retain local traces, and admit graph growth through explicit evidence gates.",
    selection: "Choose Rhizome when capability relationships, bounded multi-hop routes, or versioned graph growth help the mission. External provider execution still requires a host-supplied adapter.",
    scientificBasis: "The model draws on graph routing and stigmergy. The implemented route ranking and trace updates are software operations, not proof of biological equivalence or production performance.",
    failureModes: ["A route can be absent, stale, or over its cost and trust limits.", "A signed admission receipt does not prove an external worker started.", "Route selection and graph admission do not by themselves promote a mission result."],
    relatedConcepts: ["agent-relationships", "stigmergy", "worker-kinds", "communication-ecology"],
    variants: [
      { id: "exploratory", useCase: "A mission whose needs are unknown at first and emerge during exploration." },
      { id: "routing", useCase: "Find a bounded multi-hop path between a requested capability and a compatible provider." },
      { id: "growth", useCase: "Admit a capability change when a diagnosed graph gap passes budget, utility, provider, and evidence checks." },
      { id: "resilient", useCase: "An investigation or service that benefits from alternate routes when a member is unavailable." },
      { id: "sparse", useCase: "A large graph where branches should be limited and connections kept sparse." },
      { id: "persistent", useCase: "Repeated work that needs a session and traces preserved across steps." },
      { id: "ephemeral", useCase: "A temporary mission whose graph and resources should not persist after the session." },
      { id: "small_world", useCase: "A modular network with a few observed hubs to support local exchange." },
      { id: "private", useCase: "Routing within a trusted boundary with explicit admission and quarantine." },
      { id: "cross_representation", useCase: "Route across representations through an admitted bridge with round-trip, semantic, or loss-bound verification." },
      { id: "procedural", useCase: "A workflow made of typed procedural steps and local transformations." },
      { id: "self_healing", useCase: "Prepare reconfiguration after failure; available mechanisms remain bounded and adapter-dependent." },
    ],
  },
  metapopulation: {
    explanation: "Metapopulation coordinates semi-independent demes over directed corridors. Configured regional cycles can verify migrations and selected recovery operations while each receiver keeps local authority over admission.",
    formula: "Q = Σ_g w_g·1[support_g] / Σ_g w_g ;  reached ⇔ Q ≥ q ;  migration(Dᵢ→Dⱼ) only on an authorized corridor",
    formulaNote: "Each independent source/model group contributes at most one representative; q is the declared threshold and abstention cannot support quorum. Corridors are directed, and regional cycles apply budget, risk, provenance, and receiver-validation gates.",
    purpose: "Preserve regional capability through local work, selective migration, verified recovery, and explicit lineage and quorum rules.",
    selection: "Choose Metapopulation when the task can be partitioned into semi-independent regions and the allowed exchange or recovery rules are known.",
    scientificBasis: "The model comes from patch ecology and population exchange. Software states and verified services do not establish biological equivalence or prove that regional persistence improves mission outcomes.",
    failureModes: ["An empty or weak source may not provide a compatible founder or rescue candidate.", "A propagule that succeeds at its source can still fail local receiver validation.", "The runtime does not infer extinction from silence or declare recolonization successful without local viability evidence."],
    relatedConcepts: ["populations", "evolution-selection", "resilience", "cryptobiosis"],
    variants: [
      { id: "balanced", useCase: "Coordinate regional coverage, complementary migration, diversity, and recovery under configured quorum policy." },
      { id: "resilient", useCase: "Maintain critical capabilities across local losses with explicitly planned fallback migration or recovery." },
      { id: "exploratory", useCase: "Search poorly understood spaces across regions while selecting novelty and preserving independent local work." },
      { id: "conservative", useCase: "Review counterexamples and provenance before supporting a regional decision; abstentions cannot support quorum." },
      { id: "classic_patch", useCase: "Vacate a collapsed deme's patch and start a multi-lineage trial, then await local viability proof." },
      { id: "island_search", useCase: "Run independent regional searches and periodically migrate incumbents or counterexamples when policy gates allow." },
      { id: "heterogeneous_islands", useCase: "Keep different algorithms, providers, or lineages in different regions and exchange complementary candidates." },
      { id: "source_sink", useCase: "Route support directionally from productive sources to receiving or at-risk sinks; roles may rotate with supplied history." },
      { id: "rescue_network", useCase: "Plan a bounded rescue over redundant corridors with receiver fitness measurement and rollback." },
      { id: "stepping_stone", useCase: "Move novelty or cultural propagules across adjacent regions without direct long-range jumps." },
      { id: "anti_synchrony", useCase: "Reduce or freeze risky corridors when regional error or strategy signals are correlated." },
      { id: "federated", useCase: "Keep data and regional state local; transfer only classified, verified, and authorized propagules." },
      { id: "ephemeral_patch", useCase: "Handle temporary or unavailable patches with dormancy and service-backed reattachment." },
      { id: "persistent", useCase: "Keep resident demes, local memory, and lineage across missions under validated daemon leases." },
      { id: "evolutionary", useCase: "Explore local reproduction, selection, and migration through the evolutionary engine; this path remains partial and adapter-dependent." },
      { id: "cultural", useCase: "Keep agents resident while procedures, artifacts, tests, and memory fragments move between regions." },
    ],
  },
  biome: {
    explanation: "Biome keeps a persisted resource-and-niche model with specialized populations. A caller-invoked variant cycle performs one bounded observation, decision, and transformation; it does not restart itself as a continuous ecological loop.",
    formula: "Aᵢ ≥ 0 ;  ΣᵢAᵢ + Rᵣₑₛₑᵣᵥₑ ≤ B ;  cycleₜ = verify(act(constrain(propose(observe(Sₜ))))) ;  next cycle ← caller",
    formulaNote: "Aᵢ is an allocation to an activity and B is the available budget. This is a model of a bounded variant call, not a self-running loop; worker placement, provider calls, and real effects require separate callers and authorization.",
    purpose: "Allocate resources across specialized niches and apply bounded foraging, diversity, recovery, and persistence policies.",
    selection: "Choose Biome when resource pressure, niche yield, local populations, or phase changes matter. The caller or scheduler must invoke each cycle; external workers and providers are not launched by the illustration.",
    scientificBasis: "The model uses ecological concepts such as niches, resource allocation, and foraging as software abstractions. The topology is partial and does not establish biological equivalence or improved mission outcomes.",
    failureModes: ["An incorrect environment estimate or external fitness signal can misdirect allocation.", "A budget or evidence gate can block a phase or recovery transition.", "A compute recommendation does not move a worker, and a foraging result does not execute its patch."],
    relatedConcepts: ["niches", "metabolism", "web-foraging", "populations"],
    variants: [
      { id: "resource", useCase: "Tasks that need budgeted allocation across niche minimums, scarce resources, and a recovery reserve." },
      { id: "exploration", useCase: "Unknown work where bounded foraging scores patch yield, curiosity, and stagnation before requesting worker execution." },
      { id: "quality_diversity", useCase: "Optimization or design where caller-supplied descriptors and operators should preserve a diverse elite archive." },
      { id: "successional", useCase: "Long work that advances from pioneer to specialist to stabilizer only after evidence and stability gates." },
      { id: "resilience", useCase: "A mission that needs redundancy, protected refuges, confirmed-extinction handling, and reserve-funded recovery." },
      { id: "persistent", useCase: "Recurring work where a shared persistence key restores regional memory, biofilm, and configured decay." },
      { id: "open_ended", useCase: "Bounded child-environment exploration that opens new niches only after verifier evidence." },
      { id: "adversarial", useCase: "Safe scenario-level challenge and defense with mitigation counts and archived references; no live attack execution." },
      { id: "knowledge", useCase: "Research that treats source collections as niches, with freshness, credibility, duplication, contradiction, and provenance checks." },
      { id: "compute", useCase: "Compute tasks that need feasible provider ranking by estimated cost, latency, energy, and locality without relocating a worker." },
      { id: "multi_scale", useCase: "Large tasks that aggregate supplied individual, population, and community measures and propagate authorized constraints." },
    ],
  },
};
