import type { EvidenceState, ImplementationState, IntegrationState } from "@/components/concept-catalog";

export type Topology = {
  slug: string;
  name: string;
  index: string;
  summary: string;
  principle: string;
  runtime: string;
  limit: string;
  status: string;
  color: string;
  implementation: ImplementationState;
  integration: IntegrationState;
  evidence: EvidenceState;
  statusNote: string;
};

export const topologies: Topology[] = [
  { slug: "trinity", name: "Trinity", index: "01", summary: "Three-world baseline with twelve controlled variants.", principle: "The baseline runs three candidate worlds from a comparable start. Variant runners can add structured routing, evidence review, extra cells, replicas, or bounded child missions before the comparative gate.", runtime: "All twelve variant runners are connected to the mission/supervisor path with variant-specific completion gates.", limit: "R3 predates the wiring corrections: all twelve missions escalated and none merged. The corrected paths have not yet completed a post-correction end-to-end qualification.", status: "12 RUNNERS WIRED · QUALIFICATION PENDING", color: "purple", implementation: "partial", integration: "wired", evidence: "unit-tested", statusNote: "All twelve variant runners are connected to the mission/supervisor path. R3 (36 agents, 12 missions) ran before those corrections and ended 12/12 ESCALATE, 0 merge; it does not qualify the corrected paths. Keep Trinity partial until a post-correction campaign verifies variant outputs, effective routes, receipts, gates, and promotion." },
  { slug: "a-team", name: "A-Team", index: "02", summary: "Specialists, handoffs and integration.", principle: "A mission is divided across domain specialists. Explicit handoffs move work between them, then an integration step assembles the result.", runtime: "Dedicated dispatch and coordination paths for domain work, handoffs and integration.", limit: "Pareto arbitration only applies where the A-Team evaluator invokes it.", status: "WIRED · SPECIALIZED WORKERS", color: "orange", implementation: "partial", integration: "wired", evidence: "unit-tested", statusNote: "Graph and specialist-assignment tests are documented. Semantic decomposition and a complete mission E2E remain open." },
  { slug: "biocenose", name: "Biocenosis", index: "03", summary: "Community evaluation and explicit ballots.", principle: "A community of roles contributes evidence and evaluations. Consensus can account for confidence and quorum, while the evidence barrier remains in the decision path.", runtime: "Community preparation, evaluation and explicit jury ballots; consensus services are available.", limit: "A juror must provide an explicit ballot. Profile capabilities are not all activated automatically. In the latest 12-mission live SQLite campaign, nine cycles blocked, three completed, and none met all mission criteria or received verified promotion.", status: "PARTIAL · LIVE CAMPAIGN RECORDED", color: "green", implementation: "partial", integration: "wired", evidence: "integration-tested", statusNote: "A 2026-10-04 SQLite campaign persisted 766 telemetry and 549 community events with no reported loss. Nine cycles blocked; three completed cycles were not three successful missions. Zero missions met every criterion with verified promotion. All members used one local model, so independent fault domains were not demonstrated." },
  { slug: "holobionte", name: "Holobiont", index: "04", summary: "A host, symbionts and lifecycle contracts.", principle: "An orchestrating host composes specialist symbionts around mission capabilities, governs their lifecycle, and constrains execution through resource and capability contracts.", runtime: "The topology runtime provisions host and symbiont state, plans bounded cycles, executes supplied capabilities, and records lifecycle and health state.", limit: "Automatic immune behavior is proposed; host veto and drift evaluation are primitives without a guaranteed call in every path.", status: "WIRED · IMMUNITY PARTIAL", color: "orange", implementation: "experimental", integration: "wired", evidence: "unit-tested", statusNote: "A bounded lifecycle runtime is present. The canonical product contract still treats the topology as experimental and leaves veto acceptance open." },
  { slug: "syncytium", name: "Syncytium", index: "05", summary: "Persisted shared-state sessions and invariant-aware operations.", principle: "The runtime persists versioned shared sessions, applies supported CRDT operations, and evaluates coherence. It does not guarantee convergence across independently writing distributed replicas.", runtime: "Persisted topology sessions expose snapshots, CRDT operations, speculative branches, invariant and conflict inspection, history, and consistency evaluation.", limit: "Distributed multi-writer replication and convergence under concurrent updates remain incomplete; local session operations do not guarantee distributed consistency.", status: "WIRED · PARTIAL SHARED STATE", color: "blue", implementation: "partial", integration: "wired", evidence: "unit-tested", statusNote: "GenOS has persisted sessions and callable shared-state operations. The product contract remains partial while multi-writer convergence and its integration evidence are open." },
  { slug: "rhizome", name: "Rhizome", index: "06", summary: "Persisted capability graphs, bounded routing and local traces.", principle: "A revisioned capability graph retains local traces, ranks eligible multi-hop routes under the selected variant policy, and can admit graph changes through explicit evidence gates.", runtime: "The topology session exposes bounded route planning, deterministic scoring, direct-member lookup, trace operations and graph-growth services.", limit: "A selected route does not start its provider. Growth requires an eligible adapter and evidence; autonomous mission integration and end-to-end promotion remain experimental.", status: "EXPERIMENTAL · ROUTING TOOLS WIRED", color: "green", implementation: "experimental", integration: "wired", evidence: "unit-tested", statusNote: "GenOS exposes route planning through the topology-session operation and implements bounded graph search. The topology remains experimental because mission-level integration, provider execution and end-to-end growth evidence are still incomplete." },
  { slug: "metapopulation", name: "Metapopulation", index: "07", summary: "Regional populations, verified migration and recovery.", principle: "Semi-independent demes keep local state and exchange typed propagules through directed corridors; each receiver validates transfers locally.", runtime: "Bounded regional cycles observe demes, evaluate migration utility and corridor policy, verify receiver outcomes, and can start classic_patch recolonization trials.", limit: "Migration requires configured enablement and an adaptive signal. Rescue needs a fitness/rollback adapter; a recolonized deme is active only after local viability proof.", status: "WIRED · VERIFIED MIGRATION", color: "purple", implementation: "experimental", integration: "wired", evidence: "unit-tested", statusNote: "Regional controls and receiver-verified migration are wired. The runtime bounds cycles and gates actions; evolutionary execution remains adapter-dependent." },
  { slug: "biome", name: "Biome", index: "08", summary: "Persisted niches, resource allocation and bounded variant cycles.", principle: "A persisted environment tracks niches, specialized populations, resources, and evidence; selected variant operations apply bounded changes to that session.", runtime: "Eleven bounded variant controllers are callable through session operations. The mission loop can observe, propose, constrain, act and verify using a simulated or explicitly authorized adapter.", limit: "A caller or scheduler must invoke each cycle. The complete autonomous ecology loop, worker placement, provider calls, and external fitness remain outside the topology.", status: "EXPERIMENTAL · BOUNDED VARIANT OPERATIONS", color: "orange", implementation: "experimental", integration: "wired", evidence: "unit-tested", statusNote: "Session operations and the bounded mission loop are present, but the product contract classifies Biome as experimental. Cycles are caller-invoked; autonomous ecology, worker placement and provider execution are not provided by the topology." },
];

export function getTopology(slug: string) {
  return topologies.find((topology) => topology.slug === slug);
}
