/**
 * Short, doc-grounded phases for the browser's explanatory simulations.
 * These are walkthroughs of a policy contract, not calls into the GenOS runtime.
 */
const flows: Record<string, Record<string, string[]>> = {
  trinity: {
    controlled: ["Même snapshot en lecture seule", "Direct · structuré · falsification", "Trois dossiers scellés", "Preuves · contraintes · comparaison"],
    heterogeneous: ["Même snapshot", "Trois stratégies distinctes", "Préférence fournisseurs si disponibles", "Diversité constatée puis comparaison"],
    adversarial: ["Trois mondes scellés", "Dossiers terminés", "Cross-examen des claims", "Vérifications · gate de preuve"],
    counterfactual: ["Monde de référence", "Intervention favorable", "Intervention défavorable", "Comparer les deltas conditionnels"],
    factorial: ["Définir stratégies × modèles × outils", "Allouer les cellules isolées", "Exécuter via adaptateur requis", "Lire la grille de résultats"],
    pareto: ["Mesurer le vecteur de preuves", "Éliminer contraintes dures", "Construire le front de Pareto", "Garder les solutions non dominées"],
    jury: ["Préparer les dossiers admissibles", "Anonymiser les candidats", "Avis aveugle après comparaison", "Avis consultatif · gate inchangé"],
    recursive: ["Mission parente", "Isoler le sous-problème", "Sous-Trinity sous budget/profondeur", "Retour vérifié avec provenance"],
    adaptive: ["Lancer les trois mondes", "Mesurer l’incertitude vérifiée", "Répartir le budget de continuation", "Les trois mondes continuent"],
    temporal: ["Horizon court · effet immédiat", "Horizon moyen · intégration", "Horizon long · maintenance", "Comparer réversibilité et valeur"],
    oracular: ["L’oracle prédit le meilleur processus", "Les mondes candidats travaillent", "Résultat externe vérifié", "Noter la prédiction (Brier/log-loss)"],
    exploratory: ["Approches directes et structurées", "Produire des options distinctes", "Archiver nouveauté et qualité", "Comparer sans convergence précoce"],
  },
  "a-team": {
    expert_committee: ["Former des profils non redondants", "Analyses spécialisées en parallèle", "Votes avec preuves", "Consensus et dissensus conservé"],
    pipeline: ["Étape A · contrat d’entrée", "Handoff typé A → B", "Étape B → C · retries bornés", "Sortie validée / reprise"],
    project_dag: ["Construire le WorkGraph", "Exécuter les branches prêtes", "Joindre selon dépendances", "Invalider les nœuds affectés"],
    cross_functional_pod: ["Couvrir les compétences de bout en bout", "Attribuer un propriétaire par artefact", "Design · build · test planifiés", "Mesurer l’autonomie déclarée"],
    boundary_spanner: ["Détecter l’interface déclarée", "Contrat sémantique versionné", "Traduire si requis", "Valider schémas et provenance"],
    matrix_team: ["Identifier l’axe produit et fonction", "Résoudre par type de décision", "Valider les deux autorités", "Écriture CAS à brancher"],
    tiger_team: ["Fixer mandat, budget et durée", "Garder autorise/interdit", "Refuser action hors périmètre", "Arrêt à expiration du mandat"],
    incident_command: ["Commander · opérations · planification", "Définir période et objectifs", "Réduire les événements SITREP", "Cadence automatique non démarrée"],
    multiteam: ["Composer les sous-équipes", "Contrats et budgets locaux", "Conseil d’intégration", "Exécution via adaptateur vérifié"],
    adaptive: ["Comparer besoins et capacités", "Proposer le changement d’équipe", "Gate : preuve · budget · stabilité", "Recrutement effectif à brancher"],
    relay_team: ["Un propriétaire détient le contexte", "Paquet séquentiel versionné", "Accusé du receveur", "Rollback si transfert invalide"],
  },
  biocenose: {
    epistemic_jury: ["Engagements individuels scellés", "Révélation après tous les engagements", "Revue spécialisée", "Agrégation centrée sur les preuves"],
    delphi_community: ["Avis anonymes · tour 1", "Retour anonyme agrégé", "Tour 2 minimum", "Distribution et minorités conservées"],
    adversarial_assembly: ["Engagements scellés", "Reviewer adversarial requis", "Contre-exemples vérifiés d’abord", "Veto sur réfutation"],
    forecasting_crowd: ["Produire des prévisions probabilistes", "Revue des prévisions", "Attendre vérité résolue", "Agrégation calibrée si poids fournis"],
    argumentation_community: ["Publier des claims", "Lier SUPPORT / ATTACK / REFUTE", "Explorer le graphe d’arguments", "Validité logique non calculée"],
    polycentric_council: ["Former les groupes spécialisés", "Évaluations locales", "Agrégation hiérarchique", "Dissensus par groupe conservé"],
    byzantine_resilient_community: ["Contrôler provenance", "Placer les signaux douteux en quarantaine", "Vérifier les éléments", "Veto sur contre-exemple"],
    minority_preserving_jury: ["Engagements scellés", "Revue spécialisée", "Agrégation fondée sur preuve", "Tout dissensus conservé"],
    representative_community: ["Composer le panel représentatif", "Collecter évaluations pondérées", "Agrégation en distribution", "Minorités conservées · partiel"],
    persistent_community: ["Restaurer l’historique", "Délibérer au tour courant", "Agrégation calibrée", "Révisions append-only · partiel"],
    human_ai_deliberation: ["Engagements humains et IA", "Revue conjointe", "Jugement humain requis", "Dissensus conservé"],
    hybrid_oracle_community: ["Router vers vérificateur déterministe", "Appliquer contrôle externe", "Agrégation oracle d’abord", "Contre-exemple peut bloquer"],
  },
  holobionte: {
    organelle: ["Préserver l’identité du noyau hôte", "Admettre sur contrat et preuve", "Essai requis", "Remplacement du noyau soumis à approbation"],
    "adaptive-microbiome": ["Mesurer le besoin de capacité", "Acquisition horizontale permise par contrat", "Pondérer les ressources par contribution", "Succession après preuve"],
    "immune-critical": ["Définir modèle de menace", "Bloquer signal inconnu", "Vérificateur indépendant requis", "Échec immunitaire arrête le cycle"],
    "local-first": ["Préférer le moteur local", "Limiter l’accès aux données", "Allouer le budget local d’abord", "Compatibilité privacy avant succession"],
    regenerative: ["Réserver les ressources de reprise", "Détecter le besoin de récupération", "Évaluer la preuve de restauration", "Succession vérifiée (plan, pas action auto)"],
    "cloud-core/edge-symbionts": ["Hôte préféré cloud", "Symbiotes placés edge", "Exiger lease et provenance", "Exécution edge dépend d’un adaptateur"],
    "edge-core/cloud-symbionts": ["Hôte local / edge", "Minimiser et rédiger les entrées", "Proxy de capacités cloud", "Jamais hériter les périphériques"],
    "memory-rich": ["Admettre sur contrat et preuve", "Lire stores sémantique / épisodique / procédural", "Exiger provenance mémoire", "Succession préserve les preuves"],
    "competitive-partner": ["Définir la capacité partenaire", "Essais à budget égal", "Vérifier les résultats", "Choix du gagnant exige une preuve"],
    procedural: ["Détecter une lacune de capacité", "Recrutement contractuel proposé", "Exécuter une procédure bornée", "Arrêt après mission"],
    tool: ["Admettre un spécialiste outil", "Valider manifeste et schéma", "Sandbox lié au contrat", "Arrêt selon conditions de mission"],
    "cloud-core/edge-sync": ["Hôte préféré cloud", "Recevoir état edge asynchrone", "Vérifier provenance", "Rejeter état périmé"],
  },
  syncytium: {
    hard: ["Écriture sur état répliqué", "Tous les abonnés reçoivent", "Invariant / autorité contrôlés", "Rollback ou coordination; sinon arrêt"],
    soft: ["Émettre delta sélectif", "Fusionner les changements", "Réconcilier les conflits", "Arrêt si conflit irrécupérable"],
    code: ["Modifier l’arbre partagé", "Répliquer aux abonnés concernés", "Checkpoint et replay tests", "Arrêt si build/import échoue"],
    document: ["Éditer le document", "Répliquer à tous les abonnés", "Rejouer la séquence causale", "Arrêt si trou causal"],
    graph: ["Appliquer delta de graphe", "Répliquer sélectivement", "Reconstruire projection / retirer arête", "Arrêt si cycle ou arête pendante"],
    transactional: ["Vérifier les préconditions", "Appliquer transaction sélective", "Rollback transaction si échec", "Arrêt sur ressource ou précondition"],
    epistemic: ["Appliquer un fait avec provenance", "Répliquer sélectivement", "Préserver la contre-preuve", "Arrêt si provenance absente"],
    blackboard: ["Publier sur tableau commun", "Répliquer sélectivement", "Conserver historique d’événements", "Arrêt si question critique sans réponse"],
    localFirst: ["Écrire sur le replica local", "Mettre en file pendant partition", "Réconcilier à la reconnexion", "Arrêt si budget de partition dépassé"],
    speculative: ["Créer une branche isolée", "Essayer les changements", "Jeter ou promouvoir après validation", "Gate de promotion requis"],
    hierarchical: ["Modifier l’état régional", "Répliquer à la frontière", "Réconcilier parent et enfant", "Arrêt si invariant de frontière critique"],
    realtimeControl: ["Lire signal et delta", "Appliquer contrôle réflexe", "Arrêter puis réparer", "Arrêt sur signal de sûreté"],
    humanAi: ["Proposer une mutation attribuée", "Répliquer sélectivement", "Pause / revue ou undo attribué", "Arrêt si approbation / consentement requis"],
  },
  rhizome: {
    exploratory: ["Scout prioritaire", "Explorer jusqu’à 6 sauts", "Traces à forte température", "Stabilité sur 3 ticks"],
    routing: ["Demande de capacité", "Sélection directe parmi les membres composés", "Appliquer poids et limites du variant", "Aucun parcours multi-hop automatique"],
    growth: ["Repérer le besoin", "Seuil de croissance bas", "Réserver 50 % au budget de croissance", "Admission à vérifier avant activation"],
    resilient: ["Préparer des alternatives disjointes", "Jusqu’à 4 routes configurées", "Réserver 40 % au secours", "Recalcul sur opération explicite"],
    sparse: ["Plafonner densité à 0,3", "Limiter à 5 sauts", "Garder une alternative", "Pruning sensible au budget"],
    persistent: ["Ouvrir session persistante", "Sélectionner membre par capacité", "Enregistrer traces/session", "Réparer selon opération explicite"],
    ephemeral: ["Ouvrir session de mission", "Routes courtes (≤6 sauts)", "Décroissance rapide des traces", "Ne pas persister la session"],
    small_world: ["Utiliser hubs observés", "Préférer chemins courts (≤3 sauts)", "Pénaliser hubs points d’articulation", "Ne pas créer de raccourci sans admission"],
    private: ["Limiter au domaine de confiance", "Route privée (≤8 sauts)", "Quarantaine en cas de risque", "Seuil de confiance 0,7"],
    cross_representation: ["Détecter représentation source/cible", "Exiger un pont vérifié", "Compatibilité minimale 0,6", "Sélection directe · pas de multi-hop auto"],
    procedural: ["Seed déterministe", "Pipeline jusqu’à 6 étapes", "Exiger preuve locale et essais", "Validation causale requise"],
    self_healing: ["Détecter échec de route", "Chercher alternatives disjointes", "Reconfigurer/réparer (≤5 tours)", "Mécanisme borné, pas autonomie illimitée"],
  },
  metapopulation: {
    balanced: ["Dèmes régionaux", "Migrer des profils complémentaires", "Préserver diversité", "Quorum configuré à 0,5"],
    resilient: ["Repérer dème à risque", "Préparer migration de secours", "Préserver diversité", "Quorum 0,6 · récupération appelée explicitement"],
    exploratory: ["Maintenir plusieurs régions", "Migrer la nouveauté", "Préserver diversité", "Quorum 0,4"],
    conservative: ["Évaluer contre-exemples", "Migration de contre-preuve", "Ne pas préserver diversité par défaut", "Quorum 0,7"],
    classic_patch: ["Patches reliés small-world", "Migration fondatrice", "Recolonisation prévue", "Quorum 0,5 · plan partiel"],
    island_search: ["Îles reliées en anneau", "Recherche locale indépendante", "Migration périodique des élites", "Quorum 0,5"],
    heterogeneous_islands: ["Îles connectées", "Stratégies / fournisseurs / lignées différents", "Migration complémentaire + culture", "Quorum 0,5"],
    source_sink: ["Régions source et puits", "Corridors dirigés", "Réserve source 20 %", "Secours selon quorum 0,5"],
    rescue_network: ["Relier régions en small-world", "Prioriser dèmes à risque", "Plan SLA 5 min", "Quorum 0,6 · action explicite"],
    stepping_stone: ["Corridors par relais", "Migration culturelle rare", "Conserver diversité et localité", "Quorum 0,45"],
    anti_synchrony: ["Détecter risque d’échec corrélé", "Ouvrir coupe-feu / réordonner corridors", "Maintenir diversité ≥0,3", "Planifier extinction seulement avec couverture"],
    federated: ["Garder les agents souverains", "Vérifier minimisation et attestation", "Échanger propagules vérifiés", "Corridors hiérarchiques · quorum 0,5"],
    ephemeral_patch: ["Patches temporaires", "Rattacher rapidement les ressources", "Migration des élites", "Cryptobiose déclarée · plan partiel"],
    persistent: ["Résidents persistants", "Relier par small-world", "Garder mémoire régionale", "Décroissance mémoire 0,01"],
    evolutionary: ["Populations régionales", "Évolution et reproduction locales", "Spéciation possible", "Anneau · quorum 0,5 · partiel"],
    cultural: ["Garder agents résidents", "Transférer les artefacts seulement", "Tracer phylogénie culturelle", "Corridors small-world"],
  },
  biome: {
    resource: ["Observer demandes et stocks", "Allouer tokens / coût / quota / CPU / GPU / RAM", "Réserver les minima de niche", "Journaliser rendement pour le cycle suivant"],
    exploration: ["Observer patches inconnus", "Foraging selon curiosité/stagnation", "Archiver patch et preuves", "Transfert proposé au worker"],
    quality_diversity: ["Descripteurs et opérateurs fournis", "Cellules / niches · élite locale", "Nouveauté et compétition locale", "Enfants mutation/croisement · fitness externe"],
    successional: ["Pioneer colonise", "Gate preuve + productivité", "Specialist exploite", "Stabilizer après mesure de stabilité"],
    resilience: ["Mesurer redondance et keystone", "Protéger refuges", "Confirmer extinction avec preuve", "Financer recolonisation sur réserve"],
    persistent: ["Reprendre persistence_key", "Restaurer saisons et mémoire", "Appliquer rétention / decay", "Persister le nouvel état"],
    open_ended: ["Générer environnement enfant borné", "Archiver la nouveauté", "Évaluer utilité/coût avec vérificateur", "Suspendre après 5 cycles stériles"],
    adversarial: ["Lier attaquant et défenseur", "Compter défis et mitigations", "Archiver références d’exploits", "Rejeter payloads/exécutions réelles"],
    knowledge: ["Traiter sources comme niches", "Évaluer fraîcheur/crédibilité/contradiction", "Citer provenance", "Polliniser sources d’un thème"],
    compute: ["Observer quotas et ressources matérielles", "Comparer fournisseurs faisables", "Recommander coût/latence/énergie", "Ne déplace pas le worker"],
    multi_scale: ["Mesurer individus", "Agrégats population", "Agrégats écosystème", "Renvoyer contraintes vers le bas"],
  },
};

const fallback: Record<string, string[]> = {
  trinity: ["Trois mondes isolés", "Appliquer l’axe du variant", "Comparer les preuves", "Gate avant toute promotion"],
  "a-team": ["Préparer le dispatch", "Répartir les rôles", "Handoffs et coordination", "Intégrer les livrables"],
  biocenose: ["Former la communauté", "Engagements et divulgation", "Évaluer selon la politique", "Conserver preuves et dissensus"],
  holobionte: ["Évaluer la capacité requise", "Préparer hôte et symbiotes", "Appliquer le contrat du variant", "Vérifier avant transition"],
  syncytium: ["Produire delta d’état", "Réplication selon politique", "Réparer ou réconcilier", "Vérifier invariant / arrêt"],
  rhizome: ["Besoin de capacité", "Sélection sur membres composés", "Dépôt ou calcul de traces", "Mutation de session auditée"],
  metapopulation: ["Décrire dèmes et corridors", "Calculer quorum / migration", "Préparer le plan régional", "Appliquer seulement sur appel explicite"],
  biome: ["Observer l’environnement", "Proposer et contraindre", "Action bornée", "Vérifier et journaliser"],
};

export function getVariantSimulationSteps(family: string, variant: string): string[] {
  return flows[family]?.[variant] ?? fallback[family] ?? ["Préparer la mission", "Appliquer la politique", "Vérifier les preuves"];
}
