/**
 * Short, doc-grounded phases for the browser's explanatory simulations.
 * These are walkthroughs of a policy contract, not calls into the GenOS runtime.
 */
const flows: Record<string, Record<string, string[]>> = {
  trinity: {
    controlled: ["Create one read-only snapshot", "Run direct · structured · falsification", "Seal three independent dossiers", "Compare evidence and constraints"],
    heterogeneous: ["Create one shared snapshot", "Keep three strategies distinct", "Prefer provider diversity when available", "Record achieved diversity, then compare"],
    adversarial: ["Start three sealed attempts", "Finish or fail each attempt", "Cross-examine claims after completion", "Apply counterexample and evidence gates"],
    counterfactual: ["Set the baseline condition", "Describe a favorable intervention", "Describe an unfavorable intervention", "Compare conditional outcomes"],
    factorial: ["Variant recognized by the catalog", "Runtime rejects before launch", "No experiment cells are allocated", "Use an implemented strategy instead"],
    pareto: ["Collect comparable evidence vectors", "Remove hard-constraint failures", "Find non-dominated candidates", "Keep the Pareto set behind the gate"],
    jury: ["Complete the independent reports", "Cross-examine and compare", "Anonymize candidates for the jury", "Advisory only · evidence gate unchanged"],
    recursive: ["Variant recognized by the catalog", "Runtime rejects before launch", "No sub-Trinity is created", "Use an implemented strategy instead"],
    adaptive: ["Start exactly three worlds", "Read verified uncertainty signals", "Weight the continuation pool", "All three worlds continue"],
    temporal: ["Compare short-term outcomes", "Compare integration horizon", "Compare maintenance horizon", "Review reversibility and value"],
    oracular: ["Variant recognized by the catalog", "Runtime rejects before launch", "No oracle prediction is scored", "Use an implemented strategy instead"],
    exploratory: ["Keep three candidate approaches open", "Produce distinct solution options", "Record novelty and evidence", "Compare without early convergence"],
  },
  "a-team": {
    expert_committee: ["Set one shared evidence contract", "Collect independent specialist reports", "Apply explicit consensus / quorum", "Integrate after specialist review"],
    pipeline: ["Validate the input contract", "Pass a typed handoff to verification", "Retry locally within the step budget", "Integrate only an accepted output"],
    project_dag: ["Validate an acyclic Work Graph", "Run ready branches in parallel", "Wait for every required dependency", "Promote evidence before unblocking consumers"],
    cross_functional_pod: ["Declare required skills and owners", "Assign one owner per artifact", "Record cross-domain consultations", "Use the declared sync cadence"],
    boundary_spanner: ["Declare the service boundary", "Assign ownership of its interface", "Translate only through the contract", "Validate schema and provenance"],
    matrix_team: ["Declare product and functional axes", "Route by decision type", "Request cross-axis consultation", "CAS authority checks remain partial"],
    tiger_team: ["Set mandate, scope, budget, and duration", "Investigate only allowed work", "Reject out-of-scope actions", "Stop when the mandate expires"],
    incident_command: ["Assign command and incident roles", "Set objectives for an operational period", "Prepare SITREP and coordination updates", "Automatic cadence is not started here"],
    multiteam: ["Validate explicit subteam contracts", "Build the program dependency graph", "Wait for verified incoming contracts", "Execution requires a supplied team adapter"],
    adaptive: ["Assess current needs and capability gaps", "Propose reassignment or recruitment", "Gate on evidence · budget · stability", "Proposal does not apply the change"],
    relay_team: ["One owner holds the context", "Versioned sequential package", "Receiver acknowledges", "Rollback on invalid transfer"],
  },
  biocenose: {
    epistemic_jury: ["Seal each member's initial judgment", "Reveal only after all active members commit", "Route claims to specialist reviewers", "Aggregate explicit evidence and ballots"],
    delphi_community: ["Collect anonymous round-zero estimates", "Return an anonymous aggregate and reasons", "Run a second round or more", "Stop by spread · round limit · budget"],
    adversarial_assembly: ["Seal initial commitments", "Route claims to an adversarial reviewer", "Check counterexamples and evidence", "Verified refutation can block"],
    forecasting_crowd: ["Collect probabilistic forecasts", "Wait for a resolved external outcome", "Score with the supplied oracle reference", "Weight only with calibration and independence data"],
    argumentation_community: ["Publish normalized claims", "Persist SUPPORT / ATTACK / REFUTE edges", "Keep source and dissent links", "The graph does not prove logical validity"],
    polycentric_council: ["Local subcommunity model · partial", "Preserve local position distributions", "Coordinate through a parent council", "Subcommunity execution is not integrated"],
    byzantine_resilient_community: ["Check signal provenance", "Filter or quarantine selected members", "Route to declared evidence verifiers", "Quarantine is not a BFT guarantee"],
    minority_preserving_jury: ["Seal commitments and reveal together", "Review claims and evidence", "Append every dissent to the judgment", "Verified critical dissent can veto promotion"],
    representative_community: ["Representative sampling · partial", "Collect declared panel judgments", "Keep a weighted distribution", "Sampling mechanism is not implemented"],
    persistent_community: ["Restore the persisted session", "Review the current round", "Append belief and dissent revisions", "Inter-mission reputation remains partial"],
    human_ai_deliberation: ["Collect human and AI commitments", "Run joint review", "Require human judgment", "Preserve dissent"],
    hybrid_oracle_community: ["Route to a deterministic verifier", "Apply external checks", "Aggregate oracle results first", "A counterexample can block"],
  },
  holobionte: {
    organelle: ["Keep host identity and authority central", "Admit a core symbiont by contract", "Require a bounded trial", "Host approval gates core replacement"],
    "adaptive-microbiome": ["Observe a capability gap", "Propose a contracted symbiont", "Evaluate contribution and evidence", "Succession remains an explicit plan"],
    "immune-critical": ["Declare the threat model", "Hold unknown or suspicious signals", "Route to an independent verifier", "Host veto and escalation remain explicit"],
    "local-first": ["Check for a local executor", "Keep inputs within the local boundary", "Reserve budget under the host", "Placement is not guaranteed by the variant name"],
    regenerative: ["Detect a failed or lost resident", "Prepare a recovery reserve", "Evaluate restoration evidence", "Host reviews the plan · no automatic repair"],
    "cloud-core/edge-symbionts": ["Keep coordination at the cloud host", "Place capability near edge data", "Require an edge lease and provenance", "Execution needs a supplied adapter"],
    "edge-core/cloud-symbionts": ["Keep authority at the edge host", "Minimize and redact outbound inputs", "Proxy only contracted cloud capabilities", "Do not inherit cloud peripherals"],
    "memory-rich": ["Declare persistent memory needs", "Read semantic · episodic · procedural stores", "Require provenance and conflict handling", "Memory lifecycle is still partial"],
    "competitive-partner": ["Define equivalent capability contracts", "Compare candidates under equal budgets", "Verify contribution and cost", "Host gates any lasting assignment"],
    procedural: ["Declare the capability gap", "Propose an ordered procedure", "Run only bounded contracted steps", "Stop at the mission condition"],
    tool: ["Declare the external capability", "Check manifest and input schema", "Bind the tool to a sandbox lease", "Stop at contract conditions"],
    "cloud-core/edge-sync": ["Keep control at the cloud host", "Queue asynchronous edge events", "Check provenance and freshness", "Reject stale state before merge"],
  },
  syncytium: {
    hard: ["Declare a strict invariant", "Check write authority and preconditions", "Coordinate when merge is unsafe", "Reject invalid state · design concept"],
    soft: ["Allow local replicas to diverge", "Exchange supported deltas", "Merge under protocol assumptions", "Reconcile conflicts · convergence is conditional"],
    code: ["Branch from a versioned code base", "Collect isolated patches", "Merge and replay build checks", "Reject failed imports or tests · target model"],
    document: ["Create a shared text state", "Collect attributed section edits", "Reconcile causal order", "Semantic agreement is a separate check"],
    graph: ["Propose node or edge deltas", "Merge the graph projection", "Check cycles and dangling edges", "Repair or reject the invalid graph"],
    transactional: ["Check versions and preconditions", "Apply writes as one transaction", "Commit all or roll back", "Isolation and atomicity are target guarantees"],
    epistemic: ["Add a fact with source and confidence", "Attach contradictory evidence", "Preserve both claims in the fact map", "Reject unsupported or unattributed updates"],
    blackboard: ["Publish questions and evidence", "Let subscribers post attributed entries", "Keep an append-only event history", "Do not close while a critical issue is open"],
    localFirst: ["Write to a local replica offline", "Queue deltas during partition", "Exchange causal context on reconnect", "Reconcile within the declared partition budget"],
    speculative: ["Fork an immutable baseline", "Keep assumptions in isolated branches", "Validate the candidate change", "Discard or propose promotion behind a gate"],
    hierarchical: ["Update child-region state", "Aggregate a parent summary", "Propagate constraints downward", "Check boundary invariants on reconciliation"],
    realtimeControl: ["Read a timestamped signal", "Propose a bounded control delta", "Check safety and latency limits", "Stop and repair on a safety signal · concept only"],
    humanAi: ["Record an attributed AI proposal", "Record a human edit in shared state", "Review or undo with attribution", "Require consent and authority checks"],
  },
  rhizome: {
    exploratory: ["Diagnose the capability gap", "Scout within declared depth and budget", "Follow and deposit local traces", "Stop when the frontier or budget is exhausted"],
    routing: ["Request a capability with cost and trust limits", "Search active edges with bounded BFS", "Rank candidate paths deterministically", "Return route evidence; host adapter runs the provider"],
    growth: ["Diagnose a versioned graph gap", "Plan a candidate and check reuse", "Apply budget, utility, and evidence gates", "Admit only with a verifier receipt"],
    resilient: ["Detect an unavailable route", "Find edge-disjoint alternatives", "Reduce reuse of the same fault domain", "Re-route through an explicit operation"],
    sparse: ["Keep the active graph low-density", "Enforce declared branch and hop caps", "Leave unadmitted links inactive", "Prune only within the maintenance budget"],
    persistent: ["Open a versioned persistent session", "Retain graph, traces, lineage, and bounded leases", "Update traces from local outcomes", "Expire leases and prune through explicit maintenance"],
    ephemeral: ["Open a mission-scoped graph", "Route within declared bounds", "Decay temporary traces", "Discard graph at close; retain only an optional summary fossil"],
    small_world: ["Use observed local hubs", "Prefer bounded paths through known edges", "Penalize articulation points", "Admit shortcuts only through graph-growth gates"],
    private: ["Scope the request to trusted domains", "Bind route proof to the security context", "Exclude or quarantine untrusted nodes", "Reject cross-domain paths without admission proof"],
    cross_representation: ["Identify source and target representations", "Require an admitted bridge adapter", "Check round-trip semantics or declared loss bounds", "Route within graph bounds and retain bridge evidence"],
    procedural: ["Declare typed ordered steps", "Validate each local transformation", "Require compatibility evidence between handoffs", "Apply causal validation before accepting output"],
    self_healing: ["Verify the route failure", "Find bounded edge-disjoint alternatives", "Reconfigure through explicit repair operations", "Stop after the configured repair bound"],
  },
  metapopulation: {
    balanced: ["Use regional demes", "Migrate complementary profiles", "Preserve diversity", "Set quorum to 0.5"],
    resilient: ["Identify at-risk deme", "Prepare fallback migration", "Preserve diversity", "Quorum 0.6 · call recovery explicitly"],
    exploratory: ["Maintain several regions", "Migrate novel candidates", "Preserve diversity", "Set quorum to 0.4"],
    conservative: ["Evaluate counterexamples", "Migrate counterevidence", "Do not preserve diversity by default", "Set quorum to 0.7"],
    classic_patch: ["Connect patches in a small world", "Migrate founders", "Plan recolonization", "Quorum 0.5 · partial plan"],
    island_search: ["Connect islands in a ring", "Run independent local search", "Periodically migrate elites", "Set quorum to 0.5"],
    heterogeneous_islands: ["Connect islands", "Vary strategies, providers, and lineages", "Migrate complementary candidates and culture", "Set quorum to 0.5"],
    source_sink: ["Define source and sink regions", "Use directed corridors", "Reserve 20% at the source", "Recover with quorum 0.5"],
    rescue_network: ["Connect regions as a small world", "Prioritize at-risk demes", "Set a 5-minute SLA plan", "Quorum 0.6 · explicit action"],
    stepping_stone: ["Use relay corridors", "Migrate culture rarely", "Preserve diversity and locality", "Set quorum to 0.45"],
    anti_synchrony: ["Detect correlated failure risk", "Open circuit breakers or reorder corridors", "Maintain diversity ≥0.3", "Plan extinction only with coverage"],
    federated: ["Keep agents sovereign", "Check minimization and attestation", "Exchange verified propagules", "Hierarchical corridors · quorum 0.5"],
    ephemeral_patch: ["Use temporary patches", "Reattach resources quickly", "Migrate elites", "Declared cryptobiosis · partial plan"],
    persistent: ["Keep resident groups", "Connect as a small world", "Retain regional memory", "Memory decay 0.01"],
    evolutionary: ["Use regional populations", "Evolve and reproduce locally", "Allow possible speciation", "Ring · quorum 0.5 · partial"],
    cultural: ["Keep agents resident", "Transfer artifacts only", "Track cultural phylogeny", "Use small-world corridors"],
  },
  biome: {
    resource: ["Observe demand and inventory", "Allocate tokens / cost / quota / CPU / GPU / RAM", "Reserve niche minimums", "Log yield for the next cycle"],
    exploration: ["Observe unknown patches", "Forage by curiosity and stagnation", "Archive patch and evidence", "Propose transfer to a worker"],
    quality_diversity: ["Use supplied descriptors and operators", "Create cells / niches · local elite", "Track novelty and local competition", "Mutation / crossover offspring · external fitness"],
    successional: ["Pioneer colonizes", "Gate on evidence + productivity", "Specialist exploits", "Stabilizer follows stability measurement"],
    resilience: ["Measure redundancy and keystones", "Protect refuges", "Confirm extinction with evidence", "Fund recolonization from reserve"],
    persistent: ["Resume persistence_key", "Restore seasons and memory", "Apply retention / decay", "Persist the new state"],
    open_ended: ["Generate a bounded child environment", "Archive novelty", "Evaluate utility / cost with a verifier", "Pause after 5 sterile cycles"],
    adversarial: ["Pair attacker and defender", "Count challenges and mitigations", "Archive exploit references", "Reject real payloads or executions"],
    knowledge: ["Treat sources as niches", "Evaluate freshness / credibility / contradiction", "Cite provenance", "Cross-pollinate sources by topic"],
    compute: ["Observe quotas and hardware resources", "Compare feasible providers", "Recommend cost / latency / energy", "Do not move the worker"],
    multi_scale: ["Measure individuals", "Aggregate the population", "Aggregate the ecosystem", "Propagate constraints downward"],
  },
};

const fallback: Record<string, string[]> = {
  trinity: ["Create three isolated worlds", "Apply the variant's approach", "Compare evidence", "Gate before promotion"],
  "a-team": ["Prepare dispatch", "Assign roles", "Coordinate handoffs", "Integrate deliverables"],
  biocenose: ["Form the community", "Collect commitments and reveal them", "Evaluate under policy", "Preserve evidence and dissent"],
  holobionte: ["Assess required capabilities", "Prepare host and symbionts", "Apply the variant contract", "Verify before transition"],
  syncytium: ["Produce a state delta", "Replicate under policy", "Repair or reconcile", "Verify invariant or stop"],
  rhizome: ["Identify capability need", "Search a versioned graph with bounded BFS", "Rank route candidates and update local traces", "Apply provider and evidence gates"],
  metapopulation: ["Define demes and corridors", "Calculate quorum and migration", "Prepare regional plan", "Apply only on explicit call"],
  biome: ["Observe the environment", "Propose and constrain", "Take bounded action", "Verify and log"],
};

export function getVariantSimulationSteps(family: string, variant: string): string[] {
  return flows[family]?.[variant] ?? fallback[family] ?? ["Prepare the mission", "Apply the policy", "Verify the evidence"];
}
