/**
 * Short, doc-grounded phases for the browser's explanatory simulations.
 * These are walkthroughs of a policy contract, not calls into the GenOS runtime.
 */
const flows: Record<string, Record<string, string[]>> = {
  trinity: {
    controlled: ["Create one read-only snapshot", "Run direct · structured · falsification", "Seal three independent dossiers", "Compare evidence and constraints"],
    heterogeneous: ["Create one shared snapshot", "Keep three strategies distinct", "Prefer provider diversity when available", "Record achieved diversity, then compare"],
    adversarial: ["Start three sealed attempts", "Finish or fail each attempt", "Cross-examine claims after completion", "Apply counterexample and evidence gates"],
    counterfactual: ["Set the baseline condition", "Describe a favorable intervention", "Describe an unfavorable intervention", "Compare conditional outcomes"],
    factorial: ["Variant recognized by the catalog", "Runtime rejects before launch", "No experiment cells are allocated", "Use an implemented strategy instead"],
    pareto: ["Collect comparable evidence vectors", "Remove hard-constraint failures", "Find non-dominated candidates", "Keep the Pareto set behind the gate"],
    jury: ["Complete the independent reports", "Cross-examine and compare", "Anonymize candidates for the jury", "Advisory only · evidence gate unchanged"],
    recursive: ["Variant recognized by the catalog", "Runtime rejects before launch", "No sub-Trinity is created", "Use an implemented strategy instead"],
    adaptive: ["Start exactly three worlds", "Read verified uncertainty signals", "Weight the continuation pool", "All three worlds continue"],
    temporal: ["Compare short-term outcomes", "Compare integration horizon", "Compare maintenance horizon", "Review reversibility and value"],
    oracular: ["Variant recognized by the catalog", "Runtime rejects before launch", "No oracle prediction is scored", "Use an implemented strategy instead"],
    exploratory: ["Keep three candidate approaches open", "Produce distinct solution options", "Record novelty and evidence", "Compare without early convergence"],
  },
  "a-team": {
    expert_committee: ["Set one shared evidence contract", "Collect independent specialist reports", "Apply explicit consensus / quorum", "Integrate after specialist review"],
    pipeline: ["Validate the input contract", "Pass a typed handoff to verification", "Retry locally within the step budget", "Integrate only an accepted output"],
    project_dag: ["Validate an acyclic Work Graph", "Run ready branches in parallel", "Wait for every required dependency", "Promote evidence before unblocking consumers"],
    cross_functional_pod: ["Declare required skills and owners", "Assign one owner per artifact", "Record cross-domain consultations", "Use the declared sync cadence"],
    boundary_spanner: ["Declare the service boundary", "Assign ownership of its interface", "Translate only through the contract", "Validate schema and provenance"],
    matrix_team: ["Declare product and functional axes", "Route by decision type", "Request cross-axis consultation", "CAS authority checks remain partial"],
    tiger_team: ["Set mandate, scope, budget, and duration", "Investigate only allowed work", "Reject out-of-scope actions", "Stop when the mandate expires"],
    incident_command: ["Assign command and incident roles", "Set objectives for an operational period", "Prepare SITREP and coordination updates", "Automatic cadence is not started here"],
    multiteam: ["Validate explicit subteam contracts", "Build the program dependency graph", "Wait for verified incoming contracts", "Execution requires a supplied team adapter"],
    adaptive: ["Assess current needs and capability gaps", "Propose reassignment or recruitment", "Gate on evidence · budget · stability", "Proposal does not apply the change"],
    relay_team: ["One owner holds the context", "Versioned sequential package", "Receiver acknowledges", "Rollback on invalid transfer"],
  },
  biocenose: {
    epistemic_jury: ["Seal individual commitments", "Reveal after all commitments", "Run specialist review", "Aggregate around evidence"],
    delphi_community: ["Anonymous opinions · round 1", "Return anonymous aggregate", "Run at least round 2", "Preserve distribution and minorities"],
    adversarial_assembly: ["Seal commitments", "Require an adversarial reviewer", "Verify counterexamples first", "Allow veto on refutation"],
    forecasting_crowd: ["Produce probabilistic forecasts", "Review forecasts", "Wait for resolved ground truth", "Calibrate aggregation when weights are supplied"],
    argumentation_community: ["Publish claims", "Link SUPPORT / ATTACK / REFUTE", "Explore the argument graph", "Logical validity is not computed"],
    polycentric_council: ["Form specialist groups", "Run local evaluations", "Aggregate hierarchically", "Preserve dissent by group"],
    byzantine_resilient_community: ["Check provenance", "Quarantine suspicious signals", "Verify evidence", "Allow veto on counterexample"],
    minority_preserving_jury: ["Seal commitments", "Run specialist review", "Aggregate based on evidence", "Preserve all dissent"],
    representative_community: ["Compose a representative panel", "Collect weighted evaluations", "Aggregate as a distribution", "Preserve minorities · partial"],
    persistent_community: ["Restore history", "Deliberate on the current round", "Calibrate aggregation", "Append-only revisions · partial"],
    human_ai_deliberation: ["Collect human and AI commitments", "Run joint review", "Require human judgment", "Preserve dissent"],
    hybrid_oracle_community: ["Route to a deterministic verifier", "Apply external checks", "Aggregate oracle results first", "A counterexample can block"],
  },
  holobionte: {
    organelle: ["Preserve host core identity", "Admit by contract and evidence", "Require a trial", "Require approval to replace the core"],
    "adaptive-microbiome": ["Measure capability needs", "Allow contract-based horizontal acquisition", "Weight resources by contribution", "Succession follows evidence"],
    "immune-critical": ["Define a threat model", "Block unknown signals", "Require an independent verifier", "Immune failure stops the cycle"],
    "local-first": ["Prefer the local engine", "Limit data access", "Allocate local budget first", "Check privacy compatibility before succession"],
    regenerative: ["Reserve recovery resources", "Detect the need for recovery", "Evaluate restoration evidence", "Verify succession plan · no automatic action"],
    "cloud-core/edge-symbionts": ["Prefer a cloud host", "Place symbionts at the edge", "Require lease and provenance", "Edge execution needs an adapter"],
    "edge-core/cloud-symbionts": ["Use local / edge host", "Minimize and redact inputs", "Proxy cloud capabilities", "Never inherit peripherals"],
    "memory-rich": ["Admit by contract and evidence", "Read semantic / episodic / procedural stores", "Require memory provenance", "Succession preserves evidence"],
    "competitive-partner": ["Define partner capability", "Run trials with equal budgets", "Verify results", "Require evidence to select a winner"],
    procedural: ["Detect a capability gap", "Propose contract-based recruitment", "Run a bounded procedure", "Stop after the mission"],
    tool: ["Admit a tool specialist", "Validate manifest and schema", "Bind sandbox to the contract", "Stop under mission conditions"],
    "cloud-core/edge-sync": ["Prefer a cloud host", "Receive asynchronous edge state", "Check provenance", "Reject stale state"],
  },
  syncytium: {
    hard: ["Write to replicated state", "Notify all subscribers", "Check invariant and authority", "Rollback or coordinate; otherwise stop"],
    soft: ["Emit a selective delta", "Merge changes", "Reconcile conflicts", "Stop if the conflict cannot be recovered"],
    code: ["Edit the shared tree", "Replicate to affected subscribers", "Checkpoint and replay tests", "Stop if build or import fails"],
    document: ["Edit the document", "Replicate to all subscribers", "Replay the causal sequence", "Stop if a causal link is missing"],
    graph: ["Apply a graph delta", "Replicate selectively", "Rebuild projection or remove an edge", "Stop on cycle or dangling edge"],
    transactional: ["Check preconditions", "Apply a selective transaction", "Rollback the transaction on failure", "Stop on resource or precondition failure"],
    epistemic: ["Apply a fact with provenance", "Replicate selectively", "Preserve counterevidence", "Stop if provenance is missing"],
    blackboard: ["Publish to a shared board", "Replicate selectively", "Retain event history", "Stop if a critical question is unanswered"],
    localFirst: ["Write to the local replica", "Queue during partition", "Reconcile on reconnect", "Stop if the partition budget is exceeded"],
    speculative: ["Create an isolated branch", "Try the changes", "Discard or promote after validation", "Promotion gate required"],
    hierarchical: ["Update regional state", "Replicate across the boundary", "Reconcile parent and child", "Stop on a critical boundary invariant"],
    realtimeControl: ["Read signal and delta", "Apply reflex control", "Stop, then repair", "Stop on a safety signal"],
    humanAi: ["Propose an attributed mutation", "Replicate selectively", "Pause for review or attributed undo", "Stop if approval or consent is required"],
  },
  rhizome: {
    exploratory: ["Prioritize scouting", "Explore up to 6 hops", "Use high-temperature traces", "Check stability over 3 ticks"],
    routing: ["Request a capability", "Select directly from composed members", "Apply variant weights and limits", "No automatic multi-hop traversal"],
    growth: ["Identify the need", "Use a low growth threshold", "Reserve 50% for growth budget", "Verify admission before activation"],
    resilient: ["Prepare disjoint alternatives", "Configure up to 4 routes", "Reserve 40% for recovery", "Recalculate through an explicit operation"],
    sparse: ["Cap density at 0.3", "Limit to 5 hops", "Keep one alternative", "Make pruning budget-aware"],
    persistent: ["Open a persistent session", "Select a member by capability", "Record traces and session", "Repair through an explicit operation"],
    ephemeral: ["Open a mission session", "Use short routes (≤6 hops)", "Decay traces quickly", "Do not persist the session"],
    small_world: ["Use observed hubs", "Prefer short paths (≤3 hops)", "Penalize articulation hubs", "Do not add shortcuts without admission"],
    private: ["Stay within the trusted domain", "Use private routes (≤8 hops)", "Quarantine when risk is detected", "Set a 0.7 confidence threshold"],
    cross_representation: ["Detect source and target representations", "Require a verified bridge", "Set minimum compatibility to 0.6", "Select directly · no automatic multi-hop"],
    procedural: ["Use a deterministic seed", "Pipeline up to 6 steps", "Require local evidence and tests", "Require causal validation"],
    self_healing: ["Detect route failure", "Find disjoint alternatives", "Reconfigure or repair (≤5 rounds)", "Bound the mechanism; no unlimited autonomy"],
  },
  metapopulation: {
    balanced: ["Use regional demes", "Migrate complementary profiles", "Preserve diversity", "Set quorum to 0.5"],
    resilient: ["Identify at-risk deme", "Prepare fallback migration", "Preserve diversity", "Quorum 0.6 · call recovery explicitly"],
    exploratory: ["Maintain several regions", "Migrate novel candidates", "Preserve diversity", "Set quorum to 0.4"],
    conservative: ["Evaluate counterexamples", "Migrate counterevidence", "Do not preserve diversity by default", "Set quorum to 0.7"],
    classic_patch: ["Connect patches in a small world", "Migrate founders", "Plan recolonization", "Quorum 0.5 · partial plan"],
    island_search: ["Connect islands in a ring", "Run independent local search", "Periodically migrate elites", "Set quorum to 0.5"],
    heterogeneous_islands: ["Connect islands", "Vary strategies, providers, and lineages", "Migrate complementary candidates and culture", "Set quorum to 0.5"],
    source_sink: ["Define source and sink regions", "Use directed corridors", "Reserve 20% at the source", "Recover with quorum 0.5"],
    rescue_network: ["Connect regions as a small world", "Prioritize at-risk demes", "Set a 5-minute SLA plan", "Quorum 0.6 · explicit action"],
    stepping_stone: ["Use relay corridors", "Migrate culture rarely", "Preserve diversity and locality", "Set quorum to 0.45"],
    anti_synchrony: ["Detect correlated failure risk", "Open circuit breakers or reorder corridors", "Maintain diversity ≥0.3", "Plan extinction only with coverage"],
    federated: ["Keep agents sovereign", "Check minimization and attestation", "Exchange verified propagules", "Hierarchical corridors · quorum 0.5"],
    ephemeral_patch: ["Use temporary patches", "Reattach resources quickly", "Migrate elites", "Declared cryptobiosis · partial plan"],
    persistent: ["Keep resident groups", "Connect as a small world", "Retain regional memory", "Memory decay 0.01"],
    evolutionary: ["Use regional populations", "Evolve and reproduce locally", "Allow possible speciation", "Ring · quorum 0.5 · partial"],
    cultural: ["Keep agents resident", "Transfer artifacts only", "Track cultural phylogeny", "Use small-world corridors"],
  },
  biome: {
    resource: ["Observe demand and inventory", "Allocate tokens / cost / quota / CPU / GPU / RAM", "Reserve niche minimums", "Log yield for the next cycle"],
    exploration: ["Observe unknown patches", "Forage by curiosity and stagnation", "Archive patch and evidence", "Propose transfer to a worker"],
    quality_diversity: ["Use supplied descriptors and operators", "Create cells / niches · local elite", "Track novelty and local competition", "Mutation / crossover offspring · external fitness"],
    successional: ["Pioneer colonizes", "Gate on evidence + productivity", "Specialist exploits", "Stabilizer follows stability measurement"],
    resilience: ["Measure redundancy and keystones", "Protect refuges", "Confirm extinction with evidence", "Fund recolonization from reserve"],
    persistent: ["Resume persistence_key", "Restore seasons and memory", "Apply retention / decay", "Persist the new state"],
    open_ended: ["Generate a bounded child environment", "Archive novelty", "Evaluate utility / cost with a verifier", "Pause after 5 sterile cycles"],
    adversarial: ["Pair attacker and defender", "Count challenges and mitigations", "Archive exploit references", "Reject real payloads or executions"],
    knowledge: ["Treat sources as niches", "Evaluate freshness / credibility / contradiction", "Cite provenance", "Cross-pollinate sources by topic"],
    compute: ["Observe quotas and hardware resources", "Compare feasible providers", "Recommend cost / latency / energy", "Do not move the worker"],
    multi_scale: ["Measure individuals", "Aggregate the population", "Aggregate the ecosystem", "Propagate constraints downward"],
  },
};

const fallback: Record<string, string[]> = {
  trinity: ["Create three isolated worlds", "Apply the variant's approach", "Compare evidence", "Gate before promotion"],
  "a-team": ["Prepare dispatch", "Assign roles", "Coordinate handoffs", "Integrate deliverables"],
  biocenose: ["Form the community", "Collect commitments and reveal them", "Evaluate under policy", "Preserve evidence and dissent"],
  holobionte: ["Assess required capabilities", "Prepare host and symbionts", "Apply the variant contract", "Verify before transition"],
  syncytium: ["Produce a state delta", "Replicate under policy", "Repair or reconcile", "Verify invariant or stop"],
  rhizome: ["Identify capability need", "Select from composed members", "Deposit or calculate traces", "Audit session mutation"],
  metapopulation: ["Define demes and corridors", "Calculate quorum and migration", "Prepare regional plan", "Apply only on explicit call"],
  biome: ["Observe the environment", "Propose and constrain", "Take bounded action", "Verify and log"],
};

export function getVariantSimulationSteps(family: string, variant: string): string[] {
  return flows[family]?.[variant] ?? fallback[family] ?? ["Prepare the mission", "Apply the policy", "Verify the evidence"];
}
