import type { Metadata } from "next";
import { Eyebrow } from "@/components/eyebrow";

export const metadata: Metadata = { title: "Evidence and implementation status", description: "Review GenOS capability claims alongside implementation status, source documentation and known limitations.", alternates: { canonical: "/en/evidence" } };

const evidenceCommit = "v3";
const evidenceSource = `https://github.com/PISSARAW/GenOS/blob/${evidenceCommit}/`;

const rows = [
  { name: "Counterfactual snapshots", status: "IMPLEMENTED", tone: "implemented", body: "Snapshot, fork, diff and replay workflows are part of the runtime.", href: `${evidenceSource}docs/02-orchestration/git-agents.md`, source: "Agent Git snapshots and replay" },
  { name: "Eight topology modes", status: "WIRED", tone: "implemented", body: "Each mode has different services and capability limits; registration is not full feature parity.", href: `${evidenceSource}docs/02-orchestration/topologies-et-capacites.md`, source: "Topology capability contract" },
  { name: "Rhizome session routing", status: "CALLABLE · BOUNDED", tone: "partial", body: "The topology-session API plans bounded multi-hop routes over the persisted graph. Autonomous mission integration, provider execution and end-to-end growth remain experimental.", href: `${evidenceSource}backend/src/services/topologySessionTools.js`, source: "Rhizome topology-session route operation" },
  { name: "Continuous web perception loop", status: "PARTIAL", tone: "partial", body: "Web observation and foveation primitives exist; a complete observe–act–verify loop does not.", href: `${evidenceSource}README.md`, source: "Runtime limitations" },
  { name: "Morphogenesis topology plugins", status: "IMPLEMENTED · BOUNDED", tone: "partial", body: "Variant changes require a registered transition and satisfied conditions and evidence. Execution receipts are unverified traces; graph completion alone does not prove the mission or create a learning experience.", href: `${evidenceSource}docs/03-reference/plugins-topologies-morphogenese.md`, source: "Plugin contract and limits" },
  { name: "Historical mission morphology", status: "PROPOSAL ONLY", tone: "proposed", body: "The default mission path prepares a morphology proposal. executeMorphogenesisGraph: true opts into running that graph after evidence validation; its output is unverified and does not apply a transition or create an AgentGit commit. Morphogenesis V2 is an opt-in shadow preflight.", href: `${evidenceSource}backend/src/services/morphogenesis/morphogenesisRuntime.js`, source: "Historical morphology runtime" },
  { name: "Direct structural transitions", status: "ADAPTER-GATED", tone: "partial", body: "Spawn and retire require runtime adapters and rollback compensators. An explicit transition can persist a version commit before reporting success; graph preflight alone does not. Receipts distinguish in-memory restoration from external compensation.", href: `${evidenceSource}backend/src/services/morphogenesis/transitionEngineService.js`, source: "Transition engine and rollback contract" },
  { name: "HOX lineage differentiation", status: "CONNECTED · LIMITED PATH", tone: "partial", body: "The Rust biology orchestrator resolves cell lineage from expressed HOX state under energy and epigenetic constraints. It does not model morphogen diffusion and is not an automatic step in every backend mission.", href: `${evidenceSource}docs/01-concepts/biologie-computationnelle.md`, source: "Computational biology scope" },
  { name: "Regulation and Eureka events", status: "TRANSITION-GATED", tone: "partial", body: "A Eureka event is emitted only after an accepted regulation transition; ordinary process completion or shutdown does not count as evidence or reward.", href: `${evidenceSource}docs/adr/0111-regulation-cognitive-bornee-et-eureka.md`, source: "Bounded cognitive regulation" },
  { name: "Communication safeguards", status: "SCOPED · FAIL-CLOSED", tone: "partial", body: "Critical intents cannot bypass human confirmation through pre-scoped channels. Unknown reviewer relationships count as no demonstrated independence; global delivery is limited to active workers in the sender's tenant.", href: `${evidenceSource}backend/src/services/communication/communicationPolicyEngine.js`, source: "Communication decision policy" },
  { name: "Bounded verbal dialogue", status: "BUDGETED · TRANSACTIONAL", tone: "partial", body: "Turns require a participant speaker and stay within token, turn, and optional deadline limits. Required artifacts are checked at closure; exhausted sessions end unresolved.", href: `${evidenceSource}backend/src/services/communication/dialogueSessionService.js`, source: "Dialogue session contract" },
  { name: "Worker budget and tool lease", status: "NORMALIZED · RESTRICTIVE", tone: "partial", body: "Canonical token and time ceilings constrain worker missions. Zero-token procedural and formal types fail closed without a registered executor; an empty tool lease stays empty, and a supplied lease can only restrict role policy.", href: `${evidenceSource}docs/03-reference/types-de-workers.md`, source: "Worker budget and lease contract" },
  { name: "Measured worker methods", status: "10 KINDS · NARROW METHODS", tone: "partial", body: "Ten worker kinds have a deterministic method path. The 20-case local suite passes 10 cases without Lean and one more with Lean; nine remain unmeasured. AutoGen shares only two measured procedural cases, so broad rival parity is unproven.", href: `${evidenceSource}benchmarks/workers/README.md`, source: "Worker benchmark scope and limits" },
  { name: "Daemon event journal", status: "DURABLE · BEST-EFFORT INGESTION", tone: "partial", body: "The resident host polls an indexed event cursor every 500 ms and preserves it across restart. The production bridge reports emission only when the cheap update and journal write both succeed.", href: `${evidenceSource}docs/03-reference/types-de-daemons.md`, source: "Daemon event and restart contract" },
  { name: "Trinity variant execution", status: "12 RUNNERS WIRED · E2E PENDING", tone: "partial", body: "All twelve variant runners have dedicated completion gates. R3 predates the wiring corrections: 12/12 missions escalated and 0 merged. No post-correction campaign has qualified the full path yet.", href: `${evidenceSource}docs/02-orchestration/topologies/trinity.md`, source: "Trinity variants, gates, and qualification status" },
  { name: "Dissonance pathology marker", status: "CONFIGURABLE · SOFTWARE MODEL", tone: "partial", body: "The marker requires a finite positive threshold and a dissonance ratio above 0.85. It stores the raw score and is not a medical diagnosis or proof of hallucination.", href: `${evidenceSource}crates/genos-biology/src/pathology.rs`, source: "Degenerative-state threshold" },
  { name: "Clinical pathology confidence", status: "DETERMINISTIC · UNCALIBRATED", tone: "partial", body: "Confidence is clamp01(clamp01(severity) × 0.7 + 0.3). It is a deterministic software score, not a calibrated probability, and does not combine the other biopsy evidence.", href: `${evidenceSource}backend/src/services/medical/immuneSurveillanceService.js`, source: "Clinical pathology confidence rule" },
];

export default function EvidencePage() {
  return (
    <div className="page-shell">
      <section className="page-hero section-wrap evidence-hero">
        <Eyebrow>EVIDENCE · CLAIMS AND LIMITS</Eyebrow>
        <h1>A claim is a place<br />to <em>start looking.</em></h1>
        <p>GenOS separates what is wired, what is partial and what is proposed. Follow each reference to the canonical runtime docs for current contracts, tests and limitations.</p>
        <div className="principle-callout"><span>GENOS PRINCIPLE</span><strong>A successful transport is not proof of a valid decision.</strong></div>
      </section>
      <section className="section-wrap section-space evidence-ledger-page">
        <div className="eyebrow">IMPLEMENTATION LEDGER <span className="ledger-refresh">SOURCES IN GENOS @ {evidenceCommit.slice(0, 7)} ↗</span></div>
        <div className="ledger-head"><span>CAPABILITY</span><span>RUNTIME STATUS</span><span>WHAT THE SOURCE SAYS</span><span>SOURCE</span></div>
        {rows.map((row) => <article className="ledger-row" key={row.name}><div className="ledger-name"><span className={`ledger-icon ledger-icon-${row.tone}`} aria-hidden="true">{row.tone === "proposed" ? "⌁" : row.tone === "partial" ? "◌" : "↗"}</span><strong>{row.name}</strong></div><div><span className={`status-chip status-${row.tone}`}><i /> {row.status}</span></div><p>{row.body}</p><a href={row.href} target="_blank" rel="noreferrer" aria-label={`Read source: ${row.source}`}>↗</a></article>)}
        <div className="evidence-note"><span>↳</span><p>Status changes with the runtime. Source documentation is canonical; this ledger is a concise guide and should be reviewed when implementation changes.</p><a href="https://github.com/PISSARAW/GenOS" target="_blank" rel="noreferrer">OPEN GENOS ↗</a></div>
      </section>
      <section className="section-wrap evidence-links"><Eyebrow>GO DEEPER</Eyebrow><a href="https://github.com/PISSARAW/GenOS/blob/v3/docs/02-orchestration/topologies-et-capacites.md" target="_blank" rel="noreferrer">Topology capability contract <span>↗</span></a><a href="https://github.com/PISSARAW/GenOS/blob/v3/docs/03-reference/plugins-topologies-morphogenese.md" target="_blank" rel="noreferrer">Morphogenesis plugin contract <span>↗</span></a><a href="https://github.com/PISSARAW/GenOS/tree/v3/docs/06-qualite-preuves" target="_blank" rel="noreferrer">Evidence and quality docs <span>↗</span></a></section>
    </div>
  );
}
